d1mach – diva
d1mach Function
8 statements
Source File
pure function d1mach(i) result(d)
Uses
iso_fortran_env
Replacement for the old D1MACH routine.
 d1mach(1) = b**(emin-1), the smallest positive magnitude.
 d1mach(2) = b**emax*(1 - b**(-t)), the largest magnitude.
 d1mach(3) = b**(-t), the smallest relative spacing.
 d1mach(4) = b**(1-t), the largest relative spacing.
 d1mach(5) = log10(b)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
Return Value real(kind=rp)
Called by
Contents
Source Code
d1mach
Source Code
    pure function d1mach(i) result(d)
    use iso_fortran_env, only: rp => real64
    implicit none
    integer,intent(in) :: i
    real(rp) :: d
    real(rp),dimension(5),parameter :: constants = &
        [tiny(1.0_rp), &
         huge(1.0_rp), &
         real(radix(1.0_rp),rp)**(-digits(1.0_rp)), &
         epsilon(1.0_rp), &
         log10(real(radix(1.0_rp),rp))]
    d = constants(i)
    end function d1mach
Call graph
divaop calls d1mach
dmess calls d1mach
dzero calls d1mach, dmess
drdivx calls dmess, diva, divadb
diva calls divaop, dmess
divag calls dmess
divaa calls dmess
divadb calls dmess
divacr calls dmess
divain calls dmess
drdivdb calls diva, divadb
divao calls divag
drdiva calls diva