DIVACR – diva
DIVACR Subroutine
377 statements
Source File
subroutine DIVACR(Y, F, KORD, TOL, LGROUP)
Arguments
Type Intent Optional Attributes Name
double precision :: Y(*)
double precision :: F(*)
integer :: KORD(*)
1988-08-25 DIVACR Krogh Fix bug in relative error test. 1988-01-15 DIVACR Krogh Initial code.
THIS SUBROUTINE 1. CORRECTS Y FOR EQUATIONS WHICH ARE NOT STIFF 2. ESTIMATES ERRORS 3. SELECTS INTEGRATION ORDERS 4. TESTS IF NOISE LIMITS THE PRECISION
 Y = VECTOR OF PREDICTED VALUES ON ENTRY, AND OF CORRECTED
     VALUES WHEN THE RETURN IS MADE.
LGROUP= VECTOR INDICATING HOW ERROR TOLERANCES ARE TO BE GROUPED (AND POSSIBLY HOW INTEGRATION ORDERS ARE TO BE GROUPED). TOL = VECTOR CONTAINING ERROR TOLERANCES (AND POSSIBLY RELATIVE ERROR FACTORS). F = VECTOR GIVING PREDICTED DERIVATIVE VALUES AND DIFF. TABLES. KD = VECTOR GIVING ORDERS OF THE DIFFERENTIAL EQUATIONS (IF EQUATIONS HAVE DIFFERENT ORDERS). KQ = VECTOR OF INTEGRATION ORDERS.
double precision :: TOL(*)
integer :: LGROUP(*)
1988-08-25 DIVACR Krogh Fix bug in relative error test. 1988-01-15 DIVACR Krogh Initial code.
THIS SUBROUTINE 1. CORRECTS Y FOR EQUATIONS WHICH ARE NOT STIFF 2. ESTIMATES ERRORS 3. SELECTS INTEGRATION ORDERS 4. TESTS IF NOISE LIMITS THE PRECISION
 Y = VECTOR OF PREDICTED VALUES ON ENTRY, AND OF CORRECTED
     VALUES WHEN THE RETURN IS MADE.
LGROUP= VECTOR INDICATING HOW ERROR TOLERANCES ARE TO BE GROUPED (AND POSSIBLY HOW INTEGRATION ORDERS ARE TO BE GROUPED). TOL = VECTOR CONTAINING ERROR TOLERANCES (AND POSSIBLY RELATIVE ERROR FACTORS). F = VECTOR GIVING PREDICTED DERIVATIVE VALUES AND DIFF. TABLES. KD = VECTOR GIVING ORDERS OF THE DIFFERENTIAL EQUATIONS (IF EQUATIONS HAVE DIFFERENT ORDERS). KQ = VECTOR OF INTEGRATION ORDERS.
Calls
Contents
Common Blocks
DIVASC DIVAMC DIVAEV
Common Blocks
common /DIVASC/
Type Attributes Name Initial
real :: TN
real :: XI
integer :: IOPST
integer :: KORDI
integer :: KQMAXD
integer :: KQMAXI
integer :: LDT
integer :: MAXDIF
integer :: MAXINT
integer :: NKDKO
integer :: NTE
integer :: NYNY
integer :: NDTF
integer :: NUMDT
common /DIVAMC/
Type Attributes Name Initial
real :: TG
real :: TGSTOP
real :: TMARK
real :: TMARKX
real :: TOUT
real :: TOLG
real :: HC
real :: HDEC
real :: HINC
real :: HINCC
real :: HMAX
real :: HMAXP9
real :: HMIN
real :: ALPHA
real :: BETA
real :: D
real :: G
real :: V
real :: DS
real :: GS
real :: SIGMA
real :: RBQ
real :: DNOISE
real :: EAVE
real :: EIMAX
real :: EIMIN
real :: EMAX
real :: EREP
real :: ROBND
real :: SNOISE
real :: FDAT
integer :: ICF
integer :: ICS
integer :: IGFLG
integer :: IGTYPE
integer :: IGSTOP
integer :: ILGREP
integer :: INGS
integer :: IOP3
integer :: IOP4
integer :: IOP5
integer :: IOP6
integer :: IOP7
integer :: IOP8
integer :: IOP9
integer :: IOP10
integer :: IOP11
integer :: IOP12
integer :: IOP13
integer :: IOP14
integer :: IOP15
integer :: IOP16
integer :: IOP17
integer :: IOP18
integer :: IOP19
integer :: IOP20
integer :: IOP21
integer :: IOP22
integer :: IOP21S
integer :: ITOLEP
integer :: IY
integer :: KEMAX
integer :: KIS
integer :: KMARK
integer :: KORD1I
integer :: KORD2I
integer :: KPRED
integer :: KQDCON
integer :: KQICON
integer :: KQMAXS
integer :: KQMXDS
integer :: KQMXIL
integer :: KQMXIP
integer :: KQMXIS
integer :: KSC
integer :: KSOUT
integer :: KSSTRT
integer :: KSTEP
integer :: LEX
integer :: LINC
integer :: LINCD
integer :: LINCQ
integer :: LSC
integer :: MAXKQD
integer :: MAXKQI
integer :: METHOD
integer :: NE
integer :: NEPTOL
integer :: NG
integer :: NGTOT
integer :: NOISEQ
integer :: NOUTKO
integer :: NTOLF
integer :: NY
integer :: IDAT
common /DIVAEV/
Type Attributes Name Initial
real :: EEPS2
real :: EEPT75
real :: EOVEP2
real :: OVTM75
real :: OVD10
real :: EEPS10
real :: EEPS16
real :: EROV10
Call graph
divacr calls dmess
dmess calls d1mach, messfi