DIVAIN – diva
DIVAIN Subroutine
190 statements
Source File
subroutine DIVAIN(T, Y, F, KORD)
Arguments
Type Intent Optional Attributes Name
double precision :: T(*)
double precision :: Y(*)
double precision :: F(*)
integer :: KORD(*)
1988-01-14 DIVAIN Krogh Initial code.
SUBROUTINE TO DO INTERPOLATION FOR VARIABLE ORDER INTEG. ROUTINE
Calls
Contents
Common Blocks
DIVASC
Common Blocks
common /DIVASC/
Type Attributes Name Initial
real :: TN
real :: XI
integer :: IOPST
integer :: KORDI
integer :: KQMAXD
integer :: KQMAXI
integer :: LDT
integer :: MAXDIF
integer :: MAXINT
integer :: NKDKO
integer :: NTE
integer :: NYNY
integer :: NDTF
integer :: NUMDT
Call graph
divain calls dmess
dmess calls messfi, d1mach