DIVAG – diva
DIVAG Subroutine
181 statements
Source File
public subroutine DIVAG(TSPECS, Y, F, KORD, IFLAG, NSTOP, GNEW, GT)
SUBROUTINE TO LOCATE OUTPUT POINTS AT ZEROS OF ARBITRARY FUNCTIONS * GSTOPS * FOR DIFFERENTIAL EQUATION INTEGRATOR -ODE (OR -IVA).
History
2001-09-07 DIVAG Krogh Changes to allow user tol on G-Stops.
1995-06-20 DIVAG Krogh Fixed problem introduced with last change.
1995-05-09 DIVAG Krogh Fixed G-Stop/discontinuity code interaction
1994-11-11 DIVAG Krogh Declared all vars.
1994-10-20 DIVAG Krogh Changes to use M77CON
1994-09-12 DIVAG Krogh Added CHGTYP code.
1994-08-17 DIVAG Krogh Modified internal comment.
1994-03-07 DIVAG Krogh Allow larger order in single precision.
1993-04-27 DIVAG Krogh Additions for Conversion to C.
1992-10-12 DIVAG Krogh Fixed G-Stop/discontinuity code interaction
1992-09-17 DIVAG Krogh Slight change in check for sign change.
1992-04-08 DIVAG Krogh Unused labels 140,150,230, and 250 removed.
1992-03-10 DIVAG Krogh Fixed value for KDIM in single p. version.
1990-01-29 DIVAG Krogh Added arg to call to DERMN.
1988-03-04 DIVAG Krogh Initial code.
Arguments
Type Intent Optional Attributes Name
double precision :: TSPECS(*)
double precision :: Y(*)
double precision :: F(*)
integer :: KORD(*)
integer :: IFLAG
integer :: NSTOP
double precision :: GNEW(*)
double precision :: GT(*)
Calls
Called by
Contents
Common Blocks
DIVAEV DIVASC DIVAMC
Source Code
DIVAG
Common Blocks
common /DIVAEV/
Type Attributes Name Initial
real :: EEPS2
real :: EEPT75
real :: EOVEP2
real :: OVTM75
real :: OVD10
real :: EEPS10
real :: EEPS16
real :: EROV10
common /DIVASC/
Type Attributes Name Initial
real :: TN
real :: XI
integer :: IOPST
integer :: KORDI
integer :: KQMAXD
integer :: KQMAXI
integer :: LDT
integer :: MAXDIF
integer :: MAXINT
integer :: NKDKO
integer :: NTE
integer :: NYNY
integer :: NDTF
integer :: NUMDT
common /DIVAMC/
Type Attributes Name Initial
real :: TG
real :: TGSTOP
real :: TMARK
real :: TMARKX
real :: TOUT
real :: TOLG
real :: HC
real :: HDEC
real :: HINC
real :: HINCC
real :: HMAX
real :: HMAXP9
real :: HMIN
real :: ALPHA
real :: BETA
real :: D
real :: G
real :: V
real :: DS
real :: GS
real :: SIGMA
real :: RBQ
real :: DNOISE
real :: EAVE
real :: EIMAX
real :: EIMIN
real :: EMAX
real :: EREP
real :: ROBND
real :: SNOISE
real :: FDAT
integer :: ICF
integer :: ICS
integer :: IGFLG
integer :: IGTYPE
integer :: IGSTOP
integer :: ILGREP
integer :: INGS
integer :: IOP3
integer :: IOP4
integer :: IOP5
integer :: IOP6
integer :: IOP7
integer :: IOP8
integer :: IOP9
integer :: IOP10
integer :: IOP11
integer :: IOP12
integer :: IOP13
integer :: IOP14
integer :: IOP15
integer :: IOP16
integer :: IOP17
integer :: IOP18
integer :: IOP19
integer :: IOP20
integer :: IOP21
integer :: IOP22
integer :: IOP21S
integer :: ITOLEP
integer :: IY
integer :: KEMAX
integer :: KIS
integer :: KMARK
integer :: KORD1I
integer :: KORD2I
integer :: KPRED
integer :: KQDCON
integer :: KQICON
integer :: KQMAXS
integer :: KQMXDS
integer :: KQMXIL
integer :: KQMXIP
integer :: KQMXIS
integer :: KSC
integer :: KSOUT
integer :: KSSTRT
integer :: KSTEP
integer :: LEX
integer :: LINC
integer :: LINCD
integer :: LINCQ
integer :: LSC
integer :: MAXKQD
integer :: MAXKQI
integer :: METHOD
integer :: NE
integer :: NEPTOL
integer :: NG
integer :: NGTOT
integer :: NOISEQ
integer :: NOUTKO
integer :: NTOLF
integer :: NY
integer :: IDAT
Source Code
    subroutine DIVAG(TSPECS, Y, F, KORD, IFLAG, NSTOP, GNEW, GT)
      integer KORD(*), IFLAG, NSTOP
!--D Next line special: P=>D, X=>Q
      double precision TSPECS(*), Y(*), TOLD, TSAVE
      double precision F(*), GNEW(*), GT(*), GOLD
      save GOLD, TOLD, TSAVE
!
!++SP Default KDIM = 16
!++  Default KDIM = 20
!++  Default MAXORD = 2, MAXSTF = 1
      integer KDIM, MAXORD, MAXSTF
!++ Substitute for KDIM, MAXORD, MAXSTF below
      parameter (KDIM = 20, MAXORD = 2, MAXSTF = 1)
!--D Next line special: P=>D, X=>Q
      double precision TN
      double precision XI(KDIM)
!
!--D Next line special: P=>D, X=>Q
      double precision TG(2), TGSTOP(2), TMARK, TMARKX, TOUT, TOLG
      double precision ALPHA(KDIM), BETA(KDIM+1)
      double precision  D(MAXSTF+MAXORD,MAXORD), G(KDIM,MAXORD)
      double precision V(KDIM+MAXORD)
      double precision HC, HDEC, HINC, HINCC, HMAX, HMAXP9, HMIN
      double precision FDAT(11)
!
      double precision DS(MAXSTF+MAXORD, MAXORD), GS(KDIM)
      double precision SIGMA(KDIM), RBQ(KDIM), DNOISE
      double precision EAVE, EIMAX, EIMIN, EMAX, EREP, ROBND, SNOISE
!
!.    SPECIFICATION OF ENVIRONMENTAL CONSTANTS.
      double precision EEPS10, EEPS16, EROV10, EEPS2
      double precision EEPT75, EOVEP2, OVTM75, OVD10
      common / DIVAEV / EEPS2, EEPT75, EOVEP2, OVTM75, OVD10, EEPS10,   &
     &   EEPS16, EROV10
      save / DIVAEV /
      integer IOPST, KORDI, KQMAXD, KQMAXI, LDT, MAXDIF, MAXINT, NKDKO, &
     &   NTE, NYNY, NDTF, NUMDT
      common / DIVASC / TN, XI, IOPST, KORDI, KQMAXD, KQMAXI, LDT,      &
     &   MAXDIF, MAXINT, NKDKO, NTE, NYNY, NDTF, NUMDT
!
      integer ICF,ICS,IGFLG,IGTYPE(2),IGSTOP(2),ILGREP,INGS,IOP3,IOP4,  &
     &   IOP5,IOP6,IOP7,IOP8,IOP9,IOP10,IOP11,IOP12,IOP13,IOP14,IOP15,  &
     &   IOP16,IOP17,IOP18,IOP19,IOP20,IOP21,IOP22,IOP21S,ITOLEP,IY,    &
     &   KEMAX,KIS,KMARK,KORD1I,KORD2I,KPRED,KQDCON,KQICON,KQMAXS,      &
     &   KQMXDS,KQMXIL,KQMXIP,KQMXIS,KSC,KSOUT,KSSTRT,KSTEP,LEX,LINC,   &
     &   LINCD,LINCQ,LSC,MAXKQD,MAXKQI,METHOD,NE,NEPTOL,NG,NGTOT,       &
     &   NOISEQ,NOUTKO,NTOLF,NY,IDAT(6)
      common /DIVAMC/ TG,TGSTOP,TMARK,TMARKX,TOUT,TOLG,HC,HDEC,HINC,    &
     &   HINCC,HMAX,HMAXP9,HMIN,ALPHA,BETA,D,G,V,DS,GS,SIGMA,RBQ,DNOISE,&
     &   EAVE,EIMAX,EIMIN,EMAX,EREP,ROBND,SNOISE,FDAT,ICF,ICS,IGFLG,    &
     &   IGTYPE,IGSTOP,ILGREP,INGS,IOP3,IOP4,IOP5,IOP6,IOP7,IOP8,IOP9,  &
     &   IOP10,IOP11,IOP12,IOP13,IOP14,IOP15,IOP16,IOP17,IOP18,IOP19,   &
     &   IOP20,IOP21,IOP22,IOP21S,ITOLEP,IY,KEMAX,KIS,KMARK,KORD1I,     &
     &   KORD2I,KPRED,KQDCON,KQICON,KQMAXS,KQMXDS,KQMXIL,KQMXIP,KQMXIS, &
     &   KSC,KSOUT,KSSTRT,KSTEP,LEX,LINC,LINCD,LINCQ,LSC,MAXKQD,MAXKQI, &
     &   METHOD,NE,NEPTOL,NG,NGTOT,NOISEQ,NOUTKO,NTOLF,NY,IDAT
      save / DIVAMC / , / DIVASC /
!
      integer I, IG, IGFLGS, IZFLAG, KEXIT, NGSTOP(2)
      double precision HH
      equivalence (G(1,1), HH), (NGSTOP(1), IOP6), (KEXIT, IOP17),      &
     &   (IZFLAG, IY), (IGFLGS, ITOLEP)
!
!                      Declarations for error message processing.
!
      integer MEMDA1, MERET, MEEMES
      parameter (MEMDA1 =27)
      parameter (MERET  =51)
      parameter (MEEMES =52)
      integer MACT(7)
! ********* Error message text ***************
![Last 2 letters of Param. name]  [Text generating message.]
!AA DIVAG$B
!AB Call with bad values of KORD.  KORD(1)=$I, KORD(2)=$I, when $C
!   TSPECS(1)=$F and KSTEP=$M.$E
      integer LTXTAA,LTXTAB
      parameter (LTXTAA= 1,LTXTAB= 8)
      character MTXTAA(1) * (95)
      data MTXTAA/'DIVAG$BCall with bad values of KORD.  KORD(1)=$I, KOR&
     &D(2)=$I, when TSPECS(1)=$F and KSTEP=$M.$E'/
      data MACT / MEMDA1, 0, MEEMES, 68, 24, 0, MERET /
!
! ****************** START OF EXECUTABLE CODE **************
!
      IFLAG = 1
      IG = KORD(2)
      if ((IG /= 0) .and. (IG /= 1)) go to 500
      if (IGFLG - 3) 10, 80, 70
   10 if (IGFLG - 1) 20, 210, 60
!
! ******************** INITIAL POINT ***********************
!
   20 if (IGFLG == -3) then
         IGFLG = 5
         return
      end if
      IGTYPE(IG + 1) = 0
      if ((NGSTOP(IG + 1) <= 0) .or. (IG + IGFLG == -1)) go to 30
      IGFLG = IG - 2
      go to 40
   30 IGFLG = 5
   40 NG = NGSTOP(2 - IG)
      do 50 I = 1, NG
   50    GT(I) = GNEW(I)
      go to 480
!
!     **** USER HAS BEEN TOLD THAT A GSTOP WAS FOUND
!          TEST IF CALLED FROM OUTPUT WHEN CALL SHOULD
!          BE FROM DERIVS
   60 if ((IGTYPE(1) == 0) .and. (IG /= 0)) go to 420
!     **** PROTECT AGAINST NOISEY G NEAR THE ZERO
      if (GNEW(INGS) == 0.D0) GNEW(INGS) = GT(INGS)
!
! ****** TEST FOR CHANGE IN THE SIGN OF A G ****************
!
   70 NG = NGSTOP(2 - IG)
      INGS = 0
   80 INGS = INGS + 1
      if (INGS > NG) if (IGFLG - 4) 400, 380, 480
      if (GNEW(INGS)) 90, 100, 110
   90 if (GT(INGS)) 120, 120, 130
  100 if (GT(INGS)) 130, 80, 130
  110 if (GT(INGS)) 130, 120, 120
  120 GT(INGS) = GNEW(INGS)
      go to 80
!
! ********* A SIGN CHANGE HAS BEEN FOUND *******************
!
  130 NSTOP = INGS
      if (IG == 0) NSTOP = -INGS
      if (IGFLG /= 5) go to 200
!     **** USUAL CASE -- TEST IF OUTPUT POINT PRECEDES THE
!          SIGN CHANGE, OR IF PREDICTING, CORRECTING, OR
!          NOT THROUGH THE FIRST STEP.
!     **** TEST IF AN INTERPOLATED G WAS WHAT CHANGED SIGN
      if (IG /= 0) go to 180
!     **** BACK UP DIFFERENCES AND OTHER STUFF TO BEGINNING
!          OF THE STEP
      call DIVABU(F, KORD)
!     **** TEST IF CORRECTING
      if (KORD1I == 2) go to 170
!     **** TEST IF THROUGH THE FIRST STEP
      if (LSC < 4) go to 180
!     **** IF FIRST DERIVATIVE EVALUATION OF THE FIRST
!          STEP, FIND THE GSTOP, AND USE IT TO GET A NEW
!          INITIAL STEPSIZE
      if (LSC == 7) go to 200
!     **** SET NEW STEPSIZE AFTER SIGN CHANGE WHEN STARTING
  160 HH = TSPECS(1) - TN
!     **** SET KEXIT TO TRY NEW STEPSIZE
  170 KEXIT = 1
      TSPECS(1) = TN
      go to 460
!     **** SET KEXIT FOR USUAL CASE
  180 KEXIT = IG + 2
!     **** TEST IF SIGN CHANGE IN G PRECEDES NEXT OUTPUT PT.
      if (HH * (TSPECS(1) - TMARK)) 200, 200, 190
!     **** SET UP TO EVALUATE G AT OUTPUT POINT
  190 IGFLG = 4
      TSPECS(1) = TMARK
      NSTOP = 0
      go to 240
!
! ***************** FIND THE ZERO OF G *********************
!
!     **** INITIALIZE ZERO FINDER
  200 TOLD = TG(2 - IG)
      GOLD = GT(INGS)
      TSAVE = TSPECS(1)
      IGFLGS = IGFLG
      IGFLG = 1
      IZFLAG = 0
      go to 220
!     **** TEST IF ZERO ALREADY FOUND
  210 if (IZFLAG - 1) 350, 220, 310
  220 continue
      call DZERO(TSPECS(1), GNEW(INGS), TOLD, GOLD, IZFLAG, TOLG)
!     **** TEST FOR CONVERGENCE
      if (IZFLAG /= 1) go to 260
!     **** INTERPOLATE NEW Y, AND GO COMPUTE G AGAIN
  240 call DIVAIN(TSPECS(1), Y, F, KORD)
      IFLAG = 4
      KORD2I = IG - 3
      return
!     **** CONVERGENCE -- CHOOSE TOLD TO GIVE A CHANGE
!          IN SIGN
  260 if (GNEW(INGS) == 0.D0) go to 290
      if (TSPECS(1) - TOLD) 270, 300, 280
  270 if (HH) 290, 300, 300
  280 if (HH) 300, 300, 290
  290 TOLD = TSPECS(1)
!     **** CHECK IF SIGN CHANGE DUE TO NOISE
  300 TSPECS(1) = TOLD + XI(1)
      go to 240
  310 TSPECS(1) = TOLD
      if (GNEW(INGS)) 320, 340, 330
  320 if (GT(INGS)) 340, 360, 360
  330 if (GT(INGS)) 360, 360, 340
!     **** ZERO WAS EVIDENTLY DUE TO NOISE
  340 TSPECS(1) = TSAVE
      IZFLAG = 0
      go to 370
  350 IGFLG = IGFLGS
!     SET KORD2I TO INITIAL VALUE TO AVOID LOOP
      KORD2I = IG
      go to 80
!     **** SAVE INFORMATION ABOUT THE STOP
  360 IGFLG = 3
      TGSTOP(2 - IG) = TSPECS(1)
      IGTYPE(2 - IG) = IZFLAG + 3
      IGSTOP(2 - IG) = NSTOP
  370 NSTOP = 0
      go to 240
!
! ************** AFTER SEARCH FOR A SIGN CHANGE ************
!
!     **** NO SIGN CHANGE AT A T OUTPUT POINT
!     TEST IF CALLED FROM OUTPUT
  380 if (IG /= 0) go to 390
!     SET UP FOR CALL TO OUTPUT
      KORD1I = 7
      KORD2I = -2
      IFLAG = 3
      go to 480
!     **** ADJUST KEXIT AND SET UP TO GIVE OUTPUT
  390 KEXIT = KEXIT + 2
      KORD1I = min(KMARK, 5)
      KORD(3) = KMARK
      KORD(1) = KORD1I
      IGFLG = 5
      IFLAG = 2
      go to 470
!     **** TEST IF USER HAS BEEN TOLD OF GSTOP
  400 if (IGFLG == 2) go to 450
!     **** A GSTOP HAS BEEN FOUND
!     TEST IF STARTING
      if (LSC == 7) go to 160
      IFLAG = IGTYPE(2 - IG)
      NSTOP = IGSTOP(2 - IG)
      INGS = abs(NSTOP)
      if (INGS == 0) go to 410
      GT(INGS) = -GT(INGS)
      if (IG == 0) go to 430
      IGFLG = 2
!     If interpolated GSTOP was found set to check again in case of
!     multiple stops at exactly the same point.
      if (IGTYPE(1) /= 0) go to 440
!     **** TELL USER OF AN EXTRAPOLATED GSTOP
  410 IFLAG = IGTYPE(2)
      NSTOP = IGSTOP(2)
      INGS = abs(NSTOP)
!     **** SET SO DERIVS IS CALLED WITH KORD(1) = KPRED
  420 KORD1I = KPRED
      KORD2I = -3
      return
!     **** AN EXTRAPOLATED GSTOP WAS FOUND, SET UP TO CHECK
!          INTERPOLATED STOPS (IF ANY)
  430 NG = NGSTOP(1)
      INGS = 0
      IFLAG = 3
      NSTOP = IGSTOP(2)
!     **** SET SO OUTPUT IS CALLED WITH KORD(1) = 7
  440 KORD1I = 7
      KORD2I = -2
      go to 490
!     **** CHECK THAT AN EXTRAPOLATED G-STOP IS NOT MISSED
  450 if ((IG == 0) .or. (IGTYPE(2) == 0)) go to 460
!     SET TO CHECK FOR INTERPOLATED G-S.
      TG(1) = TSPECS(1)
      IGTYPE(1) = 0
      TSPECS(1) = TGSTOP(2)
      INGS = 0
      IGFLG = 3
      go to 240
!     **** SET SO INTEGRATOR GOES TO PLACE DIRECTED BY KEXIT
  460 NSTOP = 0
      IGFLG = 5
      IFLAG = 3
  470 KORD2I = -7
!     **** STORE INFO. ON LAST G COMPUTED
  480 IGTYPE(2 - IG) = 0
  490 TG(2 - IG) = TSPECS(1)
      return
!
! ********************** ERROR PROCESSING ******************
!
  500 MACT(2) = KSTEP
!--D Next line special: P=>S, X=>D
      call DMESS(MACT, MTXTAA, KORD, TSPECS)
      IFLAG = 8
      KEXIT = 6
      go to 470
    end subroutine divag
Call graph
divag calls dmess, divabu
dmess calls messfi
divao calls divag