DIVADB – diva
DIVADB Subroutine
179 statements
Source File
public subroutine DIVADB(LPRINT, TSPECS, Y, F, KORD, TEXT)
2009-11-04 DIVADB Krogh Included TOLG, initilized the unitialized.
2000-12-01 DIVADB Krogh Removed unused parameter METXTF.
1996-07-02 DIVADB Krogh Transpose flag for matrix output in C.
1996-03-25 DIVADB Krogh Introduced TEXT1-TEXT4 to comply with F77.
1996-01-19 DIVADB Krogh Changed NTEXT to TEXT to agree with doc.
1995-04-26 DIVADB Krogh Fixed print of V & G's for high order eqs.
1994-11-11 DIVADB Krogh Declared all vars.
1994-10-20 DIVADB Krogh Changes to use M77CON
1994-09-12 DIVADB Krogh Added CHGTYP code.
1994-03-07 DIVADB Krogh Allow larger order in single precision.
1993-05-03 DIVADB Krogh Additions for Conversion to C.
1993-04-14 DIVADB Krogh Changes for new MESS usage.
1992-04-08 DIVADB Krogh Unused labels 10 and 60 removed.
1992-03-10 DIVADB Krogh Fixed value for KDIM in single p. version.
1992-02-17 DIVADB Krogh Made tabs depend on # digits output.
1991-11-04 DIVADB Krogh Switched to use MESS, DMESS
1990-03-08 DIVADB Krogh Unused stiff vars. set to 0.
1989-07-21 DIVADB Krogh Code for integrating discontinuities
1988-06-07 DIVADB Krogh Dim. of IVC2 and DVC2 upped by 1 (old bug)
1987-12-07 DIVADB Krogh Initial code.
--D replaces "?": ?IVADB, ?IVAEV, ?IVAMC, ?IVASC, ?MESS
SUBROUTINE TO GIVE DEBUG PRINT FOR VARIABLE ORDER INTEGRATOR
LET ABS(LPRINT)= 10*N1 + N2 (N1,N2 DIGITS) N1=1 DO NOT PRINT ANY VARIABLES EXTERNAL TO THE INTEGRATOR N1=2 PRINT TSPECS, CURRENT Y, PAST Y, CURRENT F, ALL PERTINENT CONTENTS OF KORD, AND TOL. N1=3 ABOVE + DIFFERENCE TABLES UP TO HIGHEST DIFFERENCE USED N1=4 SAME AS N1=1 + ALL IN STORAGE ALLOCATED FOR DIFFERENCES
N2=1   DO NOT PRINT ANY VARIABLES INTERNAL TO THE INTEGRATOR
N2=2   PRINT ALL SCALAR VARIABLES IN INTERPOLATION COMMON BLOCK
N2=3   ABOVE + ALL SCALAR VARIABLES IN MAIN INTEG. COMMON BLOCK
N2=4   SAME AS N1=3 + ALL USED IN ARRAYS XI,BETA,ALPHA, FIRST
       COLUMN OF G, GS,RBQ,SIGMA
N2=5   SAME AS N1=4 + ALL USED IN ARRAYS G,D,DS,V
Arguments
Type Intent Optional Attributes Name
integer :: LPRINT
double precision :: TSPECS(*)
double precision :: Y(*)
double precision :: F(*)
integer :: KORD(*)
character :: TEXT*(*)
Calls
Called by
Contents
Common Blocks
DIVAEV DIVASC DIVAMC
Source Code
DIVADB
Common Blocks
common /DIVAEV/
Type Attributes Name Initial
real :: EEPS2
real :: EEPT75
real :: EOVEP2
real :: OVTM75
real :: OVD10
real :: EEPS10
real :: EEPS16
real :: EROV10
common /DIVASC/
Type Attributes Name Initial
real :: TN
real :: XI
integer :: IOPST
integer :: KORDI
integer :: KQMAXD
integer :: KQMAXI
integer :: LDT
integer :: MAXDIF
integer :: MAXINT
integer :: NKDKO
integer :: NTE
integer :: NYNY
integer :: NDTF
integer :: NUMDT
common /DIVAMC/
Type Attributes Name Initial
real :: TG
real :: TGSTOP
real :: TMARK
real :: TMARKX
real :: TOUT
real :: TOLG
real :: HC
real :: HDEC
real :: HINC
real :: HINCC
real :: HMAX
real :: HMAXP9
real :: HMIN
real :: ALPHA
real :: BETA
real :: D
real :: G
real :: V
real :: DS
real :: GS
real :: SIGMA
real :: RBQ
real :: DNOISE
real :: EAVE
real :: EIMAX
real :: EIMIN
real :: EMAX
real :: EREP
real :: ROBND
real :: SNOISE
real :: FDAT
integer :: ICF
integer :: ICS
integer :: IGFLG
integer :: IGTYPE
integer :: IGSTOP
integer :: ILGREP
integer :: INGS
integer :: IOP3
integer :: IOP4
integer :: IOP5
integer :: IOP6
integer :: IOP7
integer :: IOP8
integer :: IOP9
integer :: IOP10
integer :: IOP11
integer :: IOP12
integer :: IOP13
integer :: IOP14
integer :: IOP15
integer :: IOP16
integer :: IOP17
integer :: IOP18
integer :: IOP19
integer :: IOP20
integer :: IOP21
integer :: IOP22
integer :: IOP21S
integer :: ITOLEP
integer :: IY
integer :: KEMAX
integer :: KIS
integer :: KMARK
integer :: KORD1I
integer :: KORD2I
integer :: KPRED
integer :: KQDCON
integer :: KQICON
integer :: KQMAXS
integer :: KQMXDS
integer :: KQMXIL
integer :: KQMXIP
integer :: KQMXIS
integer :: KSC
integer :: KSOUT
integer :: KSSTRT
integer :: KSTEP
integer :: LEX
integer :: LINC
integer :: LINCD
integer :: LINCQ
integer :: LSC
integer :: MAXKQD
integer :: MAXKQI
integer :: METHOD
integer :: NE
integer :: NEPTOL
integer :: NG
integer :: NGTOT
integer :: NOISEQ
integer :: NOUTKO
integer :: NTOLF
integer :: NY
integer :: IDAT
Source Code
    subroutine DIVADB(LPRINT, TSPECS, Y, F, KORD, TEXT)
      integer LPRINT, KORD(*)
      character TEXT*(*)
      character TEXT1(1)*11, TEXT2(1)*4, TEXT3(1)*5, TEXT4(1)*4
      integer IVC1(12), IVC2(65), J, K, L, N1, N2
      double precision  DVC2(7), RVC2(8), EVC(8)
!--D Next line special: P=>D, X=>Q
      double precision TSPECS(*), Y(*), TNEQ(1), DVC1(7)
      double precision F(*)
!
!++S Default KDIM = 16
!++  Default KDIM = 20
!++  Default MAXORD = 2, MAXSTF = 1
!++  Default STIFF=.F.
      integer KDIM, MAXORD, MAXSTF
!++ Substitute for KDIM, MAXORD, MAXSTF below
      parameter (KDIM = 20, MAXORD = 2, MAXSTF = 1)
!--D Next line special: P=>D, X=>Q
      double precision TN
      double precision XI(KDIM)
!
!--D Next line special: P=>D, X=>Q
      double precision TG(2), TGSTOP(2), TMARK, TMARKX, TOUT, TOLG
      double precision ALPHA(KDIM), BETA(KDIM+1)
      double precision  D(MAXSTF+MAXORD,MAXORD), G(KDIM,MAXORD)
      double precision V(KDIM+MAXORD)
      double precision HC, HDEC, HINC, HINCC, HMAX, HMAXP9, HMIN
      double precision FDAT(11)
!
      double precision DS(MAXSTF+MAXORD, MAXORD), GS(KDIM)
      double precision SIGMA(KDIM), RBQ(KDIM), DNOISE
      double precision EAVE, EIMAX, EIMIN, EMAX, EREP, ROBND, SNOISE
!
!.    SPECIFICATION OF ENVIRONMENTAL CONSTANTS.
      double precision EEPS10, EEPS16, EROV10, EEPS2
      double precision EEPT75, EOVEP2, OVTM75, OVD10
      common / DIVAEV / EEPS2, EEPT75, EOVEP2, OVTM75, OVD10, EEPS10,   &
     &   EEPS16, EROV10
      save / DIVAEV /
      integer IOPST, KORDI, KQMAXD, KQMAXI, LDT, MAXDIF, MAXINT, NKDKO, &
     &   NTE, NYNY, NDTF, NUMDT
      common / DIVASC / TN, XI, IOPST, KORDI, KQMAXD, KQMAXI, LDT,      &
     &   MAXDIF, MAXINT, NKDKO, NTE, NYNY, NDTF, NUMDT
!
      integer ICF,ICS,IGFLG,IGTYPE(2),IGSTOP(2),ILGREP,INGS,IOP3,IOP4,  &
     &   IOP5,IOP6,IOP7,IOP8,IOP9,IOP10,IOP11,IOP12,IOP13,IOP14,IOP15,  &
     &   IOP16,IOP17,IOP18,IOP19,IOP20,IOP21,IOP22,IOP21S,ITOLEP,IY,    &
     &   KEMAX,KIS,KMARK,KORD1I,KORD2I,KPRED,KQDCON,KQICON,KQMAXS,      &
     &   KQMXDS,KQMXIL,KQMXIP,KQMXIS,KSC,KSOUT,KSSTRT,KSTEP,LEX,LINC,   &
     &   LINCD,LINCQ,LSC,MAXKQD,MAXKQI,METHOD,NE,NEPTOL,NG,NGTOT,       &
     &   NOISEQ,NOUTKO,NTOLF,NY,IDAT(6)
      common /DIVAMC/ TG,TGSTOP,TMARK,TMARKX,TOUT,TOLG,HC,HDEC,HINC,    &
     &   HINCC,HMAX,HMAXP9,HMIN,ALPHA,BETA,D,G,V,DS,GS,SIGMA,RBQ,DNOISE,&
     &   EAVE,EIMAX,EIMIN,EMAX,EREP,ROBND,SNOISE,FDAT,ICF,ICS,IGFLG,    &
     &   IGTYPE,IGSTOP,ILGREP,INGS,IOP3,IOP4,IOP5,IOP6,IOP7,IOP8,IOP9,  &
     &   IOP10,IOP11,IOP12,IOP13,IOP14,IOP15,IOP16,IOP17,IOP18,IOP19,   &
     &   IOP20,IOP21,IOP22,IOP21S,ITOLEP,IY,KEMAX,KIS,KMARK,KORD1I,     &
     &   KORD2I,KPRED,KQDCON,KQICON,KQMAXS,KQMXDS,KQMXIL,KQMXIP,KQMXIS, &
     &   KSC,KSOUT,KSSTRT,KSTEP,LEX,LINC,LINCD,LINCQ,LSC,MAXKQD,MAXKQI, &
     &   METHOD,NE,NEPTOL,NG,NGTOT,NOISEQ,NOUTKO,NTOLF,NY,IDAT
      save / DIVAMC / , / DIVASC /
      equivalence (IVC1(1), IOPST), (IVC2(1), ICF)
      equivalence (TNEQ, TN)
      equivalence (RVC2(1), DNOISE), (DVC1(1), TG), (DVC2(1), HC),      &
     &   (EVC(1), EEPS2)
!
!                      Declarations for error message processing.
      integer MEDDIG, NEDDIG, METDIG, METABS, MERET, METEXT,            &
     &   METABL, MEIVEC, MEFVEC, MEFMAT
      parameter (MEDDIG =12)
      parameter (NEDDIG =-MEDDIG)
      parameter (METDIG =22)
      parameter (METABS =32)
      parameter (MERET  =51)
      parameter (METEXT =53)
      parameter (METABL =55)
      parameter (MEIVEC =57)
      parameter (MEFVEC =61)
      parameter (MEFMAT =62)
      integer MACT0(3), MACT1(2), MACT2(7), MACT3(7), MACT4(8),         &
     &   MACT5(11), MACT6(3), MACT7(14), MACTFV(4)
      integer KPI, KPE
!                      wddtrr        wwddtrr
      parameter (KPI = 400301, KPE = 1305501)
!
! ********* Error message text ***************
![Last 2 letters of Param. name]  [Text generating message.]
!AA $NKORD:    $B
!AB Int. Ord.: $B
!   $
!AC D.E. Ord.: $B
!   $
!AD Meth.Type: $B
!   $
!AE Tolerance Groups: $B
!AF Tolerances: $B
!   $
!AG $NDifferences$B
!AH Eq. $#
!AI Ord. $#
!   $
!AJ $NTN=$F$E
!   $
!AK $NIOPST=$I$TKORDI=$I$TKQMAXD=$I$TKQMAXI=$I$TLDT=$I$T$C
!   MAXDIF=$I$TMAXINT=$I$TNKDKO=$I$TNTE=$I$TNYNY=$I$TNDTF=$I$C
!   $TNUMDT=$I$E
!   $
!AL $NICF=$I$TICS=$I$TIGFLG=$I$TIGTYPE(1)=$I$TIGTYPE(2)=$I$T$C
!   IGSTOP(1)=$I$TIGSTOP(2)=$I$TILGREP=$I$TINGS=$I$TIOP3=$I$T$C
!   IOP4=$I$TIOP5=$I$TIOP6=$I$TIOP7=$I$TIOP8=$I$TIOP9=$I$T$C
!   IOP10=$I$TIOP11=$I$TIOP12=$I$TIOP13=$I$TIOP14=$I$TIOP15=$I$T$C
!   IOP16=$I$TIOP17=$I$TIOP18=$I$TIOP19=$I$TIOP20=$I$TIOP21=$I$T$C
!   IOP22=$I$TIOP21S=$I$TITOLEP=$I$TIY=$I$TKEMAX=$I$TKIS=$I$T$C
!   KMARK=$I$TKORD1I=$I$TKORD2I=$I$TKPRED=$I$TKQDCON=$I$T$C
!   KQICON=$I$TKQMAXS=$I$TKQMXDS=$I$TKQMXIL=$I$TKQMXIP=$I$T$C
!   KQMXIS=$I$TKSC=$I$TKSOUT=$I$TKSSTRT=$I$TKSTEP=$I$TLEX=$I$T$C
!   LINC=$I$TLINCD=$I$TLINCQ=$I$TLSC=$I$TMAXKQD=$I$TMAXKQI=$I$T$C
!   METHOD=$I$TNE=$I$TNEPTOL=$I$TNG=$I$TNGTOT=$I$TNOISEQ=$I$T$C
!   NOUTKO=$I$TNTOLF=$I$TNY=$I$E
!AM $NDNOISE=$F$TEAVE=$F$TEIMAX=$F$TEIMIN=$F$TEMAX=$F$T$C
!   EREP=$F$TROBND=$F$E
!   $
!AN $NTG(1)=$F$TTG(2)=$F$TTGSTOP(1)=$F$TTGSTOP(2)=$F$C
!   $TTMARK=$F$TTMARKX=$F$TTOUT=$F$E
!   $
!AO HC=$F$THDEC=$F$THINC=$F$THINCC=$F$THMAX=$F$T$C
!   HMAXP9=$F$THMIN=$F$T$N$E
!   $
!AP K$HXI(K)$HBETA(K)$HALPHA(K)$HG(K,1)$HRBQ(K)$HSIGMA(K)$H
!   GS(K)$HV(K)$HG(K,2..MAXINT)$E
!   $
!AQ $NEEPS2=$F$TEEPT75=$F$TEOVEP2=$F$TOVTM75=$F$TOVD10=$F$T$C
!   EEPS10=$F$TEEPS16=$F$TEROV10=$F$E
      integer LTXTAA,LTXTAB,LTXTAC,LTXTAD,LTXTAE,LTXTAF,LTXTAG,LTXTAH,  &
     & LTXTAI,LTXTAJ,LTXTAK,LTXTAL,LTXTAM,LTXTAN,LTXTAO,LTXTAP,LTXTAQ
      parameter (LTXTAA=  1,LTXTAB= 14,LTXTAC=  1,LTXTAD=  1,LTXTAE=  1,&
     & LTXTAF= 21,LTXTAG=  1,LTXTAH= 16,LTXTAI= 22,LTXTAJ=  1,          &
     & LTXTAK=  1,LTXTAL=  1,LTXTAM=655,LTXTAN=  1,LTXTAO=  1,          &
     & LTXTAP=  1,LTXTAQ=  1)
      character MTXTAA(1) * (26)
      character MTXTAB(1) * (13)
      character MTXTAC(1) * (13)
      character MTXTAD(1) * (34)
      character MTXTAE(1) * (28)
      character MTXTAF(1) * (9)
      character MTXTAG(1) * (120)
      character MTXTAH(3) * (242)
      character MTXTAI(1) * (80)
      character MTXTAJ(1) * (68)
      character MTXTAK(1) * (84)
      character MTXTAL(1) * (88)
      data MTXTAA/'$NKORD:    $BInt. Ord.: $B'/
      data MTXTAB/'D.E. Ord.: $B'/
      data MTXTAC/'Meth.Type: $B'/
      data MTXTAD/'Tolerance Groups: $BTolerances: $B'/
      data MTXTAE/'$NDifferences$BEq. $#Ord. $#'/
      data MTXTAF/'$NTN=$F$E'/
      data MTXTAG/'$NIOPST=$I$TKORDI=$I$TKQMAXD=$I$TKQMAXI=$I$TLDT=$I$TM&
     &AXDIF=$I$TMAXINT=$I$TNKDKO=$I$TNTE=$I$TNYNY=$I$TNDTF=$I$TNUMDT=$I$&
     &E'/
      data MTXTAH/'$NICF=$I$TICS=$I$TIGFLG=$I$TIGTYPE(1)=$I$TIGTYPE(2)=$&
     &I$TIGSTOP(1)=$I$TIGSTOP(2)=$I$TILGREP=$I$TINGS=$I$TIOP3=$I$TIOP4=$&
     &I$TIOP5=$I$TIOP6=$I$TIOP7=$I$TIOP8=$I$TIOP9=$I$TIOP10=$I$TIOP11=$I&
     &$TIOP12=$I$TIOP13=$I$TIOP14=$I$TIOP15=$I$TIOP16=$I$TIOP17','=$I$TI&
     &OP18=$I$TIOP19=$I$TIOP20=$I$TIOP21=$I$TIOP22=$I$TIOP21S=$I$TITOLEP&
     &=$I$TIY=$I$TKEMAX=$I$TKIS=$I$TKMARK=$I$TKORD1I=$I$TKORD2I=$I$TKPRE&
     &D=$I$TKQDCON=$I$TKQICON=$I$TKQMAXS=$I$TKQMXDS=$I$TKQMXIL=$I$TKQMXI&
     &P=$I$TKQMXIS=$I$TKSC=$I$TKSOUT=$I$TKSS','TRT=$I$TKSTEP=$I$TLEX=$I$&
     &TLINC=$I$TLINCD=$I$TLINCQ=$I$TLSC=$I$TMAXKQD=$I$TMAXKQI=$I$TMETHOD&
     &=$I$TNE=$I$TNEPTOL=$I$TNG=$I$TNGTOT=$I$TNOISEQ=$I$TNOUTKO=$I$TNTOL&
     &F=$I$TNY=$I$E$NDNOISE=$F$TEAVE=$F$TEIMAX=$F$TEIMIN=$F$TEMAX=$F$TER&
     &EP=$F$TROBND=$F$E  '/
      data MTXTAI/'$NTG(1)=$F$TTG(2)=$F$TTGSTOP(1)=$F$TTGSTOP(2)=$F$TTMA&
     &RK=$F$TTMARKX=$F$TTOUT=$F$E'/
      data MTXTAJ/'HC=$F$THDEC=$F$THINC=$F$THINCC=$F$THMAX=$F$THMAXP9=$F&
     &$THMIN=$F$T$N$E'/
      data MTXTAK/'K$HXI(K)$HBETA(K)$HALPHA(K)$HG(K,1)$HRBQ(K)$HSIGMA(K)&
     &$HGS(K)$HV(K)$HG(K,2..MAXINT)$E'/
      data MTXTAL/'$NEEPS2=$F$TEEPT75=$F$TEOVEP2=$F$TOVTM75=$F$TOVD10=$F&
     &$TEEPS10=$F$TEEPS16=$F$TEROV10=$F$E'/
!
      data MACT0 / METABS, 10, MERET /
      data MACT1 / METEXT, MERET /
!                       1       2  3       4       5  6      7
      data MACT2 / METEXT, MEIVEC, 3, METEXT, MEIVEC, 0, MERET /
!                       1       2  3       4       5  6      7
      data MACT3 / METEXT, MEIVEC, 0, METEXT, MEFVEC, 0, MERET /
!                       1       2  3  4  5       6       7
      data MACT4 / METEXT, MEFMAT, 0, 0, 0, LTXTAI, LTXTAH, MERET /
!                       1   2       3       4   5       6  7       8
      data MACT5 / METABS, 12, METEXT, METABS, 18, METDIG, 5, METEXT,   &
     &             METABS, 0, MERET /
!                       9 10     11
      data MACT6 / NEDDIG, 0, MERET /
!                         2 3 4   5 6 7 8 9  10  11  12 13 14
      data MACT7 / METABL,0,0,0,KPI,0,0,0,0,KPE,KPE,KPE, 0, 0 /
!                        1       2  3      4
      data MACTFV / METEXT, MEFVEC, 3, MERET /
!
      data TEXT1 / '$NTSPECS:$B' /
      data TEXT2 / 'Y:$B' /
      data TEXT3 / 'YN:$B' /
      data TEXT4 / 'F:$B' /
!
! ********
! START OF CODE -- PRINT TEXT AND SET INDEX FOR F
! ********
!    Getting variables that are not yet assigned some values.
!++  Code for ~STIFF is active
      KQDCON = 0
      KQMXDS = 0
      MAXKQD = 0
!++  End
      GS(1) = 1.D0
      if (IOP6 == 0) then
        IGTYPE(1) = 0
        IGSTOP(1) = 0
        TG(1) = 0.D0
        TGSTOP(1) = 0.D0
      end if
      if (IOP7 == 0) then
        IGTYPE(2) = 0
        IGSTOP(2) = 0
        TG(2) = 0.D0
        TGSTOP(2) = 0.D0
      end if
      if (IOP6 + IOP7 == 0) then
        INGS = 0
        NG = 0
      end if
      if (IOP10 == 0) NOUTKO = 0
      J = 0
      call MESSFT(MACT0, TEXT)
!
      N1 = LPRINT / 10
      N2 = LPRINT - 10 * N1
      if (N1 <= 1) go to 80
! ********
! PRINT ALL EXTERNAL VARIABLES EXCEPT FOR THE DIFFERENCES
! ********
      MACTFV(3) = max(IOP5, 4)
!--D Next line special: P=>D, X=>Q
      call DMESS(MACTFV, TEXT1, KORD, TSPECS)
      MACTFV(3) = NY
!--D Next line special: P=>D, X=>Q
      call DMESS(MACTFV, TEXT2, KORD, Y)
!--D Next line special: P=>D, X=>Q
      call DMESS(MACTFV, TEXT3, KORD, Y(NYNY))
      MACTFV(3) = NTE
!--D Next line special: P=>S, X=>D
      call DMESS(MACTFV, TEXT4, KORD, F)
      MACT2(6) = NTE
      call MESS(MACT2, MTXTAA, KORD)
      if (NKDKO > 0) call MESS(MACT2(4), MTXTAB, KORD(NKDKO))
      if (IOPST > 0) call MESS(MACT2(4), MTXTAC, KORD(IOPST))
! WRITE TOL
      K = IOP16
   70 if (KORD(K) < 0) K = K + 1
      K = K + 1
      if (KORD(K - 1) < NTE) go to 70
      MACT3(3) = K - IOP16
      MACT3(6) = MACT3(3)
!--D Next line special: P=>S, X=>D
      call DMESS(MACT3, MTXTAD, KORD(IOP16), F(NTOLF))
      if (N1 == 2) go to 80
! ********
! WRITE THE DIFFERENCE TABLES
! ********
      K = NUMDT
      if (N1 == 3) K = KQMAXS
      MACT4(3) = NUMDT
      MACT4(4) = -K
      MACT4(5) = NTE
!--D Next line special: P=>S, X=>D
      call DMESS(MACT4, MTXTAE, KORD, F(NDTF))
!
   80 if (N2 <= 1) return
! ********
! WRITE SCALARS IN COMMON
! ********
!--D Next line special: P=>D, X=>Q
      call DMESS(MACT1, MTXTAF, KORD, TNEQ)
!
! ===== COMMON 1  -- INTEGER
!
      call MESS(MACT1, MTXTAG, IVC1)
      if (N2 == 2) return
      call MESS(MACT6, MTXTAA, IDAT)
      MACT5(10) = MACT6(2) + 14
!
! ===== COMMON 2  -- INTEGER AND FLOATING POINT
!
!--D Next line special: P=>S, X=>D
      call DMESS(MACT5, MTXTAH, IVC2, RVC2)
!--D Next line special: P=>D, X=>Q
      call DMESS(MACT1, MTXTAI, IVC2, DVC1)
!--D Next line special: P=>S, X=>D
      call DMESS(MACT1, MTXTAJ, IVC2, DVC2)
      if (N2 == 3) return
!         wddtrr              wddtrr
      J = 101000 * MACT6(2) + 800501
      MACT7(2) = 1
      MACT7(3) = KQMAXS
      MACT7(4) = 8
      do 90 K = 6, 9
         MACT7(K) = J
   90 continue
      if (N2 > 0) then
         MACT7(4) = 8 + MAXINT
         MACT7(13) = J
         L = min(MAXINT, 4)
         MACT7(14) = J + L - 2
      end if
      do 100 K = 1, MACT7(3)
         FDAT(1) = XI(K)
         FDAT(2) = BETA(K)
         FDAT(3) = ALPHA(K)
         FDAT(4) = G(K, 1)
         FDAT(5) = RBQ(K)
         FDAT(6) = SIGMA(K)
         FDAT(7) = GS(K)
         if (N2 >= 4) then
            FDAT(8) = V(K)
            do 95 J = 2, L
               FDAT(7+J) = G(K, J)
   95       continue
         end if
!--D Next line special: P=>S, X=>D
         call DMESS(MACT7, MTXTAK, IDAT, FDAT)
  100 continue
!++  Code for STIFF is inactive
!     if (MAXDIF <= 0) return
!        Need to define MACT8 and set values
!c--D Next line special: P=>S, X=>D
!     call DMESS(MACT8, 'D$B', IDAT, D)
!c--D Next line special: P=>S, X=>D
!     call DMESS(MACT8, 'DS$B', IDAT, DS)
!++  End
!
!--D Next line special: P=>S, X=>D
      call DMESS(MACT1, MTXTAL, IDAT, EVC)
      return
    end subroutine divadb
Call graph
divadb calls mess, messft, dmess
mess calls messfi, messgs, messmh, messpr, messfd
messft calls mess, messpr
dmess calls messfi
messfd calls messfi
drdivx calls divadb
drdivdb calls divadb