DIVA – diva
DIVA Subroutine
308 statements
Source File
public subroutine DIVA(TSPECS, Y, F, KORD, NEQ, DIVAF, DIVAO, IDIMT, IDIMY, IDIMF, IDIMK, IOPT)
Uses
divaev_module
diva_constants
divasc_module
divamc_module
Main routine.
Notes
++S Default KDIM = 16
++  Default KDIM = 20
++  Default MAXORD = 2, MAXSTF = 1
++  Default INTEGO, VAREQ, OUTPUT, DUMP, GSTOP, EXTRAP
++  Default STIFF=.F., ARGM=.F., ERRSTO=.F.
History
2015-03-15 DIVA Krogh Removed extra call divabu after noise test
2015-03-15 DIVA Krogh Forced restart needs more reduction in h.
2010-02-20 DIVA Krogh Fixed calling DIVAOP with array other than F
2009-11-03 DIVA Krogh Added option 11, more variables initialized.
2009-10-30 DIVA Krogh Gave KSSTRT and ROBND initial values.
2009-10-30 DIVA Krogh Fixed reference to undefined location in F.
2009-10-21 DIVA Krogh Got rid of NaN in diag. print when LSC=3.
2009-10-15 DIVA Krogh A few changes on how noise is handled.
2002-11-12 DIVA Krogh Fixed problem integrating to final output pt
2002-08-29 DIVA Krogh Added test for invalid HMIN/HMAX.
2002-07-26 DIVA Krogh Added KOUTKO to fully support Option 10.
2002-05-14 DIVA Krogh Fix starting prob. for Option 18.
2002-05-13 DIVA Krogh Put exponent letter in numbers missing them
2002-05-12 DIVA Krogh Added error message for bad option 5 usage.
2001-09-07 DIVA Krogh Changes to allow user tol on G-Stops.
2001-05-25 DIVA Krogh Minor change for making .f90 version.
2001-05-18 DIVA Krogh Less computing with no error test
2001-05-17 DIVA Krogh Fixed so with no error test can't start dump
2001-04-24 DIVA Krogh Inserted comments from ivacom.
2000-12-01 DIVA Krogh Removed (some of) unused C1, MAXSTF, METEXT.
1999-12-28 DIVA Krogh Saved S in DIVACR for output consistency.
1999-08-19 DIVA Krogh Removed superfluous test above label 3520.
1997-04-22 DIVA Krogh Got rid of assigned go to's. F=0 if diag.
1996-08-26 DIVA Krogh Initialize F to 0 if dumping solution.
1996-08-23 DIVA Krogh Print TN not TSPECS(1) in error messages.
1996-05-30 DIVA Krogh Changed DERIVS/OUTPUT to DIVAF/DIVAO.
1996-04-27 DIVA Krogh Changes to use .C. and C%%.
1996-03-30 DIVA Krogh Added external statement.
1996-03-25 DIVA Krogh Introduced TEXT1 to comply with F77.
1996-02-27 DIVA Krogh Fixed so DUMP not affected by ignored eqs.
1995-12-18 DIVA Krogh Fixed so no solution dump on 0 length integ.
1995-11-09 DIVA Krogh Fixed so char. data at col. 72 is not ' '.
1995-06-19 DIVA Krogh Fixed prob. with discon. just after restart.
1995-05-09 DIVA Krogh Fixed G-Stop/discontinuity code interaction
1995-04-26 DIVA Krogh Use KQMAXS instead of KQMAXI when LDIS>1000.
1995-04-26 DIVA Krogh Keep current KQL on discontinutiy.
1994-12-16 DIVA Krogh Fixed option 12 with K12 < 0.
1994-11-11 DIVA Krogh Declared all vars.
1994-11-02 DIVA Krogh Changes to use M77CON
1994-09-08 DIVA Krogh Added CHGTYP code.
1994-07-11 DIVA Krogh Fix to get same state with/without var. eqs.
1994-03-07 DIVA Krogh Allow larger order in single precision.
1994-01-14 DIVA Krogh Minor change to allow changing TFINAL.
1993-04-27 DIVA Krogh Additions for Conversion to C.
1993-04-12 DIVA Krogh Converted to use slightly altered MESS.
1993-04-12 DIVA Krogh Fixed LSC so sol. saved when HMAX is small.
1992-10-13 DIVA Krogh Fixed G-Stop/discontinuity code interaction.
1992-09-21 DIVA Krogh Fixed bug in discontinuity code.
1992-09-09 DIVA Krogh Fixed bug - Var. Eqs. with discontinuities.
1992-08-07 DIVA Krogh Storage map printed only if option 10 /= 0
1992-07-16 DIVA Krogh Restored correct discontinuity code.
1992-06-16 DIVA Krogh Eliminate reuse of storage for option 12.
1992-04-08 DIVA Krogh Removed unused labels, 1020, 2120.
1992-03-30 DIVA Krogh Fixed bug in DIVAOP error message.
1992-03-12 DIVA Krogh Simplified DIVABU, more digits in B's.
1992-01-16 DIVA Krogh Fixed minor bug in error messages.
1991-12-03 DIVA Krogh Major change for improved error checks.
1991-06-17 DIVA Krogh Fixed bug in checking storage allocation.
1991-04-11 DIVA Krogh Fixed minor bug re. option 12 in DIVAOP.
1991-03-28 DIVA Krogh Removed check at label 650 for KORD2I<0.
1991-02-08 DIVA Krogh Changed some floats to generics
1990-11-08 DIVA Krogh Fixed bug on TSPECS on discon.
1990-09-14 DIVA Krogh Fixed bug when discon. and sol. save.
1990-09-13 DIVA Krogh Increased dimension of BETA by 1.
1990-09-13 DIVA Krogh Added one more poss. on rel. error test.
1990-09-11 DIVA Krogh Recent change messed up getting dump output.
1990-06-05 DIVA Krogh Fixed bug in noise test, comments in IVACOM.
1990-05-08 DIVA Krogh Fixed new bug when TMARK hit in DIVAG.
1990-04-17 DIVA Krogh Fixed minor problem in DIVAIN error msg.
1990-04-10 DIVA Krogh Fixed interaction between discon. & dump.
1990-03-23 DIVA Krogh Fixed bug on option "-2", see 1989-12-07.
1990-03-20 DIVA Krogh Fixed rarely occuring loop.
1990-01-29 DIVA Krogh Removed unneeded labels.
1989-12-14 DIVA Krogh Saved common block DIVAEV.
1989-12-07 DIVA Krogh Added option "2" to DIVAOP.
1989-11-09 DIVA Krogh Made GG a save var. in DIVAHC
1989-08-21 DIVA Krogh Fix out of bounds ref. to V in DIVABU
1989-07-26 DIVA Krogh Fix bug in initial dim. check
1989-07-21 DIVA Krogh Code for integrating discontinuities
1987-12-07 DIVA Krogh Initial code.
Common variables and local variables
ALPHA (DIVAMC) Array with I-th entry = (current step size) / XI(I). Used in computing integration coefficients. B (DIVAHC) Array used to get started on computing integration coefficients. B(K) = 1. / (K(K+1)) BAKMIN (DIVADE) The largest delay at the initial point. BETA (DIVAMC) Array with I-th entry = product (K=1,I-1) of (current (XI(K)) / XI(K) from previous step), BETA(1)=1. Used in updating the difference tables. C (DIVAIN) Array used to hold integration/interpolation coeffs. C0 Parameter = 0. (in DIVAA,DE,CR,A,G,HC,IN,OP,PR) C1 Parameter = 1. (in DIVA,A,CR,DA,HC,IN,OP) C10 Parameter = 10. (in DIVAA,CR,OP) C1000 Parameter = 1000. (in DIVACR) C16 Parameter = 16. (in DIVAA,OP) C1M3 Parameter = .001 (in DIVAA) C1M5 Parameter = .00001 (in DIVAA) C1P125 Parameter = 1.125 (in DIVAA,HC,OP) C1P3 Parameter = 1.3 (in DIVAA) C1P4 Parameter = 1.4 (in DIVACR) C2 Parameter = 2. (in DIVAA,DE,BU,CR,IN,OP) C20 Parameter = 20. (in DIVACR) C2P5M3 Parameter = .0025 (in DIVAA) C4 Parameter = 4. (in DIVACR,OP) C40 Parameter = 40. (in DIVACR) C4096 Parameter = 4096. (in DIVAA) C6 Parameter = 6. (in DIVAA) C8M3 Parameter = .008 (in DIVAA) CM2 Parameter = -2. (in DIVACR) CM8 Parameter = -8. (in DIVACR) CMP5 Parameter = -.5 (in DIVACR) CMP75 Parameter = -.75 (in DIVAOP) CP0625 Parameter = .0625 (in DIVAA) CP1 Parameter = .1 (in DIVAA,CR,DA,HC) CP125 Parameter = .125 (in DIVACR) CP25 Parameter = .25 (in DIVAA,CR,DE,OP) CP3 Parameter = .3 (in DIVAA,OP) CP4 Parameter = .4 (in DIVAA) CP5 Parameter = .5 (in DIVAA,CR,DA,DE,HC,OP) CP5625 Parameter = .5625 (in DIVAHC) CP625 Parameter = .625 (in DIVAOP) CP75 Parameter = .75 (in DIVACR,OP) CP8 Parameter = .8 (in DIVACR) CP875 Parameter = .875 (in DIVAA, OP) CP9 Parameter = .9 (in DIVAOP) CP9375 Parameter = .9375 (in DIVACR) CQ3125 Parameter = .03125 (in DIVACR) CRBQI Parameter = .421875 (in DIVAHC) Initial val for computing RBQ. CSUM (DIVAIN) Array used to contain partial sums of the integration coefficients. This is used to corrrect for a difference table that has not yet been updated. D (DIVAMC) Array to be used later to store coefficients for integrating stiff equations. derivatives. Not used if option 13 is set. DISADJ (DIVAA) Value of stepsize when discontinuity is indicated. DNOISE (DIVAMC) Used in determining if noise is limiting the precision. It is usually |highest difference used in correcting| of the equation with the largest error estimate. DS (DIVAMC) Array to be used later to store coefficients for estimating errors when integrating stiff equations. DVC2 (DIVADB) Array used for output of variables HC to TOUT in common block DIVAMC. E (DIVACR) (Estimated error) / (Requested accuracy) EAVE (DIVAMC) This is a weighted average of past values of EIMAX. It is adjusted to account for expected changes due to step changes. EEPS10 (DIVAEV) = 10. * (machine epsilon). EEPS16 (DIVAEV) = 16. * (machine epsilon). EEPS2 (DIVAEV) = 2. * (machine epsilon). EEPT75 (DIVAEV) = (machine epsilon) * (.75) EI (DIVACR) Estimate for what E would be if step size increased. EIBND (DIVACR) Array containing limits on the estimated error with the stepsize increased. This array tends to make the code a little more conservative on step size increases at low order. EIMAX (DIVAMC) Estimate of (error estimate / error requested) if the step size should be increased. EIMIN (DIVAMC) An error estimate is small enough to allow a step increase if the estimate of ((error with the step size increased) / (error requested)) is less than EIMIN. EIMINO (DIVAA) Set to C8M3 and never changed. When step size is being reduced if EIMIN <= EIMINO then the reduction factor is set to CP875. This variable could be a parameter. EMAX (DIVAMC) Largest value computed for (error estimate) / (error requested). EOVEP2 (DIVAEV) = EEPS2 * (largest floating point number). EPS (DIVACR) Current absolute error tolerance. Also used for temporary storage when computing the desired value of EPS. ERCOEF (DIVACR) (Error coefficient from formula) / EPS EREP (DIVAMC) If EMAX > EREP, a step is repeated. Ordinarily this has the value .3. This is set < 0 if the error tolerance is specified improperly, and is set to a large value if the user requests complete control over the step size. EREP is also set < 0 after a user specified discontinuity. EROV10 (DIVAEV) = 10. / (largest floating point number). ETA (DIVAIN) Array used in computing integration/interp. coeffs. EVC (DIVADB) Array used for output of variables EEPS2 to EROV10 in common block DIVAEV. EXR (DIVAA) Set to CP1 and never changed. If it is estimated the the (error estimate) / (error requested) on the next step will be
= EXR then the step size is reduced. Could be a parameter. F (formal) Array used to store derivative values, the difference tables, error tolerance requests, and values used by some other options. (in DIVA,A,BU,CR,DA,DB,G,IN,PR) FDAT (DIVAMC) Used to store data for error messages. (Local array in DIVAIN.) FOPT (formal) in DIVAOP. Passed as place to save floating point data for options. This package passes F in for FOPT when calling DIVAOP. G (DIVAMC) Integration coefficients used for predicting solution. G(I, J) gives the I-th coefficient for integrating a J-th order differential equation. G(1, 1) is equal to the step size. GAMMA (DIVAIN) Array used in computing integration/interp. coeffs. GG (DIVAHC) Array of length = max. differential equation order allowed by code - 1. GG(K) = (HH(K+1)) / K! GNEW (formal) in DIVAG. Current value for vector function g, whose zeroes are to be found. GOINT (DIVACR) Used for assigned go to used in computing integration coefficients. GOLD (DIVAG) Previous value for element of G whose zero search is active. GS (DIVAMC) Integration coefficients used in estimating errors. GT (formal) in DIVAG. Previous value of GNEW. HC (DIVAMC) Ratio of (new step size) / (old step size) HDEC (DIVAMC) Default value to use for HC when reducing the step size. (Values closer to 1 may be used some of the time.) HH Equivalenced to G(1,1) = current step size in DIVAA,CR,DA,G,HC. HI (DIVAIN) Step length from the base value of the independent variable for the interpolation. HINC (DIVAMC) Default value to use for HC when increasing the step size. (Values closer to 1 may be used some of the time.) HINCC (DIVAMC) Actual value used for default value of HC when increasing the step size. Set to HINC after start is considered complete. During the start HINCC is set to 1.125. HMAX (DIVAMC) Largest value allowed for abs(step size). Default value is a very large number. HMAXP9 (DIVAMC) .9 * HMAX. HMIN (DIVAMC) Smallest value allowed for abs(step size). Default value is 0. HNEW (DIVADE) Value of step size when iterating at initial point for delay differential equations. I Used for temporary storage. (DIVAA,BU,CR,DA,DE,G,IN,OP,PR) IA (DIVAOP) absolute value of first integer stored for an option. ICF (DIVAMC) Final index for current loop in DIVACR. Required by option 18. ICI (DIVAIN) Temporary index, = 0 for interpolation, 1 or 0 for differentiation, and d-1, d-2, ... 0 for integration, where d is the order of the differential equation. Index of first location in C() used is ICI + an offset. ICS (DIVAMC) Starting index for current loop in DIVACR. ID (formal) Array use to contain integer data from common. Values are returned in locations 1 to 5 as follows. 1 KEMAX = Index of equation with largest error estimate 2 KSTEP = Current step number 3 NUMDT = Number of differences used for each equation 4 Reserved for future use 5 Reserved for future use IDAT (DIVAMC) Used to store integer for error messages. (Also used in DIVAA for temporary storage of KORD(2). (Local array in DIVAIN.) IDE (DIVADE - formal) Array used to contain past information so that delays can stretch back indefinitely. If the first location is 0, then any interpolations requested must be in the range of the current difference tables. At present, only the value 0 is allowed in IDE(1). This array is intended for the support of saving long past histories. IDE(2) must contain the declared dimension of WDE. IDEF (DIVADE -- formal) Flag giving indicaion of what is going on. = 0 User should compute derivatives and return to the main integrator. = 1 Code is computing additional values in order to get past data necessary for starting. User should compute derivatives and call DIVADE. < 0 Indicates an error condition. If DIVADE is called without changing the value of IDEF, the integration is stopped and an error message printed. Possible error flags are: -1 Difference tables do not span back far enough to compute the past values of Y needed. -2 There is not enough space in WDE to get the required starting values. IDIMF (formal) Declared dimension of F(). IDIMK (formal) Declared dimension of KORD(). IDIMT (formal) Declared dimension of TSPECS(). IDIMY (formal) Declared dimension of Y(). IDT (DIVAIN) Used as a base index into the difference table. IFLAG (formal in DIVAG) Used for communication with user. = 1 Continue as if DIVAG was not called. = 2 Check KORD(1) as one would do at start of OUTPUT if no G-Stops were present. (Exit if in DERIVS.) = 3 Return to the integrator. = 4 Compute G and return to DIVAG. = 5 A G-Stop has been found, and NSTOP gives its index. (If NSTOP < 0, the stop was an extrapolating stop.) = 6 Same as 5, but requested accuracy was not met. = 7 Same as 5, but there is a probable error in computing G. = 8 Fatal error of some type. (An error message has been printed.) IG (DIVAG) IG = KORD(2) on the initial entry (0 for extrapolating G-Stops, and 1 for interpolating). IGFLG (DIVAMC) Used primarily in DIVAg, but also used in DIVA to keep track of the state of GSTOP calculations. = -2 Extrapolatory G's initialized, but not the interpolatory. = -1 Interpolatory G's initialized, but not the extrapolatory. = 0 Set when integration is started or restarted, or option setting GSTOP is set. = 1 Iterating to find a GSTOP. = 2 User told that a GSTOP was found. = 3 Checking G's at point where a GSTOP was located. = 4 Checking G's at a T output point. = 5 Usual case, no sign change detected. IGSTOP (DIVAMC) IGSTOP(k) is set in DIVAg to the index of the last G with a 0, where k is one for an interpolatory G-Stop, and k is two for an extrapolatory G-Stop. IGTYPE (DIVAMC) Array with two elements as for IGSTOP, but this saves a flag giving the nature of convergence to the stop. = 0 All known G-stops completely processed. = 4 Need to compute next value while iterating. = 5 Got good convergence. = 6 Got convergence, but not to desired accuracy. = 7 Problem in getting convergence. = 8 A fatal error of some type. IHI (DIVA) Last location used by the current option. ILGREP (DIVAMC) Used when correction to keep track of equations that are to use a certain error tolerance. ILGROR (DIVACR) Index of last equation in the current group of equations grouped for selecting integration order. ILOW (DIVA) First location used by the current option. INCOM (DIVADE) Array equivalenced to LDT in the common block DIVASC. Used to simplify saving information in the common block. INCOP (DIVAOP) Array containing data giving the amount of space in IOPT used for each of the options. INGS Current index for G-stop being examined in DIVAG. INICAS (DIVADE) Used to track the initialization for a delay equation. = 1 Very beginning. = 2 Getting derivative at the very beginning. = 3 Getting derivatives at points prior to the initial point. = 4 Getting derivative at initial point after iteration is started. INTCHK (DIVA) Array passed to OPTCHK containing information on storage allocation. See comments in OPTCHK for details. INTEG (DIVAIN) Number of integrations being done. (<0 for differentiations and =0 for interpolation.) Also used as counter when computing integration coefficients. (DIVAPR) Number of integrations being done. INTEGS (DIVAPR) = -1 for equations that are not stiff, 0 for those that are stiff. INTEGZ (DIVAIN) min(INTEG, 0) INTERP (DIVAIN) added to the usual integration order to get the order to be used when interpolating: 3-KQMAXI, if HI=0; 1, if |HI| > |XI(1)| and HI * XI(1) < 0; 0, otherwise -- the usual case. IOP10 (DIVAMC) Number of times diagnostic output is to be given when leaving DIVAcr (the corrector). IOP11 (DIVAMC) Gives current step number of the method. Tells how many of certain coefficients must be computed. (Has nothing to do with options.) = min(max integ order + 1, KDIM). Also set when starting to flag that certain memory locations must be set to 0. IOP12 (DIVAMC) Points to location in F() where user supplied values of HINC, HDEC, HMIN, and HMAX. (0 if option 12 not used.) IOP13 (DIVAMC) If not zero, reverse communication will be used for getting the values of derivatives. Associated with option 13. IOP14 (DIVAMC) If not zero, reverse communication will be used in place of calls to the output routine. Associated with option 14. IOP15 (DIVAMC) If not zero, a return will be made to the user after the initialization. Associated with option 15. This might be used to overlay DIVA, some of the user's code, and perhaps DIVAop. IOP16 (DIVAMC) Points to location in KORD() where information for specifying the error tolerance is specified. See option 16. IOP17 (DIVAMC) Used in initialization for option 17, afterwards this cell is used by KEXIT which is equivalenced to IOP17. IOP18 (DIVAMC) Points to location in KORD() where information for specifying a grouping of equations for derivative evaluation is stored. See option 18. IOP19 (DIVAMC) Points to location in KORD() where information for specifying a grouping of equations for integration order control is stored. See option 19. IOP20 (DIVAMC) Used for option 20, gives first location in F where estimated errors are to be stored. Expected to be useful in a program for solving boundary value problems using multiple shooting. IOP21 (DIVAMC) Was used for stiff equations option (never completely coded). The optional code still uses this (don't activate it!). Now used to flag the location if F where the user has stored the tolerance to use in finding G-Stops. IOP21S (DIVAMC) Was used for stiff equations see above. IOP22 (DIVAMC) Set aside for possible option for stiff equations. IOP3 (DIVAMC) Value set by option 3. = 0 Interpolate to final point. (The default) = 1 Integrate to final point. = -1 Extrapolate to final point. IOP4 (DIVAMC) Value set by option 4. The output routine is called with KORD(1) = 4, every IOP4 steps. (Default value for IOP4 is a very large number. IOP5 (DIVAMC) Value provided by option 5, used to specify extra output points. IOP6 (DIVAMC) Value provided by option 6. If nonzero, the output routine is called at the end of every step. If > 0, there are IOP6 interpolating G-Stops. IOP7 (DIVAMC) Value provided by option 7. If > 0, there are K7 extrapolating G-Stops. IOP8 (DIVAMC) Value provided by option 8. If nonzero, the output routine is called with KORD(1)=8 whenever the step size is changed. IOP9 (DIVAMC) Value provided by option 9. Used to specify that the user wishes to save the solution. IOPIVA (DIVA) Used to save length of IOPT vector for error messages. IOPST (DIVASC) Intended for possible use in stiff equations. IOPT (formal DIVA and IVAOP) Used to specify options. IOPTC (DIVAOP) In DIVAOP equivalenced so that IOPTC(3) is equivalent to IOP3. IOPTS (DIVAOP) Array containing the current default values to be stored into IOPTC. IORD (DIVACR) Index of first equation in the current group of equations grouped for selecting integration order. IOUTKO (DIVADC) Used in DIVADI to point to KORD to keep track of equation grouping for diagnostic output. ISVCOM (DIVADE) Used to save info. in the common block DIVASC. ITERS (DIVADE) Counts iterations in starting delay differential equations. Max. value for this is arbitrarily 100. ITOLEP (DIVAMC) Used for temporary storage, and for the index of a tolerance relative to the start of tolerances. IVC1 (DIVADB) Array used for output of variables IOPST to NUMDT in common block DIVASC. IVC2 (DIVADB) Array used for output of variables ICF to NY in common block DIVAMC. IWB (DIVADE) Current base index for saving F values in WDE when starting delay differential equations. IY (DIVAMC) Used for the current index to the Y() array. (Local variable in DIVAIN used in computing IYI.) Equivalenced to IZFLAG in DIVAG. IYI (DIVAIN) Y(IYI) is currently being computed. IYN (DIVAIN) Y(IYN) is base Y() corresponding to Y(IYI). IYNI (DIVAIN) Used as base index for computing IYN as IY is for INI. IYO (DIVADE) Points to first base value of Y for current interpolation when getting values for a delay differential equation. IZFLAG (DIVAG) Equivalenced to IY. Set to 0 initially, and later set to the value returned by ZERO. = 0 Value set on entry at start of search. = 1 Compute next g again. = 2 Normal terminiation. = 3 Normal termination -- error criterion not satisfied. = 4 Apparent discontinuity -- no zero found. = 5 Couldn't find a sign change. = 6 ZERO was called with a bad value in IZFLAG. J For temporary storage. (In DIVA,A,BU,CR,DA,DB,DE,HC,IN,OP,PR) J1 (DIVAA & DA) Used for temporary storage. J2 (DIVAA) Used for temporary storage. JL (DIVA) Used for checking storage. JLGREP (DIVACR) Contents of first location of KORD (called LGROUP in DIVACR) for the current error tolerance rule. JLGROR (DIVACR) Contents of first location of KORD for the current integration order control. JLIM (DIVA) Used for checking second item in KORD list for options 16 and 19. K For temporary storage. (In DIVA,A,BU,CR,DA,DB,DE,HC,IN,OP,PR) KDIM Parameter giving the largest number of differences supported. Used in all the routines. KEMAX (DIVAMC) Index associated with equation giving the largest value for (estimated error) / (requested error). KEXIT (DIVAMC) Equivalenced to IOP17 which is not used after initialization. Defines actions when KORD2I = -7. (Referenced in (DIVAA,DA,G).) = 1 Take the step over with reduced H. = 2 Take the step over. = 3 Do the end of step call to OUTPUT. = 4 Reset TMARK, then do same as for KEXIT = 2. = 5 Reset TMARK, then do same as for KEXIT = 3. = 6 Give the fatal error diagnostic. KFERR (DIVA) Temporary storage in checking for option 16. KGO (DIVA) Used to tell from whence a check is being done or an error message is being written. = 1 Checking an equation group for variational equations. = 2 Checking an equation group for diagnostic print. = 3 Checking an equation group for integration order control. = 4 Checking an equation group for error control. = 5 Checking an equation group for specifying ODE orders. = 6 Found a problem with output type for printing. = 7 Found a problem with an output group for printing. = 8 Found a problem with input NEQ. = 9 Order specified for the ODE's in the system is out of range. =10 Option 16 was not used (an error). =11 Error tolerance of 0 specified without proper flags. KIS (DIVAMC) Used to check if it is time to dump the solution. The check involves incrementing KIS at the end of the step, and dumping the solution if KIS is 0. = -1 Set in DIVAcr when it is time to dump solution = 0 When starting = 2 After being dumped. This is set to 1000 just after a user specified discontinuity, and counted up from that point. KMARK (DIVAMC) Identifies the type of output associated with the next output point specified by TSPECS. KONV (DIVADE) Counts iterations. Test for convergence if KONV > 1. KORD (formal in DIVA,A,BU,CR,DA,DB,DE,G,IN,PR) KORD(1) is used to return flags for the user to test, and KORD(2) tells what routine the flag is associated with. See KORD1I and KORD2I below and the write up for the program. KORD(3) is used for communicating extra information to the user in some cases. KORD(4) to KORD(NTE+3) are used for integration order for the equations, and the rest of KORD() is available for user options. KORD1I (DIVAMC) Helps in defining the state of the integrator. Frequently has the same value as KORD(1). Meaning depends on the value of KORD(2), or the value about to be assigned to KORD(2). < 0 Happens when preparing to give output with extrapolation. = 0 Happens when checking F at points for noise test. = 1 (KORD(2)=-1) End of integration has been reached. = 1 (KORD(2)= 0) Computing first predicted derivative. = 1 (KORD(2)= 1) Output for initial point. = 2 (KORD(2)=-1) Giving diagnostic for noise limiting precision. = 2 (KORD(2)= 0) Computing corrected derivative. = 2 (KORD(2)= 1) Output for TSPECS(3). = 3 (KORD(2)=-1) Diagnostic for step size reduction too fast. = 3 (KORD(2)= 0) Computing variational derivative. = 3 (KORD(2)= 1) Output for TSPECS(4). = 4 (KORD(2)=-1) Error, discontinuity. = 4 (KORD(2)= 1) Output for certain number of steps. = 5 (KORD(2)= 0) Get initial derivatives for stiff equations. = 5 (KORD(2)= 1) Extra output from TSPECS. = 6 (KORD(2)= 1) End of step output. = 7 (KORD(2)= 0) Evaluate G before extrapolated output point. = 7 (KORD(2)= 1) Evaluate G before extrapolated output point. (Also used when checking for other G's after finding one.) = 8 (KORD(2)= 1) Tell user step size has changed. = 9 (KORD(2)= 1) Request for user to save solution. = 11 (KORD(2)=-1) Error, step size too small at end of start. = 12 (KORD(2)=-1) Error, step size is too small. = 13 (KORD(2)=-1) Error, output points specified badly. = 21 (KORD(2)=-1) H too small to give reasonable change when added to T. = 22 (KORD(2)=-1) Error, bad tolerance. = 23 (KORD(2)=-1) Set after message for a fatal error. = 24 Set on error message in DIVA, along with KORD2I = -4. Also used as an index into MLOC in DIVAA when an error is being processsed, see MLOC below. KORD2I (DIVAMC) Helps in defining the state of the integrator. Frequently has the same value as KORD(2). = -3 Set in DIVAg, to get a derivative evaluation. = -2 Set in DIVAg, to get another entry to OUTPUT. = -1 Return to calling program, done, interrupt, or got an error. = 1 Calling OUTPUT or returning to user for OUTPUT type action. = 0 Calling DERIVS or returning to user for DERIVS type action. = -4 Error message in DIVA and in DIVAop, along with KORD1I = 24. = -5 Starting = -6 Starting, getting the initial derivative value or derivatives for the noise test. = -7 Done some extrapolation, KEXIT defines the action to take. Set in DIVAg to activate KEXIT action in DIVA. = -8 Set when user has requested adjustment of the difference tables for a discontinutiy. KORDI (DIVASC) Order of differential equation being integrated. If all orders are the same, this set once at the beginning. KOUNT (DIVADE) Count of number of points back from the initial point when solving a delay differential equation. KOUNTM (DIVADE) Largest value currrently allowed for KOUNT. KOUNTX (DIVADE) Largest value allowed for KOUNTM. KOUTKO Used in DIVACR to track where output is wanted. KPRED (DIVAMC) Value assigned to KORD1I when getting a predicted derivative. (1 used now, 5 planned for use with stiff equations.) KQD (DIVACR) = max(2, integration order) KQDCON (DIVAMC) Number of coefficients computed with constant step size for stiff equations. KQICON (DIVAMC) Number of coefficients computed with constant step size for nonstiff equations. KQL (DIVACR) Integration order at start of (DIVACR) KQLORD (DIVACR) Saved value of KQL when equations are grouped for controlling the integration order. KQMAXD (DIVASC) Maximum integration order used for stiff equations. KQMAXI (DIVASC) Maximum integration order used for nonstiff equations. KQMAXS (DIVAMC) Maximum integration order for equations that have some limit on the error that can be committed. KQMXDS (DIVAMC) Used to save KQMAXD in case step is repeated and the solution must be dumped. KQMXI (DIVAIN) Maximum integration order used for integration or interpolation, = KQMAXI+INTERP-1. KQMXS (DIVAIN) Maximum step number, = max(KQMXI, KQMAXD). KQMXIL (DIVAMC) Value of KQMAXI the last time integration coefficients were computed. KQMXIP (DIVAMC) = KQMAXI + MAXINT, for computing integration coeffs. KQMXIS (DIVAMC) Used to save KQMAXI in case step is repeated and the solution must be dumped. KQN (DIVACR) Value of integration order at end of DIVACR. KQQ Used for the integration order for current equation. (Values < 0 are intended for stiff equations.) (In DIVA,BU,DA,IN,PR) KSC (DIVAMC) Number of steps that have been taken with a constant step size. KSOUT (DIVAMC) When KSTEP reaches this value, the output routine is called with KORD(1) = 4. The default value is a very large number. KSSTRT (DIVAMC) Set when ending one derivative per step to KSTEP + 2. Checked later in DIVAHC to decide whether to set the step changing factors to their nominal values. KSTEP (DIVAMC) Number of steps taken since the start of integration. L Used for temporary storage. In DIVAIN, L is the initial value of LDT, except L=1 if LDT=-1, and MAXINT >= 0. (Used in DIVAA,BU CR,DA,DB,IN,PR.) LAHAG (DIVADB) Used to get proper offset into an diagnostic message. LAIAG (DIVADB) Used to get proper offset into an diagnostic message. LDIS (DIVAA) Count of steps since user flagged a discontinuity. LDT (DIVASC) Used to keep track of state of difference table. = -5 Used only on first step to indicate that an extra iteration is desired to get a firm estimate on the error. = -4 Set on initialization before there is any difference table. = -3 Set just after predicting, interpolation is not allowed when this value is set. = -2 Set when difference table is to be updated to the end of the current step, but no interpolation is to be done. (For dumping the solution.) = 0 Calculations for current step are complete, it is not o.k. to update the difference table. = 1 Difference table has been updated to the end of the current step, e.g. by doing an interpolation. = 2 Set when doing a special interpolation during computation of derivatives. (For delay equations.) LEX (DIVAMC) Indicates how to get values at next output point: = -1 Extrapolate = 0 Interpolate (The usual case.) = 1 Integrate to the output point, integration is not continued. LGO (DIVAIN) Used as an an assigned go to. Result is to add in extra correction term when LDT has been set to 2. LGROUP (formal) This is a part of KORD passed into DIVACR. The first location is the start of the information on the grouping of equations for error control. LINC (DIVAMC) Used to indicate state of step size selection. = -10 After computed derivatives at base time, after computing other extra derivatives for the noise test. = -9 After computed second extra derivative for noise test. = -8 After computed first extra derivative for noise test. = -7 Dumping the solution and then doing a user initiated restart, or getting ready to compute extra derivatives for the noise test. = -6 Dumping the solution before a restart. = -5 Set on the first step, and also set when dumping the solution after a discontinuity. = -4 Repeat step with no change in the step size. = -3 Set when the error tolerance is set improperly. = -2 User has complete control of selecting the step size. = -1 Step is being repeated. = 0 Step size is not to be increased on this step. = k>0 Step size can be increased by HINCCk. LINCD (DIVAMC) Value of smallest k for which HINCCk >= 2. (=-2 if user is specifying all step size changes.) LINCQ (DIVAMC) Value of smallest k for which HINCCk >= 4. LIOPT (DIVAOP) Value of the last index in IOPT on the last call. Used so DIVA can print IOPT in error messages. LL (DIVACR) Temporary variable used when equations are grouped for integration order control. LNOTM1 (DIVAIN) Logical variable = L /= -1. If LNOTM1 is true, storage in Y() is different in some way lost to antiquity. Such a case can only arise in the case of stiff equations. LOCF1 (DIVADB) Gives packed data needed for output of tables by the message processor MESS. See comments there under METABL for defs. LOCF2 (DIVADB) As for LOCF1 above. LOCM (DIVAA) Parameter = 32256, used to unpack integers stored in MLOC for use in error message processing. LPRINT (formal, DIVADB) Defines how much printing is to be done in DIVADB. Let |LPRINT| = 10N1 + N2 (N1,N2 digits) N1=1 Do not print any variables external to the integrator. N1=2 Print tspecs, current y, past y, current f, all pertinent contents of KORD, and TOL. N1=3 Above + difference tables up to highest difference used. N1=4 Same as N1=1 + all in storage allocated for differences. N2=1 Do not print any variables internal to the integrator. N2=2 Print all scalar variables in interpolation common block. N2=3 Above + all scalar variables in main integ. common block. N2=4 Same as N1=3 + all used in arrays XI,BETA,ALPHA, first column of G, GS,RBQ,SIGMA N2=5 Same as N1=4 + all used in arrays G,D,DS,V LSC (DIVAMC) Indicates if starting or if noise may be present. =k<0 -k steps have been taken for which noise appears to be limiting the precision. = 0 Usual case = 1 Doing 1 derivative per step after initial part of start. = 2 Used as flag that it is time to set LSC=0. = 3 Third step, hold the order constant. = 4 Second step, increase orders from 2 to 3. = 5 First step, third time through the first step (if required). = 6 First step, second time through. = 7 First step, first time through. = 8 Set on initialization. LTXT?? Names of this form are used in setting up data statements for error messages. These names are generated automatically by PMESS, the program that makes up these messages. LX (DIVAA) Used for temporary storage in computing TMARKA(). (formal DIVADE) An integer array containing extra information, as follows. LX(1) Points to a location in Y beyond those already in use. Values of Y requested are computed at TSPECS(1) - Y(LX(1)) and stored starting at Y(LX(1)+1). If this index is 0, no more extra Y values are to be computed. LX(2) Index of the first equation for which the Y's above are to be computed. Y(LX(1)+1) will correspond to this first equation index. LX(3) Index of the last equation for which the Y's above are to be computed. Thus the Y's stored starting at Y(LX(1)+1) will require no more space than half the space ordinarily required for the array Y(), and may require significantly less. LX(4) Maximum number of times to integrate F to get Y. This should be > 0, and less than or equal to the order of the highest order differential equation. (= 0 is allowed, but probably not what you want. It would give a value only for F.) Space must be set aside for all integrals of F, even if not all are requested. For a first order system, all Y's are just the first integrals of the corresponding F's. For higher order equations, the first Y associated with a given F is the d-th integral of the corresponding F, where d is the order of the equation, and the last Y corresponding to the F is the first integral of that F. LX(5) As for LX(4), but gives the index for the fewest number of times to integrate F. Ordinarily this should be > 0. If 0 is requested, an estimate for the value of F at the delay point is computed. This should not be 0 more than once, for equations covering the same index, since later such requests would write over the earlier results. LX(5i+k) , k = 1, 2, ... 5. Treated as for the cases above. If i different cases of delayed Y's are to be computed, then LX(5i+1) must be 0. LX2 (DIVADE) Value of LX(5i+2), when working on the i-th delay. MACT Used in the programs which call the error message program. This array difines the actions to be taken by that program. (In (DIVA,A,DA,DE,G,IN,OP) MACT0 (DIVADB) Used to call the message program, see MACT. MACT? As for MACT, in (DIVA,CR,DB) MACTFV (DIVADB) As for MACT0. MAXDIF (DIVASC) Maximum differentiations required for stiff equations. MAXINT (DIVASC) Maximum integrations required. (= max. order of differential equations if equations are not stiff.) MAXKQ (DIVA, BU)e MAXKQD (DIVAMC) Largest integration order allowed for stiff equations. MAXKQI (DIVAMC) Largest integ. order allowed for nonstiff equations. ME???? Parameters defining constants used for interaction with the error message program MESS. See comments there for definitions. (In DIVA,A,DA,DE,G,IN,OP) METHOD (DIVAMC) Defines kind of methods being used. = -1 Only stiff equations are being integrated. = 0 Only nonstiff equations are being integrated. = 1 Both kinds of methods are required. MLOC (DIVA,A,DE) Contains locations in MTEXT for error messages. In DIVAA this data is packed using MLOC??, see below. MLOC?? (DIVAA) Parameters constructed to aid in making up packed data for processing error messages. Low two digits give the value of KORD1I to use for the error index and later processing, the next two give the error severity level, and the rest point to text used for the message. MODF2 (DIVADB) Used in constructing the same kind of packed data as described for LOCF1 above. MULTJ Local to DIVAOP for calls not using F. MTEXT (DIVA,A,CR,IN,OP) Text for error messages. MTXT?? (DIVA,A,CR,DA,DB,DE,G,IN,OP) Equivalenced into MTEXT. N Used for temporary storage. (In DIVAHC,IN,PR) NDTF (DIVASC) Location in F() where difference table starts. NE (DIVAMC) Number of equations in the first group. (=NTE if option 18 is not used.) NEDDIG (DIVADB) Parameter = -MEDDIG. NEPTOL (DIVAMC) Used for temporary storage and to save the value of ITOLEP for error messages. NEQ (formal) Total number of equations being integrated. NG (DIVAMC) Used in DIVAg for the number of g's in the current context. NGSTOP (DIVAG) Dimension 2 array equivalenced to IOP6, and IOP7. To get the number of interpolating and extrapolating G-Stops. NGTOT (DIVAMC) NGTOT(1) gives the number of interpolating G-Stops, and NGTOT(2) gives the number of extrapolating G-Stops. NKDKO (DIVASC) If this is nonzero (option 17), it gives the location in KORD() where a vector defining the order of each equation is specified. NLX (DIVADE) Temporary index used to keep track of interpolations being done to get Y() values for a delay differential equation. NOISEQ (DIVAMC) max(2, order of equation for which (error estimate)/ (error requested) is a maximum). NOUTKO (DIVAMC) If nonzero, gives the index in KORD where information on what equations are to be included in the diagnostic output is given. See option 10. NSTOP (formal) In DIVAG. Index of the G-stop, see IFLAG. NTE (DIVASC) Total number of equations being integrated = NEQ. NTEXT (formao DIVADB) Character variable containing heading text. NTOLF (DIVAMC) First location in F() where tolerance specifying accuracy desired is stored. NUMDT (DIVASC) Maximum allowed number of differences available for doing an integration. NXTCHK (DIVA) Equivalenced to INTCHK(1), which gives the next available location in INTCHK for storing data on storage allocation. NY (DIVAMC) Total order of the system. NYNY (DIVASC) Location in Y() where the base value for Y() is saved. NYNYO (DIVADE) Equivalenced to the saved value from common of NYNY. OUTPUT (formal) Name of subroutine to be called for the output of data or for computing G-Stops. Not used if option 14 is set. OVD10 (DIVAEV) (largest floating point number) / 10. OVTM75 (DIVAEV) (largest floating point number) * (-.75) RBQ (DIVAMC) Array containing data for the preliminary noise test. RD (formal DIVACO) Array use to contain floating point data from common. Values are returned in locations 1 to 3 as follows. 1 EMAX = Max. ratio of estimated error to requested error 2 Reserved for future use 3 Reserved for future use REF (DIVACR) Array of length 3 used for translating error tolerance type into the factor used for exponential averaging for that type. RND (DIVACR) Usually the current estimated error. Used in deciding if noise is limiting precision. RNOISE (DIVACR) Value used in comparison with RBQ() for preliminary noise test. ROBND (DIVAMC) Used to influence the selection of integration order. The larger ROBND, the harder it is to increase the order and the easier it is to decrease it. RVC2 (DIVADB) Array used for output of variables DNOISE to SNOISE in common block DIVAMC. These are variables that don't require a great deal of precision. S (DIVACR) Estimate of (step size) * eigenvalue of Jacobian. SIGMA (DIVAMC) The k-th entry of this array contains a factor that gives the amount the k-th difference is expected to increase if the step size in increased. These numbers get bigger it there is a past history of increasing the step size. SIGMAS (DIVAA) Saved value of SIGMA(k) from the last step, where k = integration order for equation with index KEMAX. SNOISE (DIVAMC) Value used in comparison with RBQ() on equation with largest value for (error estimate) / (error requested). T (formal) in DIVAIN. T(1) contains the point to be interpolated to, and T(2) is used in a check that |HI| <= |T(2)|. When used by other routines in this package, TSPECS is passed in for T. TB (DIVADE) Base time for current interpolation. TC (DIVADE) Original value of TN when getting past Y's for a delay differential equation. TEMP Used for temporary storage, in DIVAHC,PR TEMPA (DIVACR) Array equivalenced to (TPS1,TPS2,TPS3,TPS4). TEMPAO (DIVACR) Array used to accumulate values in TEMPA. TG (DIVAMC) TG(1) gives the last value of TSPECS(1) for which an interpolatory G-Stop has been computed. TG(2) is defined similarly for extrapolatory G-Stops. TGSTOP (DIVAMC) TGSTOP(1) gives the value of TSPECS(1) where the last 0 for an interpolatory G-Stop was found. TGSTOP(2) is defined similarly for extrapolatory G-Stops. TMARK (DIVAMC) Location of the next output point. TMARKA (DIVAA) Array of length 2 equivalenced to TMARK (and TMARKX). TMARKX (DIVAMC) Location of the next output point to be found using integration or extrapolation. This variable must follow immediately after TMARK in the common block. TN (DIVASC) The value of TSPECS(1) at the conclusion of the last step. TNEQ (DIVADB) Array of dimension 1 equivalenced to TN so that an array can be passed to MESS. TOL (formal) This is a part of F passed into DIVACR. The first location is the start of the information on the tolerances for error control. TOLD (DIVAG) Value of TSPECS(1) on one side of a zero. TOLG (DIVAMC) Tolerance to pass to dzero when locating G-Stops. TOUT (DIVAMC) Location of next output point defined by value of TSPECS(3). Such output is given with KORD(1) = 2. TP (DIVA,A,DA,DE,HC) Used for temporary storage. TP1 (DIVAA,DA,HC,IN,PR) Used for temporary storage. TP2 (DIVAA,DA,HC,PR) Used for temporary storage. TP3 (DIVAA) Used for temporary storage. TPD (DIVABU) Used for temporary storage. TPP (DIVACR) Used for temporary storage. Usually same as TPS3. TPS1 (DIVAA,CR) Used for temporary storage. (In DIVACR is the difference of order KQQ-2) TPS2 (DIVAA,CR) Used for temporary storage. (In DIVACR is the difference of order KQQ-1) TPS3 (DIVACR) Contains the difference of order KQQ. This is the last difference used in the corrector. TPS4 (DIVACR) Contains the difference of order KQQ+1. TPS5 (DIVACR) Temporary storage. TPS6 (DIVACR) Temporary storage. TPS7 (DIVACR) Temporary storage. TSAVE (DIVAG) Value of TSPECS(1) before starting the search for a 0. TSPECS (formal DIVA,A,DB,DE,G) TSPECS(1) is the current value of the independent variable. TSPECS(2) is the current value of the step size. TSPECS(3) is the increment to use between output points that give output with KORD(1) = 2. TSPECS(4) is the "final" output point. V (DIVAMC) Array used in computing integration coefficients. XI (DIVASC) XI(K) = TSPECS(1) - value of TSPECS(1) K steps previous. W (DIVAHC) Array used in computing integration coefficients. WDE (formal, DIVADE) Array used for working storage. This storage is used to save derivative values when iterating to get started. To be safe one should allow as much space as is allowed for differences in F. In most cases the start will not require this much space however. This array is also intended for the support of saving long past histories. Y (formal, DIVA,A,CR,DA,DB,DE,G,IN,PR) Array containing the independent variable and all derivatives up to order one less than the order of the differential equation. Also use to save these values at the beginning of the current step, the base values. YN (formal, in DIVAPR) Base values of y, these follow the current values of the dependent variable, y, in Y().
Arguments
Type Intent Optional Attributes Name
double precision :: TSPECS(*)
double precision :: Y(*)
double precision :: F(*)
integer :: KORD(*)
integer :: NEQ
real :: DIVAF
real :: DIVAO
integer :: IDIMT
integer :: IDIMY
integer :: IDIMF
integer :: IDIMK
integer :: IOPT(*)
Calls
Contents
Source Code
DIVA
Source Code
    subroutine DIVA(TSPECS, Y, F, KORD, NEQ, DIVAF, DIVAO, IDIMT,     &
                    IDIMY, IDIMF, IDIMK, IOPT)
      use divaev_module
      use diva_constants
      use divasc_module
      use divamc_module
      integer NEQ, IDIMT, IDIMY, IDIMF, IDIMK
      integer KORD(*), IOPT(*)
      double precision TSPECS(*), Y(*)
      double precision F(*)
      external DIVAF, DIVAO
      integer KGO, INTCHK(0:30), NXTCHK
      integer IHI, JL, J, ILOW, K, KQQ, JLIM, KFERR
!
      equivalence (INTCHK(1), NXTCHK)
      double precision, parameter :: CM1 = -1.D0
      integer IOPIVA(2)
      save IOPIVA
!
!                      Declarations for error message processing.
!
      character TEXT1(1)*10
      integer, parameter :: MENTXT = 23
      integer, parameter :: MEIDAT = 24
      integer, parameter :: MEMDA1 = 27
      integer, parameter :: MECONT = 50
      integer, parameter :: MERET  = 51
      integer, parameter :: MEEMES = 52
      integer, parameter :: METEXT = 53
      integer, parameter :: MEIVEC = 57
!
      integer MACT(16), MLOC(12), MACT1(4)
!
! ********* Error message text ***************
![Last 2 letters of Param. name]  [Text generating message.]
!AA DIVA$B
!AB The interval [1, 10**6], bounds the allowed values for NTE=$I.$E
!AC For option $I, the interval [$I, $I], bounds the allowed $C
!   values for the integration order which is set to $I.$E
!AD Option 16 must be used for error control.$E
!AE F($I) = $F, but it must be -1.0 when skipping the error check.$E
!AF For option $I, the interval [$I, $I] bounds the allowed $C
!   values for KORD($I)=$I, which is used to specify an $B
!AG output type for printing.$E
!AH output group for printing.$E
!AI equation group for variational equations.$E
!AJ order for a differential equation.$E
!AK equation group for diagnostic print.$E
!AL equation group for integration order control.$E
!AM equation group for error control.$E
!AN Option 5 argument must be <= 0 or > 4.$E
!   $
!AO KORD values for this option starting at KORD($M) are:$E
     integer, parameter :: LTXTAA =   1
     integer, parameter :: LTXTAB =   7
     integer, parameter :: LTXTAC =  71
     integer, parameter :: LTXTAD = 183
     integer, parameter :: LTXTAE = 226
     integer, parameter :: LTXTAF = 290
     integer, parameter :: LTXTAG = 400
     integer, parameter :: LTXTAH = 427
     integer, parameter :: LTXTAI = 455
     integer, parameter :: LTXTAJ = 498
     integer, parameter :: LTXTAK = 535
     integer, parameter :: LTXTAL = 573
     integer, parameter :: LTXTAM = 620
     integer, parameter :: LTXTAN = 655
     integer, parameter :: LTXTAO =   1
      character MTXTAA(3) * (233)
      character MTXTAB(1) * (55)
      data MTXTAA/'DIVA$BThe interval [1, 10**6], bounds the allowed val&
     &ues for NTE=$I.$EFor option $I, the interval [$I, $I], bounds the$&
     & allowed values for the integration order which is set to $I.$EOpt&
     &ion 16 must be used for error control.$EF($I) = ','$F, but it must&
     & be -1.0 when skipping the error check.$EFor option $I, the interv&
     &al [$I, $I] bounds the allowed values for KORD($I)=$I, which is us&
     &ed to specify an $Boutput type for printing.$Eoutput group for pri&
     &nting.$Eequation gro','up for variational equations.$Eorder for a$&
     & differential equation.$Eequation group for diagnostic print.$Eequ&
     &ation group for integration order control.$Eequation group for err&
     &or control.$EOption 5 argument must be <= 0 or > 4.$E'/
      data MTXTAB/'KORD values for this option starting at KORD($M) are:&
     &$E'/
! End of automatically generated error message code.
!
!        for KGO =     1      2      3      4      5      6      7
      data MLOC / LTXTAI,LTXTAK,LTXTAL,LTXTAM,LTXTAJ,LTXTAG,LTXTAH,     &
     &            LTXTAB,LTXTAC,LTXTAD,LTXTAE, LTXTAN /
!           KGO        8      9     10     11      12
!
!                      1  2  3 4       5  6       7       8       9 10
      data MACT / MEEMES,38,24,0, MENTXT, 0, METEXT, MECONT, MEMDA1,0,  &
     &  METEXT, MEIDAT,0, MEIVEC,0, MECONT /
!           11      12 13     14 15     16
      data MACT1 / METEXT, MEIVEC, 0, MERET /
      data IOPIVA(1) / 1111 /
      data TEXT1 / 'IOPT()= $B' /
!
! ************** START OF EXECUTABLE CODE ******************
!
!     **** TEST IF CONTINUING AN INTEGRATION
      if (KORD(1) /= 0) go to 330
!     **** INITIALIZE VARIOUS SCALARS
      KSTEP = 0
      KQMXIS = 0
      KORD2I = -5
      KORD(2) = -1
      NTE = NEQ
      NE = NTE
      TOLG = 0.D0
!     **** SET UP OPTIONS
      if (IOPT(1) /= 0) call DIVAOP(IOPT, F)
      call DIVAOP(IOPIVA, F)
      if (IOPT(1) == 0) IOPIVA(2) = 1
!
      if ((NE <= 0) .or. (NE > 1000000)) then
         IDAT(1) = NE
         KGO = 8
         go to 650
      end if
!                         Set up diagnostic print on storage allocation.
      INTCHK(0) = 245
      if (IOP10 /= 0) INTCHK(0) = 247
!
!     **** CHECK TSPECS STORAGE ALLOCATION
      INTCHK(2) = IDIMT
      INTCHK(3) = 4
      NXTCHK = 4
      if (IOP5 /= 0) then
         INTCHK(4) = 5
         INTCHK(5) = 5
         if (IOP5 > 0) then
            INTCHK(6) = IOP5 - 4
            if (IOP5 < 5) then
               KGO = 12
               go to 600
            end if
         else
            IHI = -IOP5
            JL = 4
            do 15 IHI = IHI, IDIMK-3, 3
               J = abs(KORD(IHI))
               if (J == 0) go to 20
               if (abs(KORD(IHI + 2)) > 1) then
                  IDAT(2) = -1
                  IDAT(3) = 1
                  KGO = 6
                  go to 600
               end if
               if ((J <= JL) .or. (J > KORD(IHI+1))) then
                  KGO = 7
                  IDAT(2) = JL + 1
                  IDAT(3) = KORD(IHI+1)
                  go to 610
               end if
               JL = KORD(IHI+1)
   15       continue
            if (KORD(IHI) /= 0) IHI = IHI + 3
   20       INTCHK(6) = JL - 4
         end if
         NXTCHK = 7
      end if
   25 call OPTCHK(INTCHK, IOPT, 'DIVA / TSPECS$E')
      if (NXTCHK < 0) KORD2I = -4
!
!     **** CHECK KORD STORAGE ALLOCATION
      INTCHK(2) = IDIMK
      INTCHK(3) = NE + 3
      NXTCHK = 4
      if (IOP5 < 0) then
         INTCHK(4) = 5
         INTCHK(5) = -IOP5
         INTCHK(6) = IHI + IOP5
         NXTCHK = 7
      end if
!
!++  Code for VAREQ is active
      if (IOP18 /= 0) then
         NE = abs(KORD(IOP18))
         INTCHK(NXTCHK) = 18
         ILOW = IOP18
         KGO = 1
!.       **** CHECK OPTION FOR VALID INPUT
         go to 430
      end if
!++  End
   30 continue
      if (NKDKO /= 0) then
!                        **** STORAGE ALLOCATED FOR ODE ORDERS
         INTCHK(NXTCHK) = 17
         INTCHK(NXTCHK+1) = NKDKO
         INTCHK(NXTCHK+2) = NTE
         NXTCHK = NXTCHK + 3
      end if
!++  Code for STIFF is inactive
!      IF (IOPST /= 0) then
!         INTCHK(NXTCHK) = 17
!         INTCHK(NXTCHK+1) = IOPST
!         INTCHK(NXTCHK+2) = NTE
!         NXTCHK = NXTCHK + 3
!      end if
!++  End
!
! **** SET INITIAL INTEGRATION ORDERS, TEST ODE ORDERS ****
!
      MAXINT = 0
      MAXDIF = 0
      NY = 0
      do 80 K = 1, NTE
         if (NKDKO /= 0) KORDI = KORD(NKDKO + K - 1)
         NY = NY + abs(KORDI)
!++  Code for STIFF is inactive
!      IF (IOPST == 0) GO TO 60
!c.    **** CHECK FOR POTENTIAL STIFF EQUATION
!      JS = abs(KORD(IOPST+K-1)) - 1
!      IF (JS) 52,60,54
!c.    **** EQUATION IS NOT ACTIVE
!   52 KQQ = 0
!      GO TO 56
!c.    **** EQUATION USES IMPLICIT METHOD
!   54 KQQ = -1
!      IF (JS > abs(KORDI)) then
!        Set up an error message.
!      end if
!      MAXINT = max(MAXINT, abs(KORDI) - JS)
!   56 IF (KORDI >= 0) GO TO 70
!      KORDI = -1 - KORDI
!      JS = JS - 1
!      MAXDIF = max(MAXDIF, JS, 1)
!      GO TO 70
!++  End
!     **** EQUATION IS TO USE AN EXPLICIT METHOD
   60    KQQ = 1
         MAXINT = max(MAXINT, KORDI)
   70    if ((KORDI > MAXORD) .or. (KORDI <= 0)) then
!                    Set up error message.  KORDI is out of range.
            IDAT(1) = 17
            IDAT(2) = 1
            IDAT(3) = MAXORD
            if (NKDKO /= 0) then
               KGO = 5
               ILOW = NKDKO
               IHI = NKDKO + K - 1
               go to 640
            else
               KGO = 9
               IDAT(4) = KORDI
               go to 650
            end if
         end if
         KORD(K + 3) = KQQ
   80 continue
!     **** SET FLAGS WHICH DEPEND ON METHOD USED
!++  Code for STIFF is inactive
!      METHOD = 1
!      IF (MAXINT > 0) IF (MAXDIF) 85,90,85
!      METHOD = -1
!   85 CONTINUE
!      KPRED = 5
!      GO TO 100
!++  End
   90 METHOD = 0
      KPRED = 1
  100 continue
!
! ******* CHECK KORD FOR DIAGNOSTIC OUTPUT CONTROL *********
!
!++  Code for OUTPUT is active
      if (IOP10 > 0) then
         if (NOUTKO /= 0) then
            INTCHK(NXTCHK) = 10
            ILOW = NOUTKO
!.    **** Check option for valid input
            KGO = 2
            go to 430
         end if
      end if
!++  End
  110 continue
!
! ********** CHECK KORD FOR INTEGRATION ORDER CONTROL ******
!
!++  Code for INTEGO is active
      if (IOP19 /= 0) then
!.           **** Check option for valid input
         INTCHK(NXTCHK) = 19
         ILOW = IOP19
         JLIM = -30
         KGO = 3
         go to 430
      end if
!++  End
  120 continue
!
! ********** CHECK SET UP FOR ERROR TOLERANCES *************
!
      INTCHK(NXTCHK) = 16
      ILOW = IOP16
      JLIM = -5
      KGO = 4
      if (IOP16 /= 0) go to 430
!.                      **** IN CURRENT CODE, IOP16=0 IS AN ERROR
      KGO = 10
      go to 650
  150 continue
!     **** CHECK KORD STORAGE ALLOCATION
      call OPTCHK(INTCHK, IOPT, 'DIVA / KORD$E')
      if (NXTCHK < 0) KORD2I = -4
!
!     ******** DONE CHECKING KORD STORAGE ALLOCATION *******
!
!     **** CHECK  Y  STORAGE ALLOCATION
      INTCHK(2) = IDIMY
      INTCHK(3) = NY + NY
      NXTCHK = 4
      NYNY = NY + 1
      call OPTCHK(INTCHK, IOPT, 'DIVA / Y$E')
      if (NXTCHK < 0) KORD2I = -4
!
!     **** CHECK  F  STORAGE ALLOCATION
      INTCHK(2) = IDIMF
      INTCHK(3) = NTE
      NXTCHK = 4
      if (IOP16 /= 0) then
!                                Error tolerance info.
         INTCHK(4) = 16
         INTCHK(5) = NTOLF
         INTCHK(6) = IHI - IOP16 + 1
         NXTCHK = 7
      end if
      if (IOP12 > 0) then
         INTCHK(NXTCHK) = 12
         INTCHK(NXTCHK+1) = IOP12
         INTCHK(NXTCHK+2) = 4
         NXTCHK = NXTCHK + 3
      end if
      if (IOP21 > 0) then
         INTCHK(NXTCHK) = 21
         INTCHK(NXTCHK+1) = IOP21
         INTCHK(NXTCHK+2) = 1
         NXTCHK = NXTCHK + 3
      end if
!
!++  Code for ERRSTO is inactive
!      IF (IOP20 /= 0) then
!c.                                Space for saving error estimates
!         INTCHK(NXTCHK) = 20
!         INTCHK(NXTCHK) = IOP20
!         INTCHK(NXTCHK) = NTE
!         NXTCHK = NXTCHK + 3
!      end if
!++  Code for STIFF is inactive
!      if (IOP21 > 0) then
!c.                               Info. for stiff equations
!         INTCHK(NXTCHK) = 21
!         INTCHK(NXTCHK+1) = IOP21
!         INTCHK(NXTCHK+2) = IOP21S
!         NXTCHK = NXTCHK + 3
!      end if
!      MAXKQD = min(MAXKQI, 6)
!++  End
!                          Set aside space for the difference tables.
      INTCHK(NXTCHK) = 0
      INTCHK(NXTCHK+1) = -KDIM * NTE
      INTCHK(NXTCHK+2) = 0
      NXTCHK = NXTCHK + 3
      INTCHK(NXTCHK) = -5 * NTE
      call OPTCHK(INTCHK, IOPT, 'DIVA / F$E')
      if (NXTCHK < 0) then
         KORD2I = -4
      else if (KORD2I /= -4) then
         do 290 K = NXTCHK+1, INTCHK(NXTCHK)
            if (INTCHK(INTCHK(K)) == 0) then
               NDTF = INTCHK(INTCHK(K)+1)
               NUMDT = min(KDIM, (INTCHK(INTCHK(K)+2)-NDTF+1) / NTE)
               MAXKQI = NUMDT - 1
            else
!         Take a quick return if needed space was not specified by user.
               KORD2I = -4
            end if
  290    continue
      end if
      if (IOP9 + abs(IOP10) + IOP11 /= 0) then
! Insure user doesn't get in trouble with F not iniitalized.
         do 300 K = NDTF, NDTF + NTE*NUMDT - 1
            F(K) = 0.D0
  300    continue
      end if
  320 continue
      if ((KORD2I == -4) .or. (IOP10 /= 0)) then
         MACT1(3) = IOPIVA(2)
         call MESS(MACT1, TEXT1, IOPT)
         KORD1I = 24
         KORD(1) = 24
      end if
      TMARK = TSPECS(1)
      TMARKX = TSPECS(4) + TSPECS(2)
!
!     **** DONE WITH INITIALIZATION AND CHECKING INPUTS
      if (IOP13 + IOP14 + IOP15 /= 0) return
  330 call DIVAA(TSPECS, Y, F, KORD, DIVAF, DIVAO)
      return
!
! ************ LOOP TO CHECK OPTION SPECIFICATIONS *********
!
  430 JL = 0
      do 560 IHI = ILOW, IDIMK
         J = KORD(IHI)
         go to (460, 480, 490, 490), KGO
!     **** CHECK ON VARIATIONAL EQUATIONS
  460    continue
!++  Code for VAREQ is active
         if (J - NTE) 470, 565, 620
  470    if (J == 0) go to 560
         if (J <= JL) go to 620
!++  End
!     **** Check on diagnostic output option
  480    continue
!++  Code for OUTPUT is active
!.    **** CHECK IF DONE
         if (J >= NTE) go to 565
         if (J <= JL) go to 620
         go to 550
!++  End
  490    continue
!     **** Check integration order control (KGO=3) and
!     **** error tolerance equation grouping (KGO=4).
         if (J - NTE) 500, 565, 620
  500    if (J) 510, 530, 540
  510    if ((JL <= 0) .and. (IHI /= ILOW)) go to 620
         if (J < JLIM) then
!                         Output an error message.
            IDAT(2) = JLIM
            IDAT(3) = 0
            go to 630
         end if
  520    JL = -JL
         go to 560
  530    if (KGO == 3) go to 520
         KFERR = NTOLF + IHI - ILOW
         if (F(KFERR) == CM1) go to 510
!                         Set up error message, TOL must be -1.
            IDAT(1) = KFERR
            KGO = 11
            go to 650
  540    if (abs(JL) >= abs(J)) go to 620
  550    JL = J
  560    continue
  565 NXTCHK = NXTCHK + 3
      INTCHK(NXTCHK-2) = ILOW
      INTCHK(NXTCHK-1) = IHI - ILOW + 1
      go to (30, 110, 120, 150), KGO
!
!     **** AN ERROR HAS BEEN MADE
!                  Error in setting up TSPECS for extra output
  600 IHI = IHI + 2
  610 ILOW = -IOP5
      go to 630
!                  Error in KORD indices
  620 IDAT(2) = abs(JL) + 1
      IDAT(3) = NTE
!                  Set up for print of message about KORD
  630 IDAT(1) = INTCHK(NXTCHK)
  640 IDAT(4) = IHI
      IDAT(5) = KORD(IHI)
!
! ***************** Process Errors *************************************
!
  650 KORD2I = -4
      MACT(4) = LTXTAF
      if (KGO >= 8) MACT(4) = -1
      MACT(6) = MLOC(KGO)
      CALL DMESS(MACT, MTXTAA, IDAT, FDAT)
      if (KGO < 8) then
         MACT(10) = ILOW
         MACT(13) = ILOW
         MACT(15) = -min(IHI+2, IDIMK)
         CALL MESS(MACT(9), MTXTAB, KORD)
         if (KGO <= 4) go to 565
      end if
!              5   6   7    8    9   10   11  12
      go to (100, 25, 25, 320, 100, 150, 660, 25), KGO - 4
  660 KGO = 4
      go to 565
    end subroutine diva
Call graph
diva calls divaop, optchk, mess, dmess
divaop calls mess
mess calls messgs, messpr, messfi, messfd, messmh
dmess calls messfi
messfd calls messfi