DIVABU – diva
DIVABU Subroutine
62 statements
Source File
subroutine DIVABU(F, KORD)
Arguments
Type Intent Optional Attributes Name
double precision :: F(*)
integer :: KORD(*)
1987-12-07 DIVABU Krogh Initial code.
THIS SUBROUTINE RESTORES THE DIFFERENCE TABLE TO ITS STATE AT THE BEGINNING OF THE CURRENT STEP. IF THE INTEGRATION ORDER WAS INCREASED, IT IS REDUCED. THE COMMON ARRAY XI IS ALSO RESTORED TO ITS STATE AT THE BEGINNING OF THE STEP. IF THE STEPSIZE IS NOT BEING CHANGED, THE ARRAY V USED TO COMPUTE INTEGRATION COEFFICIENTS IS RESTORED.
Called by
Contents
Common Blocks
DIVASC DIVAMC
Common Blocks
common /DIVASC/
Type Attributes Name Initial
real :: TN
real :: XI
integer :: IOPST
integer :: KORDI
integer :: KQMAXD
integer :: KQMAXI
integer :: LDT
integer :: MAXDIF
integer :: MAXINT
integer :: NKDKO
integer :: NTE
integer :: NYNY
integer :: NDTF
integer :: NUMDT
common /DIVAMC/
Type Attributes Name Initial
real :: TG
real :: TGSTOP
real :: TMARK
real :: TMARKX
real :: TOUT
real :: TOLG
real :: HC
real :: HDEC
real :: HINC
real :: HINCC
real :: HMAX
real :: HMAXP9
real :: HMIN
real :: ALPHA
real :: BETA
real :: D
real :: G
real :: V
real :: DS
real :: GS
real :: SIGMA
real :: RBQ
real :: DNOISE
real :: EAVE
real :: EIMAX
real :: EIMIN
real :: EMAX
real :: EREP
real :: ROBND
real :: SNOISE
real :: FDAT
integer :: ICF
integer :: ICS
integer :: IGFLG
integer :: IGTYPE
integer :: IGSTOP
integer :: ILGREP
integer :: INGS
integer :: IOP3
integer :: IOP4
integer :: IOP5
integer :: IOP6
integer :: IOP7
integer :: IOP8
integer :: IOP9
integer :: IOP10
integer :: IOP11
integer :: IOP12
integer :: IOP13
integer :: IOP14
integer :: IOP15
integer :: IOP16
integer :: IOP17
integer :: IOP18
integer :: IOP19
integer :: IOP20
integer :: IOP21
integer :: IOP22
integer :: IOP21S
integer :: ITOLEP
integer :: IY
integer :: KEMAX
integer :: KIS
integer :: KMARK
integer :: KORD1I
integer :: KORD2I
integer :: KPRED
integer :: KQDCON
integer :: KQICON
integer :: KQMAXS
integer :: KQMXDS
integer :: KQMXIL
integer :: KQMXIP
integer :: KQMXIS
integer :: KSC
integer :: KSOUT
integer :: KSSTRT
integer :: KSTEP
integer :: LEX
integer :: LINC
integer :: LINCD
integer :: LINCQ
integer :: LSC
integer :: MAXKQD
integer :: MAXKQI
integer :: METHOD
integer :: NE
integer :: NEPTOL
integer :: NG
integer :: NGTOT
integer :: NOISEQ
integer :: NOUTKO
integer :: NTOLF
integer :: NY
integer :: IDAT
Call graph
divaa calls divabu
divag calls divabu
divao calls divag