DIVAO – diva
DIVAO Subroutine
19 statements
Source File
subroutine DIVAO(TSPECS, Y, F, KORD)
Arguments
Type Intent Optional Attributes Name
double precision :: TSPECS(4)
double precision :: Y(*)
double precision :: F(*)
integer :: KORD(*)
Calls
Contents
Source Code
DIVAO
Source Code
      subroutine DIVAO(TSPECS, Y, F, KORD)
c
c Sample output subroutine for use with DIVA.
c This subroutine gives output for a simple two body problem.
c
      integer          KORD(*), IFLAG, NSTOP
      double precision TSPECS(4), Y(*), F(*), G6(1), GT6(1)
      save             G6, GT6
c
 1000 format (12X,
     1   'RESULTS FOR A SIMPLE 2-BODY PROBLEM'//
     2   5X, 'T/IFLAG', 10X, 'U/V', 11X, 'UP/VP', 9X, 'UPP/VPP')
 1001 format (1P,SP,4E15.6 / 8X,I3, 4X, 3E15.6/' ')
c
c Do the output
c
      IFLAG = 0
      if (KORD(1) .EQ. 1) then
        write (*, 1000)
      end if
      if (KORD(1) .EQ. 6) then
  100     G6(1) = Y(3)
          call DIVAG(TSPECS, Y, F, KORD, IFLAG, NSTOP, G6, GT6)
          if ((IFLAG .EQ. 1) .OR. (IFLAG .EQ. 3)) return
          if (IFLAG .EQ. 4) go to 100
      end if
      write (*,1001) TSPECS(1),Y(1),Y(2),F(1),IFLAG,Y(3),Y(4),F(2)
      return
      end subroutine DIVAO
Call graph
divao calls divag
divag calls divabu, dmess
dmess calls d1mach, messfi