DIVAA – diva
DIVAA Subroutine
636 statements
Source File
public subroutine DIVAA(TSPECS, Y, F, KORD, DIVAF, DIVAO)
Main subroutine for variable order integration of ordinary differential equations
History
1989-02-24 DIVAA Krogh Big error with BETA(2)=1+epsilon -- looped
1988-07-27 DIVAA Krogh Fixed to allow restart on a restart.
1988-03-07 DIVAA Krogh Initial code.
Arguments
Type Intent Optional Attributes Name
double precision :: TSPECS(*)
double precision :: Y(*)
double precision :: F(*)
integer :: KORD(*)
real :: DIVAF
real :: DIVAO
Calls
Contents
Common Blocks
DIVAEV DIVASC DIVAMC
Source Code
DIVAA
Common Blocks
common /DIVAEV/
Type Attributes Name Initial
real :: EEPS2
real :: EEPT75
real :: EOVEP2
real :: OVTM75
real :: OVD10
real :: EEPS10
real :: EEPS16
real :: EROV10
common /DIVASC/
Type Attributes Name Initial
real :: TN
real :: XI
integer :: IOPST
integer :: KORDI
integer :: KQMAXD
integer :: KQMAXI
integer :: LDT
integer :: MAXDIF
integer :: MAXINT
integer :: NKDKO
integer :: NTE
integer :: NYNY
integer :: NDTF
integer :: NUMDT
common /DIVAMC/
Type Attributes Name Initial
real :: TG
real :: TGSTOP
real :: TMARK
real :: TMARKX
real :: TOUT
real :: TOLG
real :: HC
real :: HDEC
real :: HINC
real :: HINCC
real :: HMAX
real :: HMAXP9
real :: HMIN
real :: ALPHA
real :: BETA
real :: D
real :: G
real :: V
real :: DS
real :: GS
real :: SIGMA
real :: RBQ
real :: DNOISE
real :: EAVE
real :: EIMAX
real :: EIMIN
real :: EMAX
real :: EREP
real :: ROBND
real :: SNOISE
real :: FDAT
integer :: ICF
integer :: ICS
integer :: IGFLG
integer :: IGTYPE
integer :: IGSTOP
integer :: ILGREP
integer :: INGS
integer :: IOP3
integer :: IOP4
integer :: IOP5
integer :: IOP6
integer :: IOP7
integer :: IOP8
integer :: IOP9
integer :: IOP10
integer :: IOP11
integer :: IOP12
integer :: IOP13
integer :: IOP14
integer :: IOP15
integer :: IOP16
integer :: IOP17
integer :: IOP18
integer :: IOP19
integer :: IOP20
integer :: IOP21
integer :: IOP22
integer :: IOP21S
integer :: ITOLEP
integer :: IY
integer :: KEMAX
integer :: KIS
integer :: KMARK
integer :: KORD1I
integer :: KORD2I
integer :: KPRED
integer :: KQDCON
integer :: KQICON
integer :: KQMAXS
integer :: KQMXDS
integer :: KQMXIL
integer :: KQMXIP
integer :: KQMXIS
integer :: KSC
integer :: KSOUT
integer :: KSSTRT
integer :: KSTEP
integer :: LEX
integer :: LINC
integer :: LINCD
integer :: LINCQ
integer :: LSC
integer :: MAXKQD
integer :: MAXKQI
integer :: METHOD
integer :: NE
integer :: NEPTOL
integer :: NG
integer :: NGTOT
integer :: NOISEQ
integer :: NOUTKO
integer :: NTOLF
integer :: NY
integer :: IDAT
Source Code
    subroutine DIVAA(TSPECS, Y, F, KORD, DIVAF, DIVAO)
      integer KORD(*)
!--D Next line special: P=>D, X=>Q
      double precision TSPECS(*), Y(*)
      double precision F(*)
      external DIVAF, DIVAO
!
      integer KDIM, MAXORD, MAXSTF
!++ Substitute for KDIM, MAXORD, MAXSTF below
      parameter (KDIM = 20, MAXORD = 2, MAXSTF = 1)
!--D Next line special: P=>D, X=>Q
      double precision TN
      double precision XI(KDIM)
!
!--D Next line special: P=>D, X=>Q
      double precision TG(2), TGSTOP(2), TMARK, TMARKX, TOUT, TOLG
      double precision ALPHA(KDIM), BETA(KDIM+1)
      double precision  D(MAXSTF+MAXORD,MAXORD), G(KDIM,MAXORD)
      double precision V(KDIM+MAXORD)
      double precision HC, HDEC, HINC, HINCC, HMAX, HMAXP9, HMIN
      double precision FDAT(11)
!
      double precision DS(MAXSTF+MAXORD, MAXORD), GS(KDIM)
      double precision SIGMA(KDIM), RBQ(KDIM), DNOISE
      double precision EAVE, EIMAX, EIMIN, EMAX, EREP, ROBND, SNOISE
!
!.    SPECIFICATION OF ENVIRONMENTAL CONSTANTS.
      double precision EEPS10, EEPS16, EROV10, EEPS2
      double precision EEPT75, EOVEP2, OVTM75, OVD10
      common / DIVAEV / EEPS2, EEPT75, EOVEP2, OVTM75, OVD10, EEPS10,   &
     &   EEPS16, EROV10
      save / DIVAEV /
      integer IOPST, KORDI, KQMAXD, KQMAXI, LDT, MAXDIF, MAXINT, NKDKO, &
     &   NTE, NYNY, NDTF, NUMDT
      common / DIVASC / TN, XI, IOPST, KORDI, KQMAXD, KQMAXI, LDT,      &
     &   MAXDIF, MAXINT, NKDKO, NTE, NYNY, NDTF, NUMDT
!
      integer ICF,ICS,IGFLG,IGTYPE(2),IGSTOP(2),ILGREP,INGS,IOP3,IOP4,  &
     &   IOP5,IOP6,IOP7,IOP8,IOP9,IOP10,IOP11,IOP12,IOP13,IOP14,IOP15,  &
     &   IOP16,IOP17,IOP18,IOP19,IOP20,IOP21,IOP22,IOP21S,ITOLEP,IY,    &
     &   KEMAX,KIS,KMARK,KORD1I,KORD2I,KPRED,KQDCON,KQICON,KQMAXS,      &
     &   KQMXDS,KQMXIL,KQMXIP,KQMXIS,KSC,KSOUT,KSSTRT,KSTEP,LEX,LINC,   &
     &   LINCD,LINCQ,LSC,MAXKQD,MAXKQI,METHOD,NE,NEPTOL,NG,NGTOT,       &
     &   NOISEQ,NOUTKO,NTOLF,NY,IDAT(6)
      common /DIVAMC/ TG,TGSTOP,TMARK,TMARKX,TOUT,TOLG,HC,HDEC,HINC,    &
     &   HINCC,HMAX,HMAXP9,HMIN,ALPHA,BETA,D,G,V,DS,GS,SIGMA,RBQ,DNOISE,&
     &   EAVE,EIMAX,EIMIN,EMAX,EREP,ROBND,SNOISE,FDAT,ICF,ICS,IGFLG,    &
     &   IGTYPE,IGSTOP,ILGREP,INGS,IOP3,IOP4,IOP5,IOP6,IOP7,IOP8,IOP9,  &
     &   IOP10,IOP11,IOP12,IOP13,IOP14,IOP15,IOP16,IOP17,IOP18,IOP19,   &
     &   IOP20,IOP21,IOP22,IOP21S,ITOLEP,IY,KEMAX,KIS,KMARK,KORD1I,     &
     &   KORD2I,KPRED,KQDCON,KQICON,KQMAXS,KQMXDS,KQMXIL,KQMXIP,KQMXIS, &
     &   KSC,KSOUT,KSSTRT,KSTEP,LEX,LINC,LINCD,LINCQ,LSC,MAXKQD,MAXKQI, &
     &   METHOD,NE,NEPTOL,NG,NGTOT,NOISEQ,NOUTKO,NTOLF,NY,IDAT
      save / DIVAMC / , / DIVASC /
!
      double precision CMP75, C0, C1M5, C1M3, C2P5M3, C8M3, CP0625, CP1
      double precision CP25, CP3, CP4, CP5, CP875, C1, C1P125, C1P3, C2
      double precision C6, C10, C16, C4096
      parameter (CMP75 = -.75D0)
      parameter (C0 = 0.D0)
      parameter (C1M5 = 1.D-5)
      parameter (C1M3 = 1.D-3)
      parameter (C2P5M3 = 2.5D-3)
      parameter (C8M3 = 8.D-3)
      parameter (CP0625 = .0625D0)
      parameter (CP1 = .1D0)
      parameter (CP25 = .25D0)
      parameter (CP3 = .3D0)
      parameter (CP4 = .4D0)
      parameter (CP5 = .5D0)
      parameter (CP875 = .875D0)
      parameter (C1 = 1.D0)
      parameter (C1P125 = 1.125D0)
      parameter (C1P3 = 1.3D0)
      parameter (C2 = 2.D0)
      parameter (C6 = 6.D0)
      parameter (C10 = 10.D0)
      parameter (C16 = 16.D0)
      parameter (C4096 = 4096.D0)
!
      integer LDIS, KEXIT, I, J, K, J1, J2, L, LX
      double precision TP, TP1, TP2, TP3, HH, DISADJ
      double precision SIGMAS, TPS1, TPS2, EIMINO, EXR
!--D Next line special: P=>D, X=>Q
      double precision  TMARKA(2), XP, XP1
      equivalence (G(1, 1), HH), (TMARKA(1), TMARK)
      equivalence (KEXIT, IOP17)
      save EIMINO, EXR, SIGMAS, TP, TP1, TP2, TP3, TPS1, TPS2, DISADJ,  &
     &   LDIS
!
!                      Declarations for error message processing.
!
      integer MACT(17), MLOC(8), MENTXT, MERET, MEEMES, METEXT
      parameter (MENTXT =23)
      parameter (MERET  =51)
      parameter (MEEMES =52)
      parameter (METEXT =53)
!
! ********* Error message text ***************
![Last 2 letters of Param. name]  [Text generating message.]
!AA DIVAA$B
!AB At: TN=$F, KSTEP=$I, with H=$F$E
!AC A previously reported error was fatal.$E
!AD Print points not properly ordered: TSPEC($I)=$F$E
!AE An error tolerance of 0 requires setting special flags.  $B
!AF Step size reduced too fast, doing a restart.  $B
!AG H is so small that TN + H = TN.  $B
!AH Error tolerance too small.  $B
!AI Step size at end of start < HMIN=$F, $B
!AJ Error estimates require a stepsize < HMIN=$F, $B
!AK (Estimated Error) / (Requested Error) for equation $I is $F.  $B
!AL Tolerance $I is F($I) = $F.$B
!AM Tolerance $I is F($I) * F($I) = $F * $F = $F.$B
!AN   Replacing F($I) with $F.$E
      integer LTXTAA,LTXTAB,LTXTAC,LTXTAD,LTXTAE,LTXTAF,LTXTAG,LTXTAH,  &
     & LTXTAI,LTXTAJ,LTXTAK,LTXTAL,LTXTAM,LTXTAN
      parameter (LTXTAA=  1,LTXTAB=  8,LTXTAC= 40,LTXTAD= 80,LTXTAE=129,&
     & LTXTAF=189,LTXTAG=237,LTXTAH=272,LTXTAI=302,LTXTAJ=342,          &
     & LTXTAK=390,LTXTAL=455,LTXTAM=484,LTXTAN=531)
      character MTXTAA(3) * (186)
!
      integer LOCM, MLOCAC, MLOCAD, MLOCAE, MLOCAF, MLOCAG, MLOCAH,     &
     &   MLOCAI, MLOCAJ
      parameter (LOCM = 32 * 256)
!                     KORD1I   Severity   Loc. message
      parameter (MLOCAC = 23 + 32 * (99 + 256 * LTXTAC))
      parameter (MLOCAD = 13 + 32 * (38 + 256 * LTXTAD))
      parameter (MLOCAE = 22 + 32 * (38 + 256 * LTXTAE))
      parameter (MLOCAF =  3 + 32 * (14 + 256 * LTXTAF))
      parameter (MLOCAG = 21 + 32 * (38 + 256 * LTXTAG))
      parameter (MLOCAH =  2 + 32 * (25 + 256 * LTXTAH))
      parameter (MLOCAI = 11 + 32 * (38 + 256 * LTXTAI))
      parameter (MLOCAJ = 12 + 32 * (38 + 256 * LTXTAJ))
!
      data MTXTAA/'DIVAA$BAt: TN=$F, KSTEP=$I, with H=$F$EA previously r&
     &eported error was fatal.$EPrint points not properly ordered: TSPEC&
     &($I)=$F$EAn error tolerance of 0 requires setting special flags. $&
     & ','$BStep size reduced too fast, doing a restart.  $BH is so smal&
     &l that TN + H = TN.  $BError tolerance too small.  $BStep size at$&
     & end of start < HMIN=$F, $BError estimates require a steps','ize <&
     & HMIN=$F, $B(Estimated Error) / (Requested Error) for equation $I$&
     & is $F.  $BTolerance $I is F($I) = $F.$BTolerance $I is F($I) * F(&
     &$I) = $F * $F = $F.$B  Replacing F($I) with $F.$E'/
      data MLOC / MLOCAC, MLOCAD, MLOCAE, MLOCAF, MLOCAG, MLOCAH,       &
     &   MLOCAI, MLOCAJ /
!
!                      1 2 3 4       5 6       7       8 9      10
      data MACT / MEEMES,0,0,0, MENTXT,0, METEXT, MENTXT,0, METEXT,     &
     &  MENTXT, 0, METEXT, MENTXT, LTXTAN, METEXT, MERET /
!           11 12      13      14      15      16     17
!
      data EXR, EIMINO / CP1, C8M3 /
      data LDIS / 0 /
!
! ************** START OF EXECUTABLE CODE ******************************
!
  660 if (KORD2I) 670, 1380, 1840
  670 if (KORD2I == -1) go to 2140
      if (KORD2I == -5) go to 720
      if (KORD2I+8) 1840, 710, 1840
!     **** SPECIAL OUTPUT CASE (EXTRAPOLATION OR GSTOP)
  680 go to (1220, 1190, 830, 690, 690, 2190), KEXIT
!     **** RESET TMARK BEFORE GOING WHERE DIRECTED BY KEXIT
  690 KEXIT = KEXIT - 2
      go to 1890
!     **** USER HAS REQUESTED A RESTART
  700 KORD2I = -5
      IGFLG = 0
      if ((KORD(2) >= 2) .and. (LSC < 3)) KORD2I = -8
      if ((KORD1I <= 3) .or. (KORD1I == 5)) go to 1890
      if (KORD2I == -5) go to 720
!                Set up for a discontinuity
  710 XP = TSPECS(1)
      if (KORD(2) == 3) then
!                Adjust for discontinuity in Y
         J = 0
         do 712 I = 1, NTE
            if (NKDKO /= 0) KORDI = KORD(NKDKO + I -1)
            K = 1
            J = J + KORDI
            XP1 = Y(J)
  711       Y(NYNY + J - K) = Y(NYNY + J - K) + XP1
            if (K < KORDI) then
               XP1 = Y(J-K) + (TN - XP) * XP1 / dble(K)
               K = K + 1
               go to 711
            end if
  712    continue
      else
         IGFLG = -3
      end if
      DISADJ = HH
      XP1 = (XP - TN) / XI(1)
      if (XP1 < CP25) then
         K = 1
         if (XP1 < CMP75) K = 2
         TSPECS(1) = TN - XI(K)
         TSPECS(2) = 2.D0*(TN - TSPECS(1))
         call DIVAIN(TSPECS(1), Y, F, KORD)
         do 713 J = 1, NY
            Y(NYNY + J - 1) = Y(J)
  713    continue
!          Move difference tables back one step
         TN = TSPECS(1)
  714    call DIVABU(F, KORD)
         if (K == 2) then
            KSC = max(KSC - 1, 1)
            do 715 K = max(1, KSC), IOP11-1
               BETA(K+1) = BETA(K) * (XI(K) / (XI(K+1) - XI(1)))
  715       continue
            K = 0
            go to 714
         end if
      end if
!      Take step to discontinuity.
      HH = (XP - TN)
      EREP = -abs(EREP)
      KIS = 1000
      LDIS = 1
      LSC = 0
      LINC = 0
      HINCC = C1P125
      KSSTRT = KSTEP + 2
      go to 1115
! ********
! INITIALIZE FOR STARTING AN INTEGRATION
! ********
  720 HH = TSPECS(2)
      LSC = 8
      LINC = -5
      LINCD = 64
      LDT = -4
      KQMAXI = 0
      EIMIN = CP3
      EAVE = C10
      XI(1) = C0
      IGFLG = 0
      KIS = 0
      KSSTRT = 0
      ROBND = 0.D0
! GO COMPUTE INITIAL DERIVATIVES
  730 KORD2I = -6
!++  Code for VAREQ is active
      ICS = 0
      ICF = NE
!++  End
  740 KORD1I = KPRED
      go to 1360
!   RETURN AFTER COMPUTING INITIAL (OR NOISE TEST) DERIVATIVES
  750 continue
!++  Code for VAREQ is active
      if (IOP18 == 0) go to 790
!.    **** SPECIAL LOGIC TO COMPUTE VARIATIONAL DERIVATIVES
  760 if (KORD1I == 3) go to 770
      KORD1I = 3
      KORD(3) = 0
  770 if (ICF == NTE) go to 790
      if (KORD2I == -6) then
         if (ICS == 1) go to 790
      end if
      ICS = ICF + 1
  780 KORD(3) = KORD(3) + 1
      ICF = IOP18 + KORD(3)
      ICF = abs(KORD(ICF))
      if (ICF) 1360, 780, 1360
!++  End
  790 ICS = 1
      ICF = NE
!++  Code for VAREQ is active
      if (KORD2I == 0) if (EREP) 2220, 2220, 1430
!++  End
      if (LINC + 5) 1490, 810, 1490
! END OF SPECIAL CODE FOR INITIALIZATION AT THE START
! ********
! UPDATE VARIABLES TO PREPARE FOR NEXT STEP
! ********
  800 LDT = 0
      EIMIN = C2P5M3+EIMIN*(C6*EAVE+EIMAX)/((EIMIN+C1)*(C6*EIMAX+EAVE))
  810 do 820 J = 1, NY
  820    Y(NYNY + J - 1) = Y(J)
      TN = TSPECS(1)
! ********
! TEST FOR VARIOUS TYPES OF OUTPUT
! ********
!     TEST FOR END OF STEP OUTPUT (OR IF DUMP OUTPUT TO BE TESTED FOR)
      if (IOP6 == 0) go to 840
!   SET UP FOR END OF STEP OUTPUT
      KORD1I = 6
      go to 1810
!     SET UP AFTER OTHER COMPUTATIONS HAVE BEEN MADE (TSPECS(1)/=TN)
  830 KORD1I = 6
      go to 860
!     TEST FOR AN OUTPUT POINT
  840 if (HH * (TMARK - TN)) 1760, 1760, 850
!     TEST FOR TOO MANY STEPS OUTPUT
  850 continue
      if (KSOUT > KSTEP) go to 890
      KORD1I = 4
  860 if (TSPECS(1) == TN) go to 1810
!     GO INTERPOLATE VALUES AT END OF LAST STEP
  870 TSPECS(1) = TN
      go to 1780
!     CONTINUE AFTER TOO MANY STEPS OUTPUT
  880 continue
      KSOUT = KSTEP + IOP4
  890 continue
!++  Code for DUMP is active
      if (IOP9 == 0) go to 920
!++  Code for DUMP & STIFF is inactive
!      KQMXDS=KQMAXD
!++  Code for DUMP is active
      KQMXIS = KQMAXI
      KIS = KIS + 1
      if (KIS /= 0) go to 920
!.   TIME TO DUMP THE SOLUTION
  900 KORD1I = 9
!.    SET TO UPDATE THE DIFFERENCE TABLE
      if (LDT == 1) go to 1810
! Note that doing this update can lead to very small differences in the
! results because of round off differences.
      LDT = -2
      go to 1780
!++  End
! RETURN AFTER DUMPING THE SOLUTION
  910 continue
!++  Code for DUMP is active
      KIS = 2
!.    TEST IF SOLUTION DUMP DUE TO RESTART, END, OR
!.    DROP IN INTEG. ORDER
      if (LINC < 0) if (LINC + 6) 1860, 1750, 1180
!++  End
! END OF TESTING FOR VARIOUS TYPES OF OUTPUT
!   TEST IF STEPSIZE MAY BE INCREASED OR IF TESTS SHOULD BE MADE
!   FOR DECREASING THE STEPSIZE (OR IF STARTING OR USER SELECTING H)
  920 KSTEP = KSTEP + 1
      if (LINC) 930, 980, 940
  930 continue
!     **** ONLY POSSIBLE VALUES AT THIS POINT ARE
!          LINC = -2 OR -5
      if (LINC + 5) 1120, 1110, 1120
! ********
! ERROR ESTIMATES INDICATE STEPSIZE CAN BE INCREASED
! ********
  940 HC = HINCC
      if (LINC > 1) HC = HC ** LINC
      HH = HC * HH
!     TEST IF NEW STEPSIZE IS TOO BIG
      if (abs(HH) > HMAX) if (HMAX) 970, 970, 960
  950 EAVE = EIMAX
      ROBND = CP3 + HINCC
      go to 1110
!     NEW STEPSIZE IS TOO BIG
  960 if (abs(XI(1)) >= HMAXP9) go to 970
      HH = sign(HMAX, HH)
      go to 950
!     RESTORE THE OLD STEPSIZE
  970 HH = XI(1)
      LINC = 0
      go to 1150
! END OF CODE FOR CASE WHEN ERROR ESTIMATES INDICATE STEPSIZE INCREASE
! ********
! TEST IF ESTIMATED ERRORS INDICATE STEPSIZE SHOULD BE DECREASED
! ********
  980 ROBND = C1P3
      if (EIMAX <= EAVE) go to 990
      EAVE = EAVE + CP4 * (EIMAX - EAVE)
      if ((EIMAX * EMAX) - C1M3) 1000, 1010, 1010
  990 EAVE = EIMAX
      if ((EIMAX * EMAX) >= EIMIN) go to 1010
 1000 ROBND = CP3 + (SIGMA(KQMAXS)/SIGMA(KQMAXS-1))
      go to 1180
!     TEST IF STEPSIZE SHOULD BE REDUCED
 1010 if (EMAX * EIMAX < EXR * EAVE) go to 1180
! ********
! ERROR ESTIMATES INDICATE STEPSIZE SHOULD BE REDUCED
! ********
      HC = HDEC
      if (EIMIN <= EIMINO) go to 1030
      EIMIN = EIMINO
      HC = CP875
 1030 HH = HC * XI(1)
      if (LSC - 1) 1040, 1080, 1090
 1040 if (abs(HH) >= HMIN) go to 1090
      if (abs(CP875*XI(1)) <= HMIN) if (LINC) 1050, 970, 970
      HH = sign(HMIN, HH)
      go to 1090
!     STEPSIZE IS TOO SMALL TO BE REDUCED
!     SET UP ERROR INDICATORS AND PREPARE FOR RETURN TO USER
 1050 KORD1I = 8
      go to 2240
!     PROCEED WITH CURRENT STEPSIZE DESPITE ERROR BEING TOO BIG
 1070 HH = XI(1)
      TSPECS(2) = HH
      EMAX = C0
      LINC = 0
      if (KORD1I - 2) 1420, 1430, 1430
!     SET LSC TO END STARTING PHASE
 1080 LSC = 2
!     CHECK IF REPEATING A STEP
 1090 if (LINC /= -1) go to 1110
!   WHEN REPEATING A STEP, BACK UP THE DIFFERENCES AND STEPSIZE INFO.
 1100 call DIVABU(F, KORD)
!   TEST IF NOISE TEST (LINC = -7) OR IF H IS NOT
!     BEING CHANGED (LINC = -4)
      if (LINC + 4) 1780, 1180, 1110
! ********
! STEPSIZE IS TO BE CHANGED
! ********
 1110 continue
! MODIFY STEPSIZE TO REDUCE ROUNDOFF ERROR IN ACCUMULATING INDEP. VAR.
      TP = C2 * abs(TN) + C4096 * abs(HH)
      TP = (TP + abs(HH)) - TP
      if (TP /= C0) HH = sign(TP, HH)
!     TEST IF NEW STEPSIZE SELECTED ACTUALLY GIVES A CHANGE
      if (HH == TSPECS(2)) go to 1140
 1115 TSPECS(2) = HH
      if (IOP8 == 0) go to 1140
!     SETUP TO TELL USER ABOUT STEPSIZE CHANGE (OR TO CHANGE STEPSIZE)
 1120 KORD1I = 8
      go to 860
!     RETURN AFTER TELLING USER ABOUT STEPSIZE CHANGE
 1130 HH = TSPECS(2)
 1140 if (HH /= XI(1)) KQICON = -1
 1150 HC = min(EOVEP2, abs(HH)) / EEPS2
! ********
! PREPARE FOR BEGINNING A NEW STEP
! ********
      if (LINC > 0) then
         LINC = min(LINC, LINCQ) + LINCQ
         go to 1190
      end if
 1180 LINC = LINCD
 1190 if (HC > abs(TN)) go to 1200
!     **** GIVE SINGULARITY DIAGNOSTIC
      KORD1I = 5
      go to 2240
 1200 TSPECS(1) = TN + HH
      if (LEX == 0) go to 1250
      if (HH * (TSPECS(1) - TMARKX) < C0) go to 1250
      TSPECS(1) = TMARKX
      HH = TMARKX - TN
      LINC = 64
      if (LEX > 0) go to 1240
      if ((LSC < 4) .and. (HH / XI(1) < CP3)) go to 1230
 1220 HH = CP875 * HH
      go to 1110
!     **** GIVE OUTPUT AT CURRENT TMARK (WITH EXTRAPOLATION)
 1230 KORD1I = -KMARK
      go to 1770
!     **** INTEGRATE TO TMARKX
 1240 KQICON = -1
!   TEST IF SUBROUTINE FOR COMPUTING INTEGRATION COEFF. SHOULD BE CALLED
 1250 continue
!++  Code for STIFF is inactive
!      IF ((KQMAXI <KQICON) .OR. (KQMAXD<KQDCON)) GO TO 1320
!++  Code for ~STIFF is active
      if (KQMAXI < KQICON) go to 1320
!++  End
!   GO COMPUTE COEFFICIENTS REQUIRED FOR THE INTEGRATION
!     TEST IF STARTING
      if (LSC < 7) go to 1310
 1260 KQMAXI = 2
!++  Code for STIFF is inactive
!      IF (METHOD) 1262,1270,1264
! 1262 KQMAXI=0
! 1264 KQMAXD=max(MAXDIF,2)
!      CALL DIVAHC
!c.  SET UP TO GO DO INITIALIZATION FOR CASE OF STIFF EQUATIONS
!      KORD1I=5
!      GO TO 1350
!++  End
!   INITIALIZE FOR EQUATIONS WHICH ARE NOT STIFF
 1270 KQMAXD = 0
      call DIVAHC
      J = NDTF
      do 1300 I = 1, NTE
!++  Code for STIFF is inactive
!         if (KORD(I + 3) <= 0) go to 1290
!++  End
         KORD(I + 3) = 1
!     INITIALIZE THE DIFFERENCE TABLE
         if (LDT == -4) F(J) = F(I)
         F(J + 1) = C0
         F(J + 2) = C0
 1290    continue
         J = J + NUMDT
 1300    continue
      if (LSC == 5) go to 1340
      LSC = 7
      LDT = 1
      go to 1330
!   INTEGRATION IS NOT BEING STARTED
 1310 K = KORD(KEMAX + 3)
      SIGMAS = SIGMA(K)
      call DIVAHC
!     **** ADJUST EAVE
      TPS1 = BETA(K)
      if (TPS1 > C1) TPS1 = CP5 * TPS1 + CP5
      EAVE = EAVE * TPS1 * (SIGMA(K) / SIGMAS)
!     TEST BELOW USED TO GET SAME RESULTS WITH/WITHOUT EXTRA EQUATIONS
      if (K > KQICON) LSC = max(LSC, -3)
! END OF SPECIAL LOGIC FOR CASE WHEN INTEG. COEFF. ROUTINE IS CALLED
 1320 continue
! ********
! PREDICT Y
! ********
 1330 continue
!++  Code for ~ARGM is active
      call DIVAPR(Y, Y(NYNY), F, KORD)
!++  Code for ARGM is inactive
!      CALL DIVAPE
!++  End
!     GO GET PREDICTED DERIVATIVES
 1340 KORD1I = KPRED
! ********
! CALL DIVAF  (OR RETURN)
! ********
 1350 KORD2I = 0
 1360 KORD(1) = KORD1I
      KORD(2) = 0
      if (IOP13 /= 0) return
      call DIVAF(TSPECS(1), Y, F, KORD(1))
!     TEST FOR SPECIAL USER RETURN
 1380 if (KORD(1) < 0) go to 2130
!     TEST FOR SPECIAL CASE
      if (KORD2I /= 0) go to 660
! ********
! TRANSFER CONTROL TO PROPER PLACE AFTER COMPUTING DERIVATIVES
! ********
      if (KORD1I - 2) 1400, 800, 1390
 1390 continue
!++  Code for VAREQ is active
      if (ICS - ICF) 1410, 1410, 760
!++  End
! ********
! PREPARE FOR CORRECTING, AND CORRECT Y
! ********
 1400 ITOLEP = 0
      ILGREP = 0
      IY = 1
      EIMAX = C1M5
      EMAX = C0
      KQMAXI = 2
      KQMAXS = 2
!++  Code for STIFF is inactive
!      IF (METHOD) 1404,1410,1406
! 1404 KQMAXI=0
! 1406 KQMAXD=2
!++  End
 1410 continue
!++  Code for ~ARGM is active
      call DIVACR(Y, F, KORD, F(NTOLF), KORD(IOP16))
!++  Code for ARGM is inactive
!      CALL DIVACE
!++  End
!     TEST IF ESTIMATED ERROR IS TOO BIG (OR IF DIAGNOSTIC CALLED FOR)
      if (EMAX > EREP) if (EREP) 2210, 2210, 1670
 1420 continue
!++  Code for VAREQ is active
      if (IOP18 /= 0) go to 760
!++  End
 1430 KORD1I = 2
!     TEST IF NOISE APPEARS TO LIMIT PRECISION
      if (EMAX < C0) go to 1470
!++  Code for ~STIFF is active
      if (LSC) 1450, 1360, 1610
!++  Code for STIFF is inactive
!      IF (LSC) 1450,1460,1610
!++  End
!     SET LSC=0 IF NOISE NO LONGER APPEARS TO LIMIT PRECISION
!     OR IF THE END OF THE STARTING PHASE HAS BEEN REACHED
 1450 LSC = 0
 1460 if (METHOD) 800, 1350, 1350
! ********
! NOISE APPEARS TO BE LIMITING PRECISION
! ********
 1470 continue
      if (LSC <= 0) LSC = max(LSC - 1, -KQMAXS)
      if (LSC == -1) go to 1460
      if (abs(EMAX) < EXR) go to 1590
      LINC = -7
      TPS2 = (C1 + BETA(NOISEQ - 1)) ** NOISEQ
      if (SNOISE < EEPS10 * TPS2) go to 1550
      TP = sign(EEPT75 * abs(TN) + OVTM75, HH)
      if (abs(TP) > abs(HH)) go to 1550
      TSPECS(1) = TN + TP
      KORD1I = 0
!     **** GO TO BACK UP THE DIFFERENCES AND GET F(TSPECS(1))
      go to 1100
!     **** SOLUTION HAS BEEN INTERPOLATED AND F COMPUTED
 1490 continue
      KORD1I = 0
      LINC = LINC - 1
      if (LINC + 9) 1510, 1520, 1500
 1500 TSPECS(1) = TN + (TP + TP)
      TP1 = F(KEMAX)
      TP2 = F(NDTF + NUMDT * KEMAX - NUMDT)
      go to 1780
!     **** COMPUTE 2-ND DIFFERENCE AT CLOSE SPACED T VALUES
 1510 TP2 = TP3
 1520 TP3 = F(KEMAX)
      TPS1 = abs((TP3 - TP1) - (TP1 - TP2))
      if ((C16 * TPS1 * TPS2) >= DNOISE) if (LINC + 9) 1550, 870, 1550
 1530 continue
      TPS2 = CP25 * SNOISE / RBQ(NOISEQ)
      do 1540 K = 2, NUMDT
         TPS1 = TPS1 + TPS1
         RBQ(K) = max(TPS1, TPS2 * RBQ(K))
 1540    continue
      LINC = 0
!FTK Next two lines added 2009-10-15
      if (abs(EMAX) < EREP) go to 1460
!FTK  LINC = -1  And then on 2015-03-14 commented out this line
      HH = CP875 * HH
      go to 1040
!     **** SET UP TO GIVE NOISE DIAGNOSTIC
 1550 KORD1I = 6
      go to 2240
!     **** AFTER GIVING NOISE DIAGNOSTIC
 1560 KORD1I = 2
      if (KORD(2) >= 0) then
        TPS1 = EEPS10
!FTK Next line added 2009-10-15
        if (TPS1 < .49D0 * RBQ(2)) go to 1530
      end if
!     **** SET NEW VALUE FOR OFFENDING TOL
      F(NTOLF + ITOLEP - 1) = FDAT(7)
      if (LINC + 7) 1180, 1570, 1180
 1570 LINC = 0
 1580 if (LSC) 1460, 1460, 1610
!     **** CHANGE HINCC AND ADJUST SIGMA()
 1590 if (LSC /= -4) go to 1580
      if (HINCC == C1P125) go to 1580
      TPS1 = C1P125 / HINCC
      TPS2 = 1.0D0
      do 1600 K = 2, IOP11
         TPS2 = TPS2 * TPS1
         SIGMA(K) = SIGMA(K) * TPS2
 1600    continue
      EAVE = EAVE * TPS1 ** (1-KORD(KEMAX+3))
      LINCD = 6
      LINCQ = 12
      HINCC = C1P125
      go to 1460
!   END OF CODE FOR CASE WHEN NOISE APPEARS TO LIMIT PRECISION
! ********
! SPECIAL LOGIC FOR STARTING THE INTEGRATION
! ********
 1610 if (LSC == 1) go to 800
      LSC = LSC - 1
      if (LSC - 2) 1620, 1640, 1650
 1620 if (EIMAX <= (CP0625*EAVE*(SIGMA(KQMAXS)/SIGMAS)*(BETA(KQMAXS+  &
     &   1))**2)) go to 800
 1630 KSSTRT = KSTEP + 2
!   TEST IF STEPSIZE IS TOO SMALL BEFORE ENDING STARTING PHASE
      if (abs(HH) >= HMIN) go to 1450
!     GIVE DIAGNOSTIC FOR STEPSIZE TOO SMALL AT END OF START
      KORD1I = 7
      go to 2240
!   SET LSC TO DO ONE DERIVATIVE EVAL. PER STEP
 1640 LSC = 1
      go to 800
!     TEST IF FIRST TIME THROUGH THE FIRST STEP
 1650 if (LSC == 6) go to 1340
!     END STARTING PHASE IF CONVERGENCE OF CORRECTOR ITERATES TOO SLOW
      if (LDT == -5) go to 1660
      LSC = min(LSC, 4)
      go to 800
 1660 LDT = 0
      if (LSC - 4) 1260, 1630, 1260
! END OF SPECIAL LOGIC FOR STARTING THE INTEGRATION
! ********
! ESTIMATED ERROR IS TOO BIG
! ********
 1670 if (BETA(2) - C1) 1690, 1730, 1680
 1680 HC = C1 / BETA(2)
      if (BETA(2) >= C1P125) go to 1740
 1690 if (BETA(2) > CP1) go to 1730
!   REQUIRED STEPSIZE REDUCTION IS TOO RAPID -- GIVE A DIAGNOSTIC
      KORD1I = 4
      go to 2240
!
!     TEST KORD(2) AFTER ABOVE DIAGNOSTIC OR A DISCONTINUITY DIAGNOSTIC
 1700 continue
      if (KORD(2) == 0) go to 1730
!  TEST IF SOLUTION MUST BE DUMPED BEFORE A RESTART
 1710 LINC = -1
!++  Code for DUMP is active
      if (IOP9 == 0) go to 1750
      if (KIS == 2) go to 1750
      LINC = -6
!.    GO DUMP SOLUTION BEFORE REPEATING THE STEP
 1720 KQMAXI = KQMXIS
!++  Code for DUMP & STIFF is inactive
!      KQMAXD=KQMXDS
!++  Code for DUMP is active
      call DIVABU(F, KORD)
      go to 900
!++  End
!   SET UP TO REPEAT THE STEP
 1730 HC = CP5
 1740 LINC = -1
      if (LSC <= 3) go to 1030
!   RESTART THE INTEGRATION IF ERROR IS TOO BIG ON FIRST OR SECOND STEP
! LOOP TO SELECT A NEW INITIAL STEPSIZE
 1750 LSC = 7
 1755 HH = HH * CP5
      EMAX = EMAX * CP25
      if (EMAX >= CP3) go to 1755
      go to 1090
!   END OF SELECTING A NEW INITIAL STEPSIZE
! END OF LOGIC FOR CASE WHEN ESTIMATED ERROR IS TOO BIG
! ********
! INTEGRATION HAS REACHED AN OUTPUT POINT
! ********
 1760 if (KMARK == 0) go to 1920
      KORD1I = min(KMARK, 5)
      KORD(3) = KMARK
      if (TSPECS(1) == TMARK) go to 1790
 1770 TSPECS(1) = TMARK
 1780 call DIVAIN(TSPECS(1), Y, F, KORD)
 1790 continue
      if (KORD1I) 1800, 730, 1810
!   OUTPUT POINT IS OBTAINED BY EXTRAPOLATION
 1800 continue
!++  Code for EXTRAP is active
      KORD1I = -KORD1I
      KORD2I = -7
      KEXIT = 4
!.  TEST IF GSTOP-S ARE PRESENT
!++  Code for EXTRAP &  GSTOP is active
      if (NGTOT == 0) go to 1820
      IGFLG = 4
      KEXIT = 2
      KORD1I = 7
      if (IOP7) 740, 1820, 740
!++  End
! ********
! CALL DIVAO  (OR RETURN)
! ********
 1810 KORD2I = 1
 1820 KORD(1) = KORD1I
      KORD(2) = 1
      if (IOP14 /= 0) return
      call DIVAO(TSPECS(1), Y, F, KORD(1))
!     TEST FOR SPECIAL USER RETURN OR FOR A RESTART
!++  Code for ~DUMP is inactive
! 1840 IF (KORD(1)) 2130,700,1880
!++  Code for DUMP is active
 1840 if (KORD(1) > 0) go to 1880
 1850 if (IOP9 == 0) go to 1870
!.    **** GO DUMP THE SOLUTION
      LINC = -7
      ITOLEP = KORD(1)
      IDAT(1) = KORD(2)
      NEPTOL = KORD1I
      if (LSC /= 8) go to 900
 1860 LINC = min(0, LINCD)
      KORD1I = NEPTOL
      KORD(1) = ITOLEP
      KORD(2) = IDAT(1)
 1870 if (KORD(1)) 2130, 700, 2100
!++  End
 1880 if (KORD2I < 0) go to (2140, 1810, 1350, 2110, 720, 750, 680,  &
     &   710), -KORD2I
      if (KORD2I == 0) go to 1380
! ********
! TRANSFER CONTROL TO PROPER PLACE AFTER OUTPUT
! ********
 1890 if (KORD1I - 5) 1910, 1930, 1900
 1900 if (KORD1I - 8) 840, 1130, 910
 1910 if (KORD1I - 3) 1920, 1930, 880
!   GET NEW TOUT
 1920 TOUT = TSPECS(1) + TSPECS(3)
! GET NEW TMARK (NEXT INDEP. VAR. OUTPUT POINT)
 1930 XP = TMARK
      K = KMARK
      TMARK = TOUT
      KMARK = 2
      LEX = 0
      if (IOP5) 1940, 1980, 1970
 1940 I = -IOP5
 1950 I = I + 3
      J1 = KORD(I - 3)
      if (J1) 1950, 1980, 1960
 1960 J2 = KORD(I - 2)
      L = KORD(I - 1)
      go to 1990
 1970 J1 = 5
      J2 = IOP5
      L = 0
      if (J2 >= J1) go to 1990
 1980 J1 = 4
      J2 = 4
      L = IOP3
!
!     **** LOOP TO SET NEW TMARK (AND TMARKX)
 1990 do 2060 J = J1, J2
!        **** TEST IF EXTRAPOLATION NOT POSSIBLE
         if (L == 0) go to 2010
         LX = 2
         if (LEX) 2020, 2030, 2020
 2000    LEX = L
 2010    LX = 1
 2020    if (HH * (TSPECS(J) - TMARKA(LX))) 2030, 2060, 2060
 2030    if (J == 4) go to 2050
         if (HH * (TSPECS(J) - XP)) 2060, 2040, 2050
 2040    if ((K >= J) .or. (K == 3)) go to 2060
 2050    TMARKA(LX) = TSPECS(J)
         if (LX == 2) go to 2000
         KMARK = J
 2060    continue
      if (IOP5 < 0) go to 1950
      if (J1 /= 4) go to 1980
      if (KMARK == 4) KMARK = 3
!     **** TEST IF NEW TMARK IS ACCEPTABLE
      if (HH * (XP - TMARK)) 2070, 2080, 2090
 2070 if (KORD2I - 1) 670, 840, 670
 2080 if (K /= KMARK) go to 2070
!++  Code for DUMP is active
      if (KORD1I == 3) go to 1850
!++  Code for ~DUMP is inactive
!      IF (KORD1I == 3) GO TO 2100
!++  End
 2090 if (KORD1I == 13) go to 2190
! SETUP TO INDICATE ERROR IN SPECIFICATION OF OUTPUT POINTS
      KORD1I = 2
      IDAT(2) = KMARK
      if (KMARK <= 3) IDAT(2) = KMARK + 1
      FDAT(3) = TSPECS(IDAT(2))
      go to 2240
!     SET KORD1I=1 TO INDICATE THAT END OF INTEGRATION HAS BEEN REACHED
 2100 KORD1I = 1
! ********
! RETURN TO USER
! ********
 2110 KORD2I = -1
      KORD(1) = KORD1I
 2130 KORD(2) = -1
      return
! ********
! TRANSFER CONTROL TO PROPER PLACE AFTER RETURN TO USER
! ********
 2140 if (KORD1I - 2) 2150, 1560, 2160
 2150 KORD2I = 1
      go to 1930
 2160 if (KORD1I - 4) 1700, 2200, 2170
 2170 if (KORD1I - 13) 2180, 1930, 2190
 2180 if (abs(HH) >= HMIN) if (KORD1I - 11) 1030, 1450, 1030
      if (KORD(2) == 0) if (KORD1I - 11) 1070, 800, 1070
!   ERROR MESSAGES HAVE BEEN IGNORED -- COMPUTATION CAN NOT CONTINUE
 2190 KORD1I = 1
      go to 2240
!
!        AFTER A DISCONTINUITY RETURN
 2200 LINC = -4
      if (KORD(2)) 1710, 1730, 1100
! ********
! PROBLEM ENCOUNTERED WHEN CORRECTING
! ********
 2210 if (LDIS == 0) go to 2230
!           Extra checks when had a user specified discontinuity.
!++  Code for VAREQ is active
      if (IOP18 /= 0) go to 760
!++  End
 2220 KORD1I = 2
      LDIS = LDIS + 1
      TP = DISADJ / HH
      if (KIS >= 1000) then
         if (LDIS == 2) then
            if (KQMAXS <= 3) then
               LDIS = 0
               EREP = abs(EREP)
               TSPECS(2) = HH*min(min(TP, TP**2),                       &
     &            (CP25 * EXR/EMAX)**.333333333D0)
               go to 720
            end if
            LINC = -5
            if (IOP9 == 0) KIS = 1001
            go to 800
         end if
         if (IOP9 == 0) KIS = KIS + 1
         if (KQMAXS <= LDIS + 2) KIS = LDIS + 1
         LINC = min(LINC, LDIS-2)
      end if
      if (LDIS > 2*KQMAXS) then
         EREP = abs(EREP)
         LDIS = 0
         if (EMAX > EREP) go to 1670
         go to 1430
      end if
      if (TP >= HINCC**(LINC+2)) then
         if ((LDIS /= 3) .and. (TP > dble(KQMAXS))) LSC = 1
         EIMIN = CP5
         EAVE = EAVE * TP**8
      end if
      if (LSC == 2) go to 1630
      if (EMAX > EXR) go to 1730
      go to 1430
!
 2230 EREP = abs(EREP)
!++  Code for DUMP is active
      if (LINC < -3) go to 1720
!++  End
!     BAD TOL
      KORD1I = 3
! ********
! ERROR PROCESSING
! ********
 2240 FDAT(1) = TN
      FDAT(2) = HH
      IDAT(1) = KSTEP
      ITOLEP = max(NEPTOL, -NEPTOL - 1)
      J = 3
      if (KORD1I >= 7) then
         J = 4
         FDAT(3) = HMIN
      end if
      if (KORD1I <= 3) then
         if (KORD1I < 3) then
            K = 8
         else
            MACT(9) = LTXTAL
            FDAT(3) = C0
            IDAT(2) = ITOLEP
            IDAT(3) = ITOLEP + NTOLF - 1
            K = 11
         end if
      else
         MACT(9) = LTXTAK
         FDAT(J) = EMAX
         IDAT(2) = KEMAX
         IDAT(3) = ITOLEP
         IDAT(4) = ITOLEP + NTOLF - 1
         FDAT(J+1) = F(IDAT(4))
         K = 14
         if (KORD1I == 6) then
            K = 17
            IDAT(5) = IDAT(4)
            FDAT(7) = 32.D0 * abs(EMAX) * FDAT(J+1)
            FDAT(J+2) = FDAT(7)
         end if
         MACT(12) = LTXTAL
         if (NEPTOL < 0) then
            MACT(12) = LTXTAM
            IDAT(6) = IDAT(4)
            IDAT(5) = IDAT(4) + 1
            FDAT(J+2) = F(IDAT(5))
            FDAT(J+3) = FDAT(J+1) * FDAT(J+2)
         end if
      end if
! Set the location for the first part of the message that varies, set
! the error severity, and the index number, print the error and
! return or stop.
      L = MLOC(KORD1I)
      MACT(6) = L / LOCM
      MACT(2) = (L - MACT(6) * LOCM) / 32
      KORD1I = mod(L, 32)
      MACT(3) = KORD1I
      MACT(K) = MERET
!--D Next line special: P=>S, X=>D
      call DMESS(MACT, MTXTAA, IDAT, FDAT)
      MACT(K) = MENTXT
      go to 2110
    end subroutine divaa
Call graph
divaa calls divabu, divahc, dmess
dmess calls messfi