DIVAOP – diva
DIVAOP Subroutine
178 statements
Source File
public subroutine DIVAOP(IOPT, FOPT)
SUBROUTINE TO SET UP OPTIONS FOR DIFFERENTIAL EQUATION PACKAGE -IVA
History
1987-12-07 DIVAOP Krogh Initial code.
Arguments
Type Intent Optional Attributes Name
integer :: IOPT(*)
double precision :: FOPT(*)
Calls
Called by
Contents
Common Blocks
DIVASC DIVAMC DIVAEV
Source Code
DIVAOP
Common Blocks
common /DIVASC/
Type Attributes Name Initial
real :: TN
real :: XI
integer :: IOPST
integer :: KORDI
integer :: KQMAXD
integer :: KQMAXI
integer :: LDT
integer :: MAXDIF
integer :: MAXINT
integer :: NKDKO
integer :: NTE
integer :: NYNY
integer :: NDTF
integer :: NUMDT
common /DIVAMC/
Type Attributes Name Initial
real :: TG
real :: TGSTOP
real :: TMARK
real :: TMARKX
real :: TOUT
real :: TOLG
real :: HC
real :: HDEC
real :: HINC
real :: HINCC
real :: HMAX
real :: HMAXP9
real :: HMIN
real :: ALPHA
real :: BETA
real :: D
real :: G
real :: V
real :: DS
real :: GS
real :: SIGMA
real :: RBQ
real :: DNOISE
real :: EAVE
real :: EIMAX
real :: EIMIN
real :: EMAX
real :: EREP
real :: ROBND
real :: SNOISE
real :: FDAT
integer :: ICF
integer :: ICS
integer :: IGFLG
integer :: IGTYPE
integer :: IGSTOP
integer :: ILGREP
integer :: INGS
integer :: IOP3
integer :: IOP4
integer :: IOP5
integer :: IOP6
integer :: IOP7
integer :: IOP8
integer :: IOP9
integer :: IOP10
integer :: IOP11
integer :: IOP12
integer :: IOP13
integer :: IOP14
integer :: IOP15
integer :: IOP16
integer :: IOP17
integer :: IOP18
integer :: IOP19
integer :: IOP20
integer :: IOP21
integer :: IOP22
integer :: IOP21S
integer :: ITOLEP
integer :: IY
integer :: KEMAX
integer :: KIS
integer :: KMARK
integer :: KORD1I
integer :: KORD2I
integer :: KPRED
integer :: KQDCON
integer :: KQICON
integer :: KQMAXS
integer :: KQMXDS
integer :: KQMXIL
integer :: KQMXIP
integer :: KQMXIS
integer :: KSC
integer :: KSOUT
integer :: KSSTRT
integer :: KSTEP
integer :: LEX
integer :: LINC
integer :: LINCD
integer :: LINCQ
integer :: LSC
integer :: MAXKQD
integer :: MAXKQI
integer :: METHOD
integer :: NE
integer :: NEPTOL
integer :: NG
integer :: NGTOT
integer :: NOISEQ
integer :: NOUTKO
integer :: NTOLF
integer :: NY
integer :: IDAT
common /DIVAEV/
Type Attributes Name Initial
real :: EEPS2
real :: EEPT75
real :: EOVEP2
real :: OVTM75
real :: OVD10
real :: EEPS10
real :: EEPS16
real :: EROV10
Source Code
    subroutine DIVAOP(IOPT, FOPT)
      double precision FOPT(*)
      integer IOPT(*)
!
      integer KDIM, MAXORD, MAXSTF
!++ Substitute for KDIM, MAXORD, MAXSTF below
      parameter (KDIM = 20, MAXORD = 2, MAXSTF = 1)
      double precision TN
      double precision XI(KDIM)
!
      double precision TG(2), TGSTOP(2), TMARK, TMARKX, TOUT, TOLG
      double precision ALPHA(KDIM), BETA(KDIM+1)
      double precision D(MAXSTF+MAXORD,MAXORD), G(KDIM,MAXORD)
      double precision V(KDIM+MAXORD)
      double precision HC, HDEC, HINC, HINCC, HMAX, HMAXP9, HMIN
      double precision FDAT(11)
!
      double precision DS(MAXSTF+MAXORD, MAXORD), GS(KDIM)
      double precision SIGMA(KDIM), RBQ(KDIM), DNOISE
      double precision EAVE, EIMAX, EIMIN, EMAX, EREP, ROBND, SNOISE
!
      integer IOPST, KORDI, KQMAXD, KQMAXI, LDT, MAXDIF, MAXINT, NKDKO, &
     &   NTE, NYNY, NDTF, NUMDT
      common / DIVASC / TN, XI, IOPST, KORDI, KQMAXD, KQMAXI, LDT,      &
     &   MAXDIF, MAXINT, NKDKO, NTE, NYNY, NDTF, NUMDT
!
      integer ICF,ICS,IGFLG,IGTYPE(2),IGSTOP(2),ILGREP,INGS,IOP3,IOP4,  &
     &   IOP5,IOP6,IOP7,IOP8,IOP9,IOP10,IOP11,IOP12,IOP13,IOP14,IOP15,  &
     &   IOP16,IOP17,IOP18,IOP19,IOP20,IOP21,IOP22,IOP21S,ITOLEP,IY,    &
     &   KEMAX,KIS,KMARK,KORD1I,KORD2I,KPRED,KQDCON,KQICON,KQMAXS,      &
     &   KQMXDS,KQMXIL,KQMXIP,KQMXIS,KSC,KSOUT,KSSTRT,KSTEP,LEX,LINC,   &
     &   LINCD,LINCQ,LSC,MAXKQD,MAXKQI,METHOD,NE,NEPTOL,NG,NGTOT,       &
     &   NOISEQ,NOUTKO,NTOLF,NY,IDAT(6)
      common /DIVAMC/ TG,TGSTOP,TMARK,TMARKX,TOUT,TOLG,HC,HDEC,HINC,    &
     &   HINCC,HMAX,HMAXP9,HMIN,ALPHA,BETA,D,G,V,DS,GS,SIGMA,RBQ,DNOISE,&
     &   EAVE,EIMAX,EIMIN,EMAX,EREP,ROBND,SNOISE,FDAT,ICF,ICS,IGFLG,    &
     &   IGTYPE,IGSTOP,ILGREP,INGS,IOP3,IOP4,IOP5,IOP6,IOP7,IOP8,IOP9,  &
     &   IOP10,IOP11,IOP12,IOP13,IOP14,IOP15,IOP16,IOP17,IOP18,IOP19,   &
     &   IOP20,IOP21,IOP22,IOP21S,ITOLEP,IY,KEMAX,KIS,KMARK,KORD1I,     &
     &   KORD2I,KPRED,KQDCON,KQICON,KQMAXS,KQMXDS,KQMXIL,KQMXIP,KQMXIS, &
     &   KSC,KSOUT,KSSTRT,KSTEP,LEX,LINC,LINCD,LINCQ,LSC,MAXKQD,MAXKQI, &
     &   METHOD,NE,NEPTOL,NG,NGTOT,NOISEQ,NOUTKO,NTOLF,NY,IDAT
      save / DIVAMC / , / DIVASC /
!.    SPECIFICATION OF ENVIRONMENTAL CONSTANTS.
      double precision EEPS10, EEPS16, EROV10, EEPS2, EEPT75, EOVEP2
      double precision OVTM75, OVD10
      common / DIVAEV / EEPS2, EEPT75, EOVEP2, OVTM75, OVD10, EEPS10,   &
     &   EEPS16, EROV10
      save / DIVAEV /
!
      integer IOPTS(23), INCOP(22), IOPTC(23), I, IA, J, K, LIOPT, MULTJ
      double precision CMP75, C0, CP25, CP3, CP5, CP625, CP75, CP875,   &
     &   CP9, C1, C1P125, C2, C4, C10, C16
      parameter (CMP75 = (-.75D0))
      parameter (C0 = 0.D0)
      parameter (CP25 = .25D0)
      parameter (CP3 = .3D0)
      parameter (CP5 = .5D0)
      parameter (CP625 = .625D0)
      parameter (CP75 = .75D0)
      parameter (CP875 = .875D0)
      parameter (CP9 = .9D0)
      parameter (C1 = 1.D0)
      parameter (C1P125 = 1.125D0)
      parameter (C2 = 2.D0)
      parameter (C4 = 4.D0)
      parameter (C10 = 10.D0)
      parameter (C16 = 16.D0)
      !external D1MACH
      !double precision D1MACH
      equivalence (IOPTC(3), IOP3)
      save IOPTS, LIOPT
!
!                      Declarations for error message processing.
!
      integer MECONT, MERET, MEEMES, MEIVEC
      parameter (MECONT =50)
      parameter (MERET  =51)
      parameter (MEEMES =52)
      parameter (MEIVEC =57)
      integer MACT(7), MACT1(5)
!
! ********* Error message text ***************
![Last 2 letters of Param. name]  [Text generating message.]
!AA DIVAOP$B
!AB Error in IOPT() specifications: IOPT =$E
!AC HMIN = $F is > HMAX = $F.$E
      integer LTXTAA,LTXTAB,LTXTAC
      parameter (LTXTAA= 1,LTXTAB= 9,LTXTAC=49)
      character MTXTAA(1) * (76)
      data MTXTAA/'DIVAOP$BError in IOPT() specifications: IOPT =$EHMIN$&
     & = $F is > HMAX = $F.$E'/
! **** End of text generated by pmess
!                      1   2  3   4       5  6      7
      data MACT / MEEMES, 88, 24, 0, MEIVEC, 0, MERET /
      data MACT1 / MEEMES, 28, 24, LTXTAC, MERET /
!
!                      IOP4       IOP17
      data IOPTS / 3*0, 500000, 12*0, 1, 6*0 /
!
!                  1  2    3  8  9 10 11 12  13  16   17 21 22
      data INCOP / 1, 3, 5*2, 1, 2, 3, 1, 2, 3*1, 3, 4*2, 2, 2 /
!
! ********* START OF EXECUTABLE CODE ***********************
!
      MULTJ = 1
      K = 1
 4200 I = IOPT(K)
      IA = abs(I)
! 1 and 6 lines below need 21 changed if more options are added.
      if (IA <= 21) if (I) 4220, 4520, 4280
      if (IA /= 1111) go to 4490
      if (I < 0) then
        MULTJ = -1
        K = K + 1
        go to 4200
      end if
      IOPT(2) = LIOPT
!
!     ****  INITIALIZE FOR STARTING A NEW INTEGRATION
      do 4210 J = 3, 23
 4210    IOPTC(J) = IOPTS(J)
      KSOUT = IOPTS(4)
      KMARK = 1 - IOPTS(1)
      KORDI = IOPTS(17)
      NKDKO = max(-KORDI, 0)
      IOPST = IOPTS(22)
      go to 4260
!
!     **** SET A NOMINAL VALUE
 4220 IOPTS(IA) = 0
      if (IA == 12) go to 4420
      if (IA - 2) 4400, 4240, 4230
 4230 if (IA == 4) IOPTS(4) = 500000
      if (IA == 21) TOLG = 0.D0
      go to 4390
!
!     **** SET ALL OPTIONS TO THEIR NOMINAL VALUES
 4240 IA = 1
      IOPTS(1) = 0
      do 4250 J = 3, 22
         IOPTS(J) = 0
         IOPTC(J) = 0
 4250 continue
      IOPTS(4) = 500000
      IOPTC(4) = IOPTS(4)
      IOPTS(17) = 1
      TOLG = 0.D0
 4260 NGTOT = IOPTS(7) + max(IOPTS(6), 0)
      if (IOPTS(12) == 0) go to 4420
 4270 return
!
!     **** SET SPECIFIED OPTION
 4280 J = IOPT(K + 1)
      if (INCOP(IA) - 2) 4290, 4330, 4300
!     **** OPTION INVOLVES NO EXTRA PARAMETERS
 4290 IOPTS(IA) = 1
      if (IA - 2) 4400, 4400, 4390
!     **** TAKE CARE OF SECOND EXTRA PARAMETER
 4300 if (IA /= 10) go to 4310
      NOUTKO = IOPT(K + 2)
      if (NOUTKO) 4500, 4350, 4350
 4310 if (IA /= 16) go to 4320
      NTOLF = IOPT(K + 2)
      if (NTOLF) 4500, 4500, 4350
 4320 if (J == 3) then
        if (KMARK /= 3) then
           if (XI(1)*(FOPT(IOPT(K+2)) - TMARK) >= C0) go to 4400
        end if
      end if
      TMARK = FOPT(IOPT(K+2))
      KMARK = J
      go to 4400
!     **** TAKE CARE OF FIRST EXTRA PARAMETER
 4330 continue
      if (IA == 12) go to 4410
      if (IA == 4) KSOUT = J
      if (IA == 21) TOLG = FOPT(J)
 4350 IOPTS(IA) = J * MULTJ
      if (abs(IA - 7) > 1) go to 4360
!     **** SET SPECIAL PARAMETERS FOR GSTOP-S
      IGFLG = 0
      NGTOT = IOPTS(7) + max(IOPTS(6), 0)
!     **** TEST FOR ERROR
      if (J > 500) go to 4500
 4360 if (J > 0) go to 4390
      if ((IA == 5) .or. (IA == 17)) go to 4390
      if (J + 1) 4500, 4370, 4380
 4370 if (IA == 7) go to 4500
 4380 if ((IA == 4) .or. (IA == 11) .or. (IA >= 16)) go to 4500
!     **** STORE SAVED VALUE IN COMMON
 4390 IOPTC(IA) = IOPTS(IA)
!
!     **** INCREMENT K TO GET NEXT OPTION
 4400 K = K + INCOP(IA)
      go to 4200
!
! ******* SET UP INFORMATION FOR CHANGING STEPSIZE *********
!
!     **** TEST IF VALUES ARE ALREADY SET
 4410 if (IOPTS(12) /= 0) go to 4430
!     **** SET NOMINAL VALUES FOR VARIABLES ONLY SET ONCE
 4420 EREP = CP3
!     **** SET NOMINAL VALUES FOR STEPSIZE CONTROL AND ENV. CONSTANTS
      EEPS2 = D1MACH(4)
      EEPS16 = C16 * EEPS2
      EEPS10 = CP625 * EEPS16
      EEPT75 = EEPS2 ** CP75
      EEPS2 = EEPS2 + EEPS2
      OVD10 = D1MACH(2)
      EROV10 = C10 / OVD10
      EOVEP2 = OVD10 * EEPS2
      OVTM75 = OVD10 ** CMP75
      OVD10 = OVD10 / C10
      HINC = C2
      HDEC = CP5
      HMIN = EROV10
      HMAX = OVD10
      if (I /= 12) go to 4470
 4430 IOPTS(12) = J * MULTJ
      if (J) 4450, 4470, 4460
!     **** SET UP TO GIVE USER COMPLETE STEPSIZE CONTROL
 4450 EREP = C1 / EROV10
      HINC = -C2
      IOP8 = 1
!## Recent code 12/16/94
      LINCD = -2
      LINC = -2
      ROBND = C1
!## Recent code 9/6/2001
      TOLG = 0.D0
!## End of recent code
      go to 4480
!     **** SET USER VALUES FOR STEPSIZE CONTROL
 4460 if (FOPT(J) /= C0) HINC = max(C1P125, min(FOPT(J),C4))
      if (FOPT(J + 1) /= C0) HDEC = min(CP875, max(FOPT(J + 1), CP25))
      if (FOPT(J + 2) /= C0) HMIN = FOPT(J + 2)
      if (FOPT(J + 3) /= C0) HMAX = FOPT(J + 3)
      if ((HMIN > HMAX) .or. (HMAX <= 0.D0)) then
         call DMESS(MACT1, MTXTAA, IOPT, FOPT(J+2))
         KORD2I = -4
      end if
 4470 KQICON = -1
 4480 HMAXP9 = HMAX * CP9
      if (I - 1111) 4400, 4270, 4400
!
! ***************** ERROR  IN  IOPT ************************
!
 4490 IA = 1
 4500 MACT(6) = K + INCOP(IA) - 1
      call MESS(MACT, MTXTAA, IOPT)
      KORD1I = 24
      KORD2I = -4
! Usual return with no error is here.
 4520 LIOPT = K
      return
    end subroutine divaop
Call graph
divaop calls mess
mess calls messgs, messpr, messmh, messfi, messfd
messfd calls messfi
diva calls divaop