DMESS – diva
DMESS Subroutine
172 statements
Source File
public subroutine DMESS(MACT, TEXT, IDAT, FDAT)
Processes Messages -- Actions are controlled by MACT(). See comment is subroutine MESS. This program is for the extra argument of type real.
BUF In common CMESSC, see MESS. DOLS In common for intitialization, not used here. See MESS. EUNIT In common for intitialization, not used here. See MESS. FDAT Formal argument -- gives floating point data to print. FBIG Largest magnitude of floating point number to output. FSMA Smalles magnitude floating point number to be printed. FMTF In common CMESSC, format for printing floating point number. FMTG In common CMESSC, user format to use in place of FMTF. FMTSP Format for printing sparse vectors. FOUT Floating point number to be output. FSMA Smallest postitive floating point number. ICOL In common CMESSI, see MESS. ID Number of decimal digits for floating point format statement. IDAT Integer data -- passed to MESS. IVAR In common CMESSI, see MESS. IWF In common CMESSI, see MESS. IWG In common CMESSI, see MESS. J Temporary index. K Temporary index. KSMA Number of leading 0's in "F" format. If < 0, -KSMA gives the number of extra digits to the left of the decimal point. KSMA depends on abs(smallest number printed). KBIG Number of extra digits before the decimal point required by the largest number to be printed if "F" format is used. KDF In common CMESSI, see MESS. KDFDEF In common CMESSI, see MESS. KDIAG In common CMESSI, not used here, see MESS. KEXE Extra space required for E format. KF In common CMESSI, see MESS. KLINE In common CMESSI, see MESS. KSCRN In common CMESSI, see MESS. KRES1 In common CMESSI, see MESS. KSPEC In common CMESSI, see MESS. LASTER In common CMESSI, not used here, see MESS. LASTI In common CMESSI, see MESS. LBUF In common CMESSI, see MESS. LDFDEF Value of KDFDEF for this routine. (Saved) LENBUF In common CMESSI, see MESS. LENLIN In common CMESSI, not used here, see MESS. LENTRY In common CMESSI, see MESS. LHEAD In common CMESSI, not used here, see MESS. LINERR In common CMESSI, not used here, see MESS. LINMSG In common CMESSI, not used here, see MESS. LOCBEG In common CMESSI, see MESS. LPRINT In common CMESSI, not used here, see MESS. LSTOP In common CMESSI, not used here, see MESS. LSTRT In common CMESSI, see MESS. MACT Formal argument, see MESS. MDAT In common CMESSI, not used here, see MESS. MEMDA5 In common CMESSI, see MESS. MESS Program called for most of the message processing. MPT In common CMESSI, see MESS. MUNIT In common CMESSI, not used here, see MESS. NCOL In common CMESSI, see MESS. NDIM In common CMESSI, see MESS. NEG 1 if any number is < 0, else it is 0. NFDAT In common CMESSI, see MESS. NIDAT In common CMESSI, not used here, see MESS. NMDAT In common CMESSI, not used here, see MESS. NTEXT In common CMESSI, not used here, see MESS. OUNIT In common CMESSI, not used here, see MESS. D1MACH External func. giving floating pt. info. about the environment. SUNIT In common CMESSI, not used here, see MESS. TEXT Formal argument, passed to MESS, see there. XARGOK In common CMESSI, see MESS.
%% void dmessxc(long int);
History
2009-09-27 DMESS Krogh Same as below, in another place.
2009-07-23 DMESS Krogh Changed ,1x to :1x in write to FMTF.
2008-06-13 DMESS Krogh Changed -0's to 0.
2007-09-08 DMESS Krogh Fixed definitions of MEVLAS.
2006-10-08 DMESS Krogh Another try, see 2005-05-26
2006-10-08 DMESS Krogh Fixed minor problem in matrix/vector output.
2006-10-01 DMESS Krogh Print NaN's and infity (at least for g77).
2006-07-01 DMESS Krogh messxc => dmessxc (and not static) (for C)
2006-04-07 DMESS Krogh Major rewrite of code for F.Pt. format.
2006-04-04 DMESS Krogh Fixes in C code for vectors & matrices.
2006-04-02 DMESS Krogh Added code for output of sparse vector.
2005-07-10 DMESS Krogh Small adjustment for last correction.
2005-05-26 DMESS Krogh Fixed "*" output in boundary case.
2002-05-16 DMESS Krogh Added way for user to get error count.
2002-03-27 DMESS Krogh Fixed crash when number is -INF.
2001-06-08 DMESS Krogh Eliminated Hollerith in formats.
2001-05-25 DMESS Krogh Added a couple of commas in formats.
1997-06-17 DMESS Krogh In C code made messxc, static.
1996-07-12 DMESS Krogh Changes to use .C. and C%%.
1996-03-30 DMESS Krogh Added external statement.
1994-10-20 DMESS Krogh Changes to use M77CON
1994-09-21 DMESS Krogh Added CHGTYP code.
1994-09-08 DMESS Krogh Added new matrix/vector capabilities.
1994-08-17 DMESS Krogh Removed duplicate save statement.
1994-04-19 DMESS Krogh Removed blank line from DMESS.
1993-05-14 DMESS Krogh Changed TEXT to array of character strings.
1993-04-14 DMESS Krogh Fixes for conversion to C. (C%% comments.)
1992-07-12 DMESS Krogh Fixed so negative KDFDEF works.
1992-05-27 DMESS Krogh Initialized LDFDEF in a data statement.
1992-05-14 DMESS Krogh Put common blocks in save statement.
1992-04-28 DMESS Krogh Corrected minor error in floating pt. format
1992-02-28 DMESS Krogh Initial Code.
Arguments
Type Intent Optional Attributes Name
integer :: MACT(*)
character :: TEXT(*)*(*)
integer :: IDAT(*)
double precision :: FDAT(*)
Calls
Called by
Contents
Common Blocks
CMESSI CMESSC
Source Code
DMESS
Common Blocks
common /CMESSI/
Type Attributes Name Initial
real :: SUNIT
integer :: LHEAD
integer :: KDFDEF
integer :: LINMSG
integer :: LINERR
integer :: MUNIT
real :: EUNIT
integer :: KSCRN
integer :: KDIAG
integer :: MAXERR
integer :: LSTOP
integer :: LPRINT
integer :: KDF
integer :: NTEXT
integer :: NIDAT
integer :: NFDAT
integer :: NMDAT
integer :: MDAT
real :: TABSPA
real :: ERRCNT
integer :: ICHAR0
integer :: IMAG
integer :: INC
integer :: IRC
integer :: ITEXT
integer :: IWF
integer :: IWG
integer :: KDI
integer :: KDJ
integer :: KLINE
integer :: KSHIFT
integer :: KSPEC
integer :: KT
integer :: LASTI
integer :: LBUF
integer :: LENLIN
integer :: LENOUT
integer :: LENTRY
integer :: LENTXT
integer :: LOCBEG
integer :: LSTRT
integer :: LTEXT
integer :: MAXWID
integer :: MPT
integer :: NROW
integer :: NCOL
integer :: NDIM
real :: OUNIT
real :: GOTFMT
real :: XARG
real :: XARGOK
common /CMESSC/
Type Attributes Name Initial
real :: BUF
real :: DOLS
real :: FMTF
real :: FMTG
real :: FMTI
real :: FMTJ
real :: FMTT
real :: FMTIM
Source Code
    subroutine DMESS (MACT, TEXT, IDAT, FDAT)
      !external         D1MACH
      integer          MACT(*), IDAT(*)
      double precision FDAT(*)
      character        TEXT(*)*(*)
      character        FMTSP*29
      integer          ICOL, ID, J, K, KSMA, KBIG, KEXE, LDFDEF, NEG
      double precision FBIG, FOUT, FSMA !, D1MACH
      save LDFDEF, FMTSP
      save /CMESSI/, /CMESSC/
!++ CODE for .C. is inactive
!      integer  kciwid, kccwid, kcrwid, lbeg, lend, lfprec, lgprec
!      common /MESSCC/ kciwid,kccwid,kcrwid,lbeg,lend,lfprec,lgprec
!++ END
!
! ************************** Data from common block ********************
!
! For comments on these variables, see the listing for MESS.
!
      integer   LENBUF, MEVBAS, MEVLAS
      parameter (LENBUF=250)
      parameter (MEVBAS=10)
      parameter (MEVLAS=33)
      logical          XARG, GOTFMT, XARGOK
      integer          ERRCNT, EUNIT, ICHAR0, IRC, IVAR(MEVBAS:MEVLAS), &
     &   IMAG, INC, ITEXT, IWF, IWG, KDF, KDFDEF, KDI, KDIAG, KDJ,      &
     &   KLINE, KSCRN, KSHIFT, KSPEC, KT, MAXERR, LASTI, LBUF, LENLIN,  &
     &   LENOUT, LENTRY, LENTXT, LHEAD, LINERR, LINMSG, LOCBEG, LPRINT, &
     &   LSTOP, LSTRT, LTEXT, MAXWID(2), MDAT(5), MPT, MUNIT, NCOL,     &
     &   NDIM, NFDAT, NIDAT, NMDAT, NROW, NTEXT, OUNIT, SUNIT, TABSPA
!
      character BUF*(LENBUF), DOLS*72, FMTC*7, FMTF*20, FMTG*15,        &
     &  FMTI*7, FMTIM(2)*7, FMTJ*7, FMTR*7, FMTT*15
      common /CMESSI/ SUNIT, LHEAD, KDFDEF, LINMSG, LINERR, MUNIT,      &
     &   EUNIT, KSCRN, KDIAG, MAXERR, LSTOP, LPRINT, KDF, NTEXT, NIDAT, &
     &   NFDAT, NMDAT, MDAT, TABSPA, ERRCNT, ICHAR0, IMAG, INC, IRC,    &
     &   ITEXT, IWF, IWG, KDI, KDJ, KLINE, KSHIFT, KSPEC, KT, LASTI,    &
     &   LBUF, LENLIN, LENOUT, LENTRY, LENTXT, LOCBEG, LSTRT, LTEXT,    &
     &   MAXWID, MPT, NROW, NCOL, NDIM, OUNIT, GOTFMT, XARG, XARGOK
      common /CMESSC / BUF, DOLS, FMTF, FMTG, FMTI, FMTJ, FMTT, FMTIM
      equivalence (IVAR(MEVBAS), SUNIT)
      equivalence (FMTIM(1), FMTR), (FMTIM(2), FMTC)
!
      data LDFDEF / 0 /
!
! ************************* Start of Executable Code *******************
!
      XARGOK = .true.
      if (LDFDEF == 0) then
         LDFDEF = 1 - int(log10(d1mach(3)))
      end if
      KDFDEF = LDFDEF
      KDF = KDFDEF
   10 call MESS (MACT, TEXT, IDAT)
!             4    5    6    7    8    9   10   11
      go to (20, 100, 100, 200, 300, 400, 100, 500), LENTRY-3
      XARGOK = .false.
      LDFDEF = KDFDEF
      return
!                                      Print from FDAT
   20 J = LBUF + 1
      FOUT = FDAT(NFDAT)
      NFDAT = NFDAT + 1
      if (KSPEC >= 8) then
         LBUF = LBUF + IWG
!%% messcc.lend = cmessi.lbuf;
!%% cmessc.buf[messcc.lend] = ' ';
!%% if ((j > 1) && (cmessc.buf[j-2] >= '0') &&
!%%    (cmessc.buf[j-2] <= '9')) cmessc.buf[j++ - 1] = ' ';
!%% sprintf(&cmessc.buf[j-1], cmessc.fmtg, cmessi.iwg,
!%%    messcc.lgprec, fout);
!%% if (cmessc.buf[messcc.lend] != 0) {messcc.lbeg=j; dmessxc(kexe);}
         write (BUF(J:LBUF), FMTG) FOUT
         go to 10
      end if
      if (FOUT <= 0.D0) then
        if (FOUT == 0.D0) then
          FDAT(NFDAT-1) = 0.D0
          FOUT = 0.D0
        else
          NEG = 1
        end if
      else if (FOUT > 0.D0) then
        NEG = 0
      else
!               Must be a Nan
        NEG = 0
        FBIG = 1.0
        FSMA = 1.0
        IWF = 2
        go to 40
      end if
      FBIG = abs(FOUT)
      FSMA = FBIG
      IWF = 2
!                                      Get the format.
   40 continue
      if (KDF == 0) KDF = KDFDEF
      KEXE = 0
      if (FBIG /= 0.D0) then
        if (FSMA == 0.D0) FSMA = 1.D0
        FBIG = FBIG * (1.D0 + .5D0 * .1D0**abs(KDF))
        IWF = IWF + NEG
        if (KDF < 0) then
          KSMA = 0
        else
          KSMA = -log10(FSMA)
          if (FSMA < 1.D0) KSMA = KSMA + 1
        end if
        KBIG = log10(FBIG)
        if (FBIG < 1.D0) then
          KBIG = KBIG - 1
          if (FBIG > 1.D0 - .1D0**abs(KDF-1)) KBIG = 0
        end if
!         This is to get ininities out (at least with g77)
        if ((KBIG < -1000) .or. (KBIG > 1000)) KBIG = 8
        if ((KSMA < -1000) .or. (KSMA > 1000)) KSMA = 8
        if (max(KBIG, 0) + max(KSMA,0) >= 4) then
!               Want to use an "E" format
          KEXE = 3 + max(0, int(log10(dble(max(KBIG,abs(KSMA))+1.D-5))))
          if (KDF < 0) then
            ID = -KDF
          else
            ID = KDF - 1
          end if
          IWF = IWF + ID + KEXE
!++ CODE for ~.C. is active
          if (LENTRY == 10) IWF = IWF - 1
          write (FMTF, '(''(1P,99(E'',I2,''.'',I2,''E'',I1,'':1X))'')') &
     &      IWF, ID, KEXE - 2
!++ CODE for .C. is inactive
!c WATCOM C and others (?) man need an extra 1 here??
!%%    strcpy(cmessc.fmtf, "%*.*E ");
!      lfprec = id
!++ END
          go to 60
        end if
      else
        KSMA = 1
        KBIG = -1
      end if
!               Want to use an "F" format
      if (KDF < 0) then
        ID = -KDF
      else
        ID = KDF + KSMA - 1
      end if
!++ CODE for ~.C. is active
      IWF = IWF + ID + max(KBIG, -1)
      write (FMTF, '(''(0P,99(F'',I2,''.'',I2,'':1X))'')') IWF,ID
!++ CODE for .C. is inactive
!      IWF = IWF + ID + max(KBIG, 0)
!%%    strcpy(cmessc.fmtf, "%*.*f ");
!      lfprec = id
!++ END
   60 if (LENTRY /= 4) then
        IWF = IWF + 1
        if (LENTRY /= 10) go to 10
!               Take care of setup for sparse vector
        IMAG = 0
        do 70 J = LOCBEG, LASTI
          IMAG = max(abs(IMAG), IDAT(J))
   70   continue
        call MESSFI
!  Format forms:     12345678901234567890   123456789012345678  1234567
!                    (1P,99(Edd.ddEd:1X))   (0P,99(Fxx.xx:1X))  (99Idd)
!++ CODE for ~.C. is active
        if (FMTF(8:8) == 'F') then
          FMTSP=                                                        &
     &      '(99(' // FMTI(4:6) // ''') '',0P,' // FMTF(8:18)
        else
          FMTSP=                                                        &
     &     '(99(' // FMTI(4:6) // ''')'' ,1P,' // FMTF(8:20)
        end if
!++ CODE for .C. is inactive
!c Using cmessc.fmtf in place of fmtsp
!%%      if (cmessc.fmtf[4] == 'f') {
!%%      strcpy(cmessc.fmtf, "%*ld) %*.*f ");
!%%      kexe = 0;
!%%      }
!%%      else strcpy(cmessc.fmtf, "%*ld) %*.*E ");
!%%      cmessi.iwf++;
!++ END
        IWF = IWF + KDI + 1
        go to 10
      end if
!
      LBUF = LBUF + IWF
!%% messcc.lend = cmessi.lbuf;
!%% cmessc.buf[messcc.lend] = ' ';
!%% if ((j > 1) && (cmessc.buf[j-2] >= '0') &&
!%%    (cmessc.buf[j-2] <= '9')) cmessc.buf[j++ - 1] = ' ';
!%% sprintf(&cmessc.buf[j-1], cmessc.fmtf, cmessi.iwf,
!%%    messcc.lfprec, fout);
!%% if (cmessc.buf[messcc.lend] != 0) {messcc.lbeg=j; dmessxc(kexe);}
      write (BUF(J:LBUF),FMTF) FOUT
      go to 10
!                                     Get format for a vector or matrix
  100 ICOL = 1
      if (FDAT(LOCBEG) < 0.D0) then
        NEG = 1
      else if (FDAT(LOCBEG) >= 0.D0) then
        NEG = 0
      else
!               Must be a Nan
        NEG = 0
        FBIG = 1.0
        FSMA = 1.0
        go to 110
      end if
      FBIG = abs(FDAT(LOCBEG))
      FSMA = FBIG
  110 do 120 J = LOCBEG, LASTI, INC
        if (FDAT(J) <= 0.D0) then
          if (FDAT(J) == 0.D0) then
            FDAT(J) = 0.D0
          else
            NEG = 1
          end if
        end if
        FBIG = max(FBIG, abs(FDAT(J)))
        if (FSMA == 0.D0) then
          FSMA = abs(FDAT(J))
        else if (FDAT(J) /= 0.D0) then
          FSMA = min(FSMA, abs(FDAT(J)))
        end if
  120 continue
      if (NCOL /= 0) then
         ICOL = ICOL + 1
         LOCBEG = LOCBEG + NDIM
         LASTI = LASTI + NDIM
         if (ICOL <= NCOL) go to 110
      end if
      IWF = 2
      go to 40
!                                    Floating point vector output
  200 continue
!%% messcc.lend = cmessi.lstrt-1;
!%% neg = 0;
!%% for (j=cmessi.mpt; j<cmessi.mpt+cmessi.kline; j++){
!%%   messcc.lbeg = messcc.lend;
!%%   messcc.lend = messcc.lend + cmessi.iwf;
!%%   if (kexe) {
!%%     if (kexe == 5)
!%%        neg = ((fabs(fdat[cmessi.inc*j-1]) < 1.e100)) ? -1: 0;
!%%     else if (kexe ==3) neg = 1;
!%%   }
!%%   sprintf(&cmessc.buf[messcc.lbeg], cmessc.fmtf,
!%%    cmessi.iwf+neg, messcc.lfprec, fdat[cmessi.inc*j-1]);
!%%   if ((kexe == 3) || ((kexe == 5) && neg)) dmessxc(kexe); }
      write(BUF(LSTRT:LBUF),FMTF)(FDAT(K),K=MPT,MPT+INC*(KLINE-1),INC)
!      print '(/A/)', BUF(1:LBUF)
      MPT = MPT + KLINE * INC
      go to 10
!                                    Floating point matrix output
  300 continue
!%% messcc.lend = cmessi.lstrt-1;
!%% neg = 0;
!%% for (j=cmessi.mpt; j<=cmessi.lasti; j+=cmessi.ndim){
!%%    messcc.lbeg = messcc.lend;
!%%    messcc.lend = messcc.lend + cmessi.iwf;
!%%   if (kexe) {
!%%     if (kexe == 5) neg = ((fabs(fdat[j-1]) < 1.e100)) ? -1: 0;
!%%     else if (kexe ==3) neg = 1;
!%%   }
!C%%    if ((messcc.lbeg > 1) && (cmessc.buf[messcc.lbeg-1] >= '0') &&
!C%%       (cmessc.buf[messcc.lbeg-1] <= '9'))
!C%%       cmessc.buf[messcc.lbeg++] = ' ';
!%%    sprintf(&cmessc.buf[messcc.lbeg],
!%%       cmessc.fmtf, cmessi.iwf+neg, messcc.lfprec, fdat[j-1]);
!%%    if ((kexe == 3) || ((kexe == 5) && neg)) dmessxc(kexe); }
      write (BUF(LSTRT:LBUF), FMTF) (FDAT(K), K = MPT, LASTI, NDIM)
      go to 10
!                                    Table output
  400 continue
!%% messcc.lend = cmessi.lstrt-1;
!%% neg=0;
!%% for (j=cmessi.mpt; j<cmessi.mpt+cmessi.kline; j++){
!%%    messcc.lbeg = messcc.lend;
!%%    messcc.lend = messcc.lend + cmessi.iwf;
!C%%    if ((messcc.lbeg > 1) && (cmessc.buf[messcc.lbeg-1] >= '0') &&
!C%%       (cmessc.buf[messcc.lbeg-1] <= '9'))
!C%%       cmessc.buf[messcc.lbeg++] = ' ';
!%%    sprintf(&cmessc.buf[messcc.lbeg], cmessc.fmtf,
!%%       cmessi.iwf+neg, messcc.lfprec, fdat[j-1]); }
      write (BUF(LSTRT:LBUF), FMTF) (FDAT(K), K = MPT, MPT+KLINE-1)
      go to 10
!                                   Sparse vector output
  500 continue
!%%  messcc.lend = -1;
!%%  neg = 0;
!%%  for (j=cmessi.mpt; j<cmessi.mpt+cmessi.kline; j++) {
!%%    messcc.lbeg = messcc.lend + 1;
!%%     messcc.lend = messcc.lend + cmessi.iwf;
!%%   if (kexe) {
!%%     if (kexe == 5) neg = ((fabs(fdat[j-1]) < 1.e100)) ? -1: 0;
!%%     else if (kexe == 3) neg = 1;
!%%   }
!%%   sprintf(&cmessc.buf[messcc.lbeg], cmessc.fmtf, cmessi.kdi,
!%%     idat[j-1],cmessi.iwf-cmessi.kdi-2+neg,messcc.lfprec,fdat[j-1]);
!%%     if ((kexe == 3) || ((kexe == 5) && neg)) dmessxc(kexe); }
      write (BUF(1:LBUF), FMTSP) (IDAT(K),FDAT(K),K=MPT,MPT+KLINE-1)
      MPT = MPT + KLINE
      go to 10
    end subroutine dmess
Call graph
dmess calls messfi
drdivx calls dmess, divadb, diva
divag calls dmess
divadb calls dmess
dzero calls dmess
divain calls dmess
divaa calls dmess
divacr calls dmess
diva calls dmess
drdiva calls diva
drdivdb calls divadb, diva
divao calls divag