DZERO – diva
DZERO Subroutine
261 statements
Source File
subroutine DZERO(X1, F1, X2, F2, MODE, TOL)
Arguments
Type Intent Optional Attributes Name
double precision :: X1
double precision :: F1
double precision :: X2
double precision :: F2
integer :: MODE
2010-04-14 DZERO Krogh No discontinuity message if |F1-F2| small. 2010-04-12 DZERO Krogh Fixed KNKP to get discontinuity diagnostic. 2010-02-20 DZERO Krogh $G => $F for print out of iterations 2008-03-01 DZERO Krogh Minor change in diagnostic print. 2000-12-01 DZERO Krogh Removed unused variable C1P01. 1998-11-01 DZERO Krogh Set so errors stop less easily. 1998-11-01 DZERO Krogh For "mangle", INDIC replaced with MACT(3). 1996-03-30 DZERO Krogh Added external statement. 1995-11-09 DZERO Krogh Fixed so char. data at col. 72 is not ' '. 1994-11-11 DZERO Krogh Declared all vars. 1994-10-20 DZERO Krogh Changes to use M77CON 1994-09-08 DZERO Krogh Added CHGTYP code. 1993-04-27 DZERO Krogh Additions for Conversion to C. 1993-04-13 DZERO Krogh Minor change for new MESS. 1992-04-08 DZERO Krogh Unused label 400 removed. 1992-01-09 DZERO Krogh Moved calc. of XXMXO up (for error msg.) 1991-11-26 DZERO Krogh Converted to new error processor. 1988-08-14 DZERO Krogh Labels runumbered. 1988-03-07 DZERO Krogh Initial code.
--D replaces "?": ?ZERO, ?MESS
SUBROUTINE TO FIND A BOUNDED ZERO
analysis and coding by Fred T.Krogh at the Jet Propulsion Laboratory, Pasadena, Calif. April 25, 1972. Modified for portability, April 1984 by Krogh. Algorithmic changes, vars. added to save stmt., Sept. 1987 by Krogh
Parameters in the calling sequence are defined as follows:
X1 = independent variable F1 = dependent variable -- initially F1=F(X1). When MODE=1 (or 5) the user is to compute F(X1) given X1 X2 = second value of independent variable F2 = F(X2) on the initial entry. When MODE = 2-4, F2=F(X2) and F1F2 .le. 0. MODE is a parameter used for communication between this subroutine and the user. (The user should set MODE only to initialize it to 0 before the first call) =1 compute F(X1) and call $ZERO =2 F(X1) is approximately 0, the iteration is finished and the error criterion is satisfied. =3 same as MODE=2, except the error criterion can not be satisfied. =4 apparently the function has a discontinuity between X1 and X2 -- No zero can be found =5 F1F2 was greater than zero on the first call, and an attempt to bound the zero on both sides have failed. =6 fatal error -- $ZERO was called after mode was set .ge.2. If $ZERO is called again, the program will be stopped. (Unless MODE is set to 0) <0 If MODE is set <0 and $ZERO is called, no action is taken except that print is turned on for -MODE calls to $ZERO. This print gives all values of X and F used in the iteration. TOL is the error tolerance TOL.GT.0 Iterate until values of X1 and X2 are known for which abs(X1-X2) .le. tol and F1*F2 .le. 0. TOL.LT.0 Iterate until a value of X1 is found for which abs(F1) .le. abs(TOL). TOL = 0 Iterate until the zero is determined as precisely as possible. MODE = 3 is impossible in this case.
Parameters in the calling sequence have the following types
double precision :: TOL
Calls
Contents
None
Call graph
dzero calls d1mach, dmess
dmess calls d1mach, messfi