MESSMH – diva
MESSMH Subroutine
131 statements
Source File
subroutine MESSMH(TEXT)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: TEXT(*)
Called by
Contents
Common Blocks
CMESSI CMESSC
Common Blocks
common /CMESSI/
Type Attributes Name Initial
real :: SUNIT
integer :: LHEAD
integer :: KDFDEF
integer :: LINMSG
integer :: LINERR
integer :: MUNIT
real :: EUNIT
integer :: KSCRN
integer :: KDIAG
integer :: MAXERR
integer :: LSTOP
integer :: LPRINT
integer :: KDF
integer :: NTEXT
integer :: NIDAT
integer :: NFDAT
integer :: NMDAT
integer :: MDAT
real :: TABSPA
real :: ERRCNT
integer :: ICHAR0
integer :: IMAG
integer :: INC
integer :: IRC
integer :: ITEXT
integer :: IWF
integer :: IWG
integer :: KDI
integer :: KDJ
integer :: KLINE
integer :: KSHIFT
integer :: KSPEC
integer :: KT
integer :: LASTI
integer :: LBUF
integer :: LENLIN
integer :: LENOUT
integer :: LENTRY
integer :: LENTXT
integer :: LOCBEG
integer :: LSTRT
integer :: LTEXT
integer :: MAXWID
integer :: MPT
integer :: NROW
integer :: NCOL
integer :: NDIM
real :: OUNIT
real :: GOTFMT
real :: XARG
real :: XARGOK
common /CMESSC/
Type Attributes Name Initial
real :: BUF
real :: DOLS
real :: FMTF
real :: FMTG
real :: FMTI
real :: FMTJ
real :: FMTT
real :: FMTIM
Call graph
mess calls messmh
diva calls mess, divaop
messft calls mess
divaop calls mess
divadb calls mess, messft
drdivx calls diva, divadb
drdiva calls diva
drdivdb calls diva, divadb