MESSFI – diva
MESSFI Subroutine
37 statements
Source File
public subroutine MESSFI()
Get the format for the integer IMAG.
** Variable only used here *******
I, K, KD are used in determining number of characters needed to represent IMAG.
Arguments
None
Called by
Contents
Common Blocks
CMESSI CMESSC
Source Code
MESSFI
Common Blocks
common /CMESSI/
Type Attributes Name Initial
real :: SUNIT
integer :: LHEAD
integer :: KDFDEF
integer :: LINMSG
integer :: LINERR
integer :: MUNIT
real :: EUNIT
integer :: KSCRN
integer :: KDIAG
integer :: MAXERR
integer :: LSTOP
integer :: LPRINT
integer :: KDF
integer :: NTEXT
integer :: NIDAT
integer :: NFDAT
integer :: NMDAT
integer :: MDAT
real :: TABSPA
real :: ERRCNT
integer :: ICHAR0
integer :: IMAG
integer :: INC
integer :: IRC
integer :: ITEXT
integer :: IWF
integer :: IWG
integer :: KDI
integer :: KDJ
integer :: KLINE
integer :: KSHIFT
integer :: KSPEC
integer :: KT
integer :: LASTI
integer :: LBUF
integer :: LENLIN
integer :: LENOUT
integer :: LENTRY
integer :: LENTXT
integer :: LOCBEG
integer :: LSTRT
integer :: LTEXT
integer :: MAXWID
integer :: MPT
integer :: NROW
integer :: NCOL
integer :: NDIM
real :: OUNIT
real :: GOTFMT
real :: XARG
real :: XARGOK
common /CMESSC/
Type Attributes Name Initial
real :: BUF
real :: DOLS
real :: FMTF
real :: FMTG
real :: FMTI
real :: FMTJ
real :: FMTT
real :: FMTIM
Source Code
    subroutine MESSFI()
      integer I, K, KD
!
! For comments on other variables, see the listing for MESS.
      integer   LENBUF, MEVBAS, MEVLAS
      parameter (LENBUF=250)
      parameter (MEVBAS=10)
      parameter (MEVLAS=33)
      logical          XARG, GOTFMT, XARGOK
      integer          ERRCNT, EUNIT, ICHAR0, IRC, IVAR(MEVBAS:MEVLAS), &
     &   IMAG, INC, ITEXT, IWF, IWG, KDF, KDFDEF, KDI, KDIAG, KDJ,      &
     &   KLINE, KSCRN, KSHIFT, KSPEC, KT, MAXERR, LASTI, LBUF, LENLIN,  &
     &   LENOUT, LENTRY, LENTXT, LHEAD, LINERR, LINMSG, LOCBEG, LPRINT, &
     &   LSTOP, LSTRT, LTEXT, MAXWID(2), MDAT(5), MPT, MUNIT, NCOL,     &
     &   NDIM, NFDAT, NIDAT, NMDAT, NROW, NTEXT, OUNIT, SUNIT, TABSPA
!
      character BUF*(LENBUF), DOLS*72, FMTC*7, FMTF*20, FMTG*15,        &
     &  FMTI*7, FMTIM(2)*7, FMTJ*7, FMTR*7, FMTT*15
      common /CMESSI/ SUNIT, LHEAD, KDFDEF, LINMSG, LINERR, MUNIT,      &
     &   EUNIT, KSCRN, KDIAG, MAXERR, LSTOP, LPRINT, KDF, NTEXT, NIDAT, &
     &   NFDAT, NMDAT, MDAT, TABSPA, ERRCNT, ICHAR0, IMAG, INC, IRC,    &
     &   ITEXT, IWF, IWG, KDI, KDJ, KLINE, KSHIFT, KSPEC, KT, LASTI,    &
     &   LBUF, LENLIN, LENOUT, LENTRY, LENTXT, LOCBEG, LSTRT, LTEXT,    &
     &   MAXWID, MPT, NROW, NCOL, NDIM, OUNIT, GOTFMT, XARG, XARGOK
      common /CMESSC / BUF, DOLS, FMTF, FMTG, FMTI, FMTJ, FMTT, FMTIM
      equivalence (IVAR(MEVBAS), SUNIT)
      equivalence (FMTIM(1), FMTR), (FMTIM(2), FMTC)
!
      save /CMESSI/, /CMESSC/
!
      KD = 1
      if (KDI < 0) then
!              KDI < 0 to flag need for extra space -- avoids overflows
         KDI = -KDI
         KD = 2
      end if
      K = 1
      if (IMAG < 0) then
         IMAG = -IMAG
         KD = KD + 1
      end if
      I = IMAG / 10
      if (I /= 0) then
   10    K = 10 * K
         KD = KD + 1
         if (I >= K) go to 10
      end if
      if (KD /= KDI) then
         KDI = KD
!++ CODE for ~.C. is active
         FMTI(5:5) = char(ICHAR0 + KDI / 10)
         FMTI(6:6) = char(ICHAR0 + mod(KDI, 10))
!++ CODE for .C. is inactive
!%%      messcc.kciwid = cmessi.kdi;
!++ END
      end if
      return
    end subroutine messfi
Call graph
mess calls messfi, messfd
messfd calls messfi
dmess calls messfi
drdivx calls dmess, divadb, diva
messft calls mess
divadb calls mess, dmess, messft
divaop calls mess
divag calls dmess
dzero calls dmess
divain calls dmess
divaa calls dmess
divacr calls dmess
diva calls mess, dmess, divaop
drdiva calls diva
drdivdb calls divadb, diva
divao calls divag