MESSGS – diva
MESSGS Function
9 statements
Source File
function MESSGS()
Arguments
None
Return Value integer
Called by
Contents
None
Call graph
mess calls messgs
divadb calls mess, messft
messft calls mess
diva calls mess, divaop
divaop calls mess
drdivdb calls divadb, diva
drdivx calls divadb, diva
drdiva calls diva