MESSFT – diva
MESSFT Subroutine
44 statements
Source File
public subroutine MESSFT(MACT, FTEXT)
Prints FTEXT, which contains a Fortran character string, and then call MESS to do the actions in MACT. Actions in MACT can not do anything other than actions that reference MACT. This routine intended for use by library subroutines getting text in the form of a Fortran character string.
Arguments
Type Intent Optional Attributes Name
integer :: MACT(*)
character :: FTEXT*(*)
Calls
Called by
Contents
Common Blocks
CMESSI CMESSC
Source Code
MESSFT
Common Blocks
common /CMESSI/
Type Attributes Name Initial
real :: SUNIT
integer :: LHEAD
integer :: KDFDEF
integer :: LINMSG
integer :: LINERR
integer :: MUNIT
real :: EUNIT
integer :: KSCRN
integer :: KDIAG
integer :: MAXERR
integer :: LSTOP
integer :: LPRINT
integer :: KDF
integer :: NTEXT
integer :: NIDAT
integer :: NFDAT
integer :: NMDAT
integer :: MDAT
real :: TABSPA
real :: ERRCNT
integer :: ICHAR0
integer :: IMAG
integer :: INC
integer :: IRC
integer :: ITEXT
integer :: IWF
integer :: IWG
integer :: KDI
integer :: KDJ
integer :: KLINE
integer :: KSHIFT
integer :: KSPEC
integer :: KT
integer :: LASTI
integer :: LBUF
integer :: LENLIN
integer :: LENOUT
integer :: LENTRY
integer :: LENTXT
integer :: LOCBEG
integer :: LSTRT
integer :: LTEXT
integer :: MAXWID
integer :: MPT
integer :: NROW
integer :: NCOL
integer :: NDIM
real :: OUNIT
real :: GOTFMT
real :: XARG
real :: XARGOK
common /CMESSC/
Type Attributes Name Initial
real :: BUF
real :: DOLS
real :: FMTF
real :: FMTG
real :: FMTI
real :: FMTJ
real :: FMTT
real :: FMTIM
Source Code
      subroutine MESSFT(MACT, FTEXT)
        integer MACT(*)
        character FTEXT*(*)
  !
        integer J, K, IDAT(1)
  !++ CODE for ~.C. is active
        character TEXT(1)*1
  !++ CODE for .C. is inactive
  !      character TEXT(1)*2
  !++ END
        integer, parameter :: MESUNI=10
        integer, parameter :: MEPRNT=21
        integer, parameter :: MECONT=50
  !
        integer, parameter :: LENBUF = 250
        integer, parameter :: MEVBAS = 10
        integer, parameter :: MEVLAS = 33
        logical          XARG, GOTFMT, XARGOK
        integer          ERRCNT, EUNIT, ICHAR0, IRC, IVAR(MEVBAS:MEVLAS), &
       &   IMAG, INC, ITEXT, IWF, IWG, KDF, KDFDEF, KDI, KDIAG, KDJ,      &
       &   KLINE, KSCRN, KSHIFT, KSPEC, KT, MAXERR, LASTI, LBUF, LENLIN,  &
       &   LENOUT, LENTRY, LENTXT, LHEAD, LINERR, LINMSG, LOCBEG, LPRINT, &
       &   LSTOP, LSTRT, LTEXT, MAXWID(2), MDAT(5), MPT, MUNIT, NCOL,     &
       &   NDIM, NFDAT, NIDAT, NMDAT, NROW, NTEXT, OUNIT, SUNIT, TABSPA
  !
        character BUF*(LENBUF), DOLS*72, FMTC*7, FMTF*20, FMTG*15,        &
       &  FMTI*7, FMTIM(2)*7, FMTJ*7, FMTR*7, FMTT*15
        common /CMESSI/ SUNIT, LHEAD, KDFDEF, LINMSG, LINERR, MUNIT,      &
       &   EUNIT, KSCRN, KDIAG, MAXERR, LSTOP, LPRINT, KDF, NTEXT, NIDAT, &
       &   NFDAT, NMDAT, MDAT, TABSPA, ERRCNT, ICHAR0, IMAG, INC, IRC,    &
       &   ITEXT, IWF, IWG, KDI, KDJ, KLINE, KSHIFT, KSPEC, KT, LASTI,    &
       &   LBUF, LENLIN, LENOUT, LENTRY, LENTXT, LOCBEG, LSTRT, LTEXT,    &
       &   MAXWID, MPT, NROW, NCOL, NDIM, OUNIT, GOTFMT, XARG, XARGOK
        common /CMESSC / BUF, DOLS, FMTF, FMTG, FMTI, FMTJ, FMTT, FMTIM
        equivalence (IVAR(MEVBAS), SUNIT)
        equivalence (FMTIM(1), FMTR), (FMTIM(2), FMTC)
        do J = 1, 100, 2
           K = abs(MACT(J))
           if ((K > MEPRNT) .or. (K < MESUNI)) exit
        end do
        K = MACT(J)
        MACT(J) = MECONT
        call MESS(MACT, TEXT, IDAT)
        MACT(J) = K
        K = len(FTEXT)
        NTEXT = 1
        if (K /= 0) then
           if (FTEXT(1:1) == '0') then
              NTEXT = 2
              K = K - 1
              if (LBUF == 0) then
                 BUF(1:1) = ' '
                 LBUF = 1
              end if
           end if
           call MESSPR
           LBUF = K
           BUF(1:K) = FTEXT(NTEXT:NTEXT+K-1)
        end if
        ICHAR0 = ICHAR('0')
        if (MACT(J) /= MECONT) call mess(MACT(J), TEXT, IDAT)
      end subroutine messft
Call graph
messft calls messpr, mess
mess calls messpr, messfd, messmh, messfi, messgs
messfd calls messfi
divadb calls messft