DRDIVDB – diva
DRDIVDB Program
25 statements
Source File
Calls
Contents
Variables
INEQ IFDIM IYDIM NEQ KORD IOPT TSPECS T H DELT TFINAL F Y TOL NDIG MEDDIG MEMLIN MERET
Variables
Type Attributes Name Initial
integer, parameter :: INEQ = 2
2009-11-03 DRDIVDB Krogh -- Used option 11 2001-07-16 DRDIVDB Krogh -- Declared type for paramter TOL. 2001-05-25 DRDIVDB Krogh -- Added comma to format. 1996-06-14 DRDIVDB Krogh Small change in output format 1994-09-12 DRDIVDB Krogh Fixed for CHGTYP. 1993-07-18 DRDIVDB Krogh Fixed to get same output in S.P. and D.P. 1993-05-05 DRDIVDB Krogh Adjusted to simplify conversion to C. 1989-05-04 Fred T. Krogh
--D replaces "?": DR?IVDB, ?IVA, ?IVADB, ?IVAF, ?IVAO, ?MESS
Sample driver for DIVA -- Set up to solve two second order equations. Tests debug output
integer, parameter :: IFDIM = 16*INEQ+1
2009-11-03 DRDIVDB Krogh -- Used option 11 2001-07-16 DRDIVDB Krogh -- Declared type for paramter TOL. 2001-05-25 DRDIVDB Krogh -- Added comma to format. 1996-06-14 DRDIVDB Krogh Small change in output format 1994-09-12 DRDIVDB Krogh Fixed for CHGTYP. 1993-07-18 DRDIVDB Krogh Fixed to get same output in S.P. and D.P. 1993-05-05 DRDIVDB Krogh Adjusted to simplify conversion to C. 1989-05-04 Fred T. Krogh
--D replaces "?": DR?IVDB, ?IVA, ?IVADB, ?IVAF, ?IVAO, ?MESS
Sample driver for DIVA -- Set up to solve two second order equations. Tests debug output
integer, parameter :: IYDIM = 4*INEQ
2009-11-03 DRDIVDB Krogh -- Used option 11 2001-07-16 DRDIVDB Krogh -- Declared type for paramter TOL. 2001-05-25 DRDIVDB Krogh -- Added comma to format. 1996-06-14 DRDIVDB Krogh Small change in output format 1994-09-12 DRDIVDB Krogh Fixed for CHGTYP. 1993-07-18 DRDIVDB Krogh Fixed to get same output in S.P. and D.P. 1993-05-05 DRDIVDB Krogh Adjusted to simplify conversion to C. 1989-05-04 Fred T. Krogh
--D replaces "?": DR?IVDB, ?IVA, ?IVADB, ?IVAF, ?IVAO, ?MESS
Sample driver for DIVA -- Set up to solve two second order equations. Tests debug output
integer :: NEQ
integer :: KORD(6)
integer :: IOPT(7)
double precision :: TSPECS(4)
double precision :: T
double precision :: H
double precision :: DELT
double precision :: TFINAL
double precision :: F(IFDIM)
double precision :: Y(IYDIM)
double precision, parameter :: TOL = 10.D0 **(-NDIG)
integer, parameter :: NDIG = 10
integer, parameter :: MEDDIG = 12
integer, parameter :: MEMLIN = 13
integer, parameter :: MERET = 51
Call graph
drdivdb calls diva, divadb
diva calls mess, optchk, dmess, divaop
divadb calls mess, dmess, messft
mess calls messpr, messgs, messmh, messfi, messfd
dmess calls d1mach, messfi
divaop calls mess, d1mach
messft calls mess, messpr
messfd calls messfi