DRDIVA – diva
DRDIVA Program
21 statements
Source File
Calls
Contents
Variables
INEQ IFDIM IKDIM ITDIM IYDIM NEQ KORD IOPT TSPECS Y T H DELT TFINAL NDIG F TOL
Variables
Type Attributes Name Initial
integer, parameter :: INEQ = 2
2010-06-09 DRDIVA Krogh Used parameters for all dimenssions. 2001-05-25 DRDIVA Krogh Minor change for making .f90 version. 1996-06-14 DRDIVA Krogh Small change in output format 1994-11-02 DRDIVA Krogh Changes to use M77CON 1994-07-18 DRDIVA Krogh Last change. --D replaces "?": DR?IVA, ?IVA, ?IVAF, ?IVAO Sample driver for DIVA -- Set up to solve two second order equations.
integer, parameter :: IFDIM = 16*INEQ+1
2010-06-09 DRDIVA Krogh Used parameters for all dimenssions. 2001-05-25 DRDIVA Krogh Minor change for making .f90 version. 1996-06-14 DRDIVA Krogh Small change in output format 1994-11-02 DRDIVA Krogh Changes to use M77CON 1994-07-18 DRDIVA Krogh Last change. --D replaces "?": DR?IVA, ?IVA, ?IVAF, ?IVAO Sample driver for DIVA -- Set up to solve two second order equations.
integer, parameter :: IKDIM = 6
2010-06-09 DRDIVA Krogh Used parameters for all dimenssions. 2001-05-25 DRDIVA Krogh Minor change for making .f90 version. 1996-06-14 DRDIVA Krogh Small change in output format 1994-11-02 DRDIVA Krogh Changes to use M77CON 1994-07-18 DRDIVA Krogh Last change. --D replaces "?": DR?IVA, ?IVA, ?IVAF, ?IVAO Sample driver for DIVA -- Set up to solve two second order equations.
integer, parameter :: ITDIM = 4
2010-06-09 DRDIVA Krogh Used parameters for all dimenssions. 2001-05-25 DRDIVA Krogh Minor change for making .f90 version. 1996-06-14 DRDIVA Krogh Small change in output format 1994-11-02 DRDIVA Krogh Changes to use M77CON 1994-07-18 DRDIVA Krogh Last change. --D replaces "?": DR?IVA, ?IVA, ?IVAF, ?IVAO Sample driver for DIVA -- Set up to solve two second order equations.
integer, parameter :: IYDIM = 4*INEQ
2010-06-09 DRDIVA Krogh Used parameters for all dimenssions. 2001-05-25 DRDIVA Krogh Minor change for making .f90 version. 1996-06-14 DRDIVA Krogh Small change in output format 1994-11-02 DRDIVA Krogh Changes to use M77CON 1994-07-18 DRDIVA Krogh Last change. --D replaces "?": DR?IVA, ?IVA, ?IVAF, ?IVAO Sample driver for DIVA -- Set up to solve two second order equations.
integer :: NEQ
integer :: KORD(IKDIM)
integer :: IOPT(6)
double precision :: TSPECS(ITDIM)
double precision :: Y(IYDIM)
double precision :: T
double precision :: H
double precision :: DELT
double precision :: TFINAL
integer, parameter :: NDIG = 10
double precision :: F(IFDIM)
double precision, parameter :: TOL = 10.D0 **(-NDIG)
Call graph
drdiva calls diva
diva calls dmess, mess, optchk, divaop
dmess calls d1mach, messfi
mess calls messpr, messfd, messgs, messmh, messfi
divaop calls mess, d1mach
messfd calls messfi