DRDIVX – diva
DRDIVX Program
37 statements
Source File
Calls
Contents
Variables
INEQ IFDIM IYDIM NEQ KORD IOPT ID TSPECS T H DELT TFINAL F Y RD TOL NDIG MEDDIG MERET MACT MDUMMY
Variables
Type Attributes Name Initial
integer, parameter :: INEQ = 2
2009-11-03 DRDIVX Krogh -- Used option 11 2006-04-10 DRDIVX Krogh -- * dim for Y and F in divao. 2001-07-16 DRDIVX Krogh -- Declared type for parameter TOL. 2001-05-25 DRDIVX Krogh Minor change for making .f90 version. 1996-06-14 DRDIVX Krogh Small change in output format 1994-09-12 DRDIVX Krogh Fixed for CHGTYP. 1994-08-19 DRDIVX Krogh Specified no. of digits in the output. 1993-05-05 DRDIVX Krogh Adjusted to simplify conversion to C. 1992-03-10 DRDIVX Fred T. Krogh
--D replaces "?": DR?IVX, ?IVA, ?IVACO, ?IVADB, ?IVAF, ?IVAG, ?IVAO, --& ?MESS
Sample driver for DIVA -- Set up to solve two second order equations. Test DIVAG, DIVADB, and DIVACO
integer, parameter :: IFDIM = 16*INEQ+1
2009-11-03 DRDIVX Krogh -- Used option 11 2006-04-10 DRDIVX Krogh -- * dim for Y and F in divao. 2001-07-16 DRDIVX Krogh -- Declared type for parameter TOL. 2001-05-25 DRDIVX Krogh Minor change for making .f90 version. 1996-06-14 DRDIVX Krogh Small change in output format 1994-09-12 DRDIVX Krogh Fixed for CHGTYP. 1994-08-19 DRDIVX Krogh Specified no. of digits in the output. 1993-05-05 DRDIVX Krogh Adjusted to simplify conversion to C. 1992-03-10 DRDIVX Fred T. Krogh
--D replaces "?": DR?IVX, ?IVA, ?IVACO, ?IVADB, ?IVAF, ?IVAG, ?IVAO, --& ?MESS
Sample driver for DIVA -- Set up to solve two second order equations. Test DIVAG, DIVADB, and DIVACO
integer, parameter :: IYDIM = 4*INEQ
2009-11-03 DRDIVX Krogh -- Used option 11 2006-04-10 DRDIVX Krogh -- * dim for Y and F in divao. 2001-07-16 DRDIVX Krogh -- Declared type for parameter TOL. 2001-05-25 DRDIVX Krogh Minor change for making .f90 version. 1996-06-14 DRDIVX Krogh Small change in output format 1994-09-12 DRDIVX Krogh Fixed for CHGTYP. 1994-08-19 DRDIVX Krogh Specified no. of digits in the output. 1993-05-05 DRDIVX Krogh Adjusted to simplify conversion to C. 1992-03-10 DRDIVX Fred T. Krogh
--D replaces "?": DR?IVX, ?IVA, ?IVACO, ?IVADB, ?IVAF, ?IVAG, ?IVAO, --& ?MESS
Sample driver for DIVA -- Set up to solve two second order equations. Test DIVAG, DIVADB, and DIVACO
integer :: NEQ
integer :: KORD(6)
integer :: IOPT(12)
integer :: ID(5)
double precision :: TSPECS(4)
double precision :: T
double precision :: H
double precision :: DELT
double precision :: TFINAL
double precision :: F(IFDIM)
double precision :: Y(IYDIM)
double precision :: RD(3)
double precision, parameter :: TOL = 10.D0 **(-NDIG)
integer, parameter :: NDIG = 10
integer, parameter :: MEDDIG = 12
integer, parameter :: MERET = 51
integer :: MACT(3)
character :: MDUMMY(1)*2
Call graph
drdivx calls divadb, diva, dmess, divaco
divadb calls dmess, messft, mess
diva calls dmess, divaop, optchk, mess
dmess calls messfi, d1mach
divaop calls mess, d1mach
messft calls mess, messpr
mess calls messfi, messgs, messmh, messfd, messpr
messfd calls messfi